### ISSUE TITLE
Some keyboard presses combination doesn't work e.g shift+arrow 

### ISSUE THREAD

**Issue by karamjaber** [moses-palmer/pynput#107]
I'm using latest pynput(1.4) and when i try to do a key press that combined from modifier+key where key is not a letter doesn't work.
The code i tried:
```
from pynput.keyboard import Key, Controller

keyboard = Controller()

with keyboard.pressed(Key.shift):
    keyboard.press(Key.down)
    keyboard.release(Key.down)
```
but the following code works as expected:
```
keyboard = Controller()

with keyboard.pressed(Key.shift):
    keyboard.press('a')
    keyboard.release('a')
```
Am I doing something wrong ?

**Comment by moses-palmer** [comment]
Thank you for your report, and sorry for the late reply.

I have tested your snippet on _Windows_ and _Linux_, and I can confirm that it indeed does not work on _Windows_.

[`pynput.keyboard.Controller.press`](https://github.com/moses-palmer/pynput/blob/9cebc07326690af980acf02a477ed67e9f588f13/lib/pynput/keyboard/_base.py#L341) treats character arguments as a special case: if <kbd>Shift</kbd> is pressed, the character is upper cased ([see here](https://github.com/moses-palmer/pynput/blob/9cebc07326690af980acf02a477ed67e9f588f13/lib/pynput/keyboard/_base.py#L555)). That is why your second example works.

It appears that virtually pressed modifiers do not generate short cut commands on Windows. The function used to send the virtual key presses, [`SendInput`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-sendinput), does not appear to support passing the modifiers as flags, so I do not have a solution readily available.

**Comment by moses-palmer** [comment]
This issue is supposedly resolved on the _master_ branch. Is it possible for you to test?

**Comment by moses-palmer** [comment]
I have tested this with the _master_ branch, and the issue seems resolved. If not, please reopen.
