### ISSUE TITLE
Question: How is the Exception handling supposed to work?

### ISSUE THREAD

**Issue by RedFantom** [moses-palmer/pynput#108]
**Background**
I have a program in which I run multiple Listeners for a long period of time, usually somewhere over half an hour to even over an hour at a time. It is very useful to me if exceptions anywhere in the program are reported immediately, as for most parts of the code unittests is not possible (given the structure and nature of the program), so I can debug issues as soon as I see them appear.

Currently, the pynput Listeners hide the exceptions from me, completely. I lost quite a bit of time tracking down the issue to the pynput Listeners. I was a bit disappointed when I discovered that I can only catch the errors upon joining a Thread, which is only done after I have performed a testing session.

**Observed Behaviour**
Using my fork of the repository, I have determined the behaviour to be the following:
`lib/pynput/_utils/__init__.py`
```python
@classmethod
def _emitter(cls, f):
    @functools.wraps(f)
    def inner(self, *args, **kwargs):
        try:
            return f(self, *args, **kwargs)  # Call the callback for the event
        except Exception as e:  # Exception occurred in callback
            if not isinstance(e, self._HANDLED_EXCEPTIONS):
                # Schedule for raising upon .join()
                self._queue.put(
                    None if isinstance(e, cls.StopException)
                    else sys.exc_info())
                self.stop()  # Cleanup
            # XXX Never reached
            raise
    return inner
```

**Expected Behaviour**
I am not familiar with Threading daemons, but I would expect the error to be re-raised at the end of the `try-except`-block. However, the `raise` point is never reached, thus I do not see anything appear on `stderr`. Is this the desired behaviour? Because of it is, I would like propose a PR for my branch of the repository.

**Other Details**
Operating System: Ubuntu 18.04 64-bit
Back-end: Xorg

**Comment by moses-palmer** [comment]
Thank you for your input, and your effort.

I am a bit uncertain about what your problem is, however. As is documented [here](https://pynput.readthedocs.io/en/latest/mouse.html#handling-mouse-listener-errors) and [here](https://pynput.readthedocs.io/en/latest/keyboard.html#handling-keyboard-listener-errors), any errors raised by callback methods will be re-raised _when you join the listener_.

Since callbacks happen in a separate thread, and are initiated from the operating system, I cannot se any other way to do it. If you want immediate notification when your callback fails to handle an exception, you may want to wrap it thus:
```python
import logging

def log_exception(f):
    def inner(*args, **kwargs):
        try:
            return f(*args, **kwargs)
        except:
            logging.getLogger(f.__globals__['__name__']).exception(
                '%s failed to handle an exception', f.__name__)
    return inner

@log_exception
def my_monitor_callback(*args, **kwargs):
    """A callback for a keyboard monitor.
    """
    raise Exception('coffee!')
```

**Comment by RedFantom** [comment]
Thank you for your reply. I see then that there is no way other than to fetch the exception in the library other than joining the Listener. Callbacks of course happen in the Listener thread, but even if an exception occurs in a different `Thread`, or `Process` even, the error gets printed to the same `stderr` as the main thread. It may be desirable to do cleanup first to not leave any hooks or callbacks in place, but getting immediate feedback is possible without returning the exception to the main thread.

What pretty much happens when an exception occurs in a thread is that the context of the other Thread stops, as an unhandled exception was thrown, and its traceback gets printed to `stderr`. The main thread just happily continues operating, as it is independent from the context of the other thread. The option to make this happen would seem desirable in some use-cases.

I suppose wrapping my callback with such decorators would indeed work, but I was hoping for some function or argument in the library. Catching the error on joining really is not an option for me, given the long run-time of my program.

**Comment by moses-palmer** [comment]
Do you get exceptions in your listener thread in locations other than in your listener callback? If so, that is a bug in *pynput* that should be addressed, otherwise handling them in the callback code seems like the reasonable choice.

**Comment by RedFantom** [comment]
Coding errors happen, and having them hidden away for a long time and even then not knowing where to start debugging it is just an experience I think others would like to avoid as well. Exceptions that you expect should always be prevented, it's the unexpected you really want to know about.

Requiring the user to wrap the callbacks in `try/except` blocks and printing the traceback to stdout or somehow pass it to a place where it is *not* caught by the `try/except` block in the `pynput` library without an option to turn it off is, in my opinion, a weird design choice. It's not that I don't appreciate errors being passed to the `MainThread`, it's the difficulty of preventing the `pynput` library from grabbing it in the first place that I do not quite agree with.

Still, it appears we differ in opinion on that topic, and thus I will simply use my own fork of the library instead. Thank you for your time.

**Comment by moses-palmer** [comment]
With your final comment, I'm finally starting to understand what you mean.

Am I right to think that you would like the default behaviour on exceptions to be to immediately stop the listener, thus allowing the exception to be caught immediately by propagation to the main thread?

If so, I think your concern is very valid. This would unfortunately break the API, and would thus need a major version bump.

I will definitely consider this for the next major update.

**Comment by RedFantom** [comment]
Okay, so I think we still don't really understand each other.

Immediate propagation to the main thread would be nice, but would indeed require an API breaking change. What I am proposing is simply allowing the user the option to not have the Listener catch all the exceptions in its own Thread for propagation to the main thread in the first place.

Exceptions in separate threads simply have their tracebacks printed to stderr and then crash the Listener, so there is immediate feedback. Because all exceptions in the callbacks are caught by default, escaping this `try/except` block requires quite some additional code for all listeners. It would be more efficient (both in terms of amount of code and in terms of speed) to simply provide the option to skip the handling of exceptions, like [this](https://github.com/moses-palmer/pynput/compare/master...RedFantom:master).

My initial question concerned the execution of the code. I had expected errors caught in the Listener callbacks to be printed to `stderr` by default because there is a `raise` at the end of the `try/except` block, but it is never executed. That is what really confused me.

A simple option that disables the handling of exceptions makes it much easier to debug errors that occur in the listeners. Making them propagate to the main thread would be the best solution in general, but I do not really see a way to do that properly

**Comment by moses-palmer** [comment]
OK, thank you for your clarification!

In that case, would not a simple log statement suffice? That would maintain the behaviour that uncaught exceptions do not crash the listener, but it would still provide immediate feedback.

**Comment by RedFantom** [comment]
While a log statement suffices in most cases, having the actual full traceback as printed to `stderr` offers advantages in some IDEs as well as for error reporting services (like `Sentry` with a `sys` hook), and my patch would not change the default behaviour or break existing code. Personally, I think it would make things just a little more flexible and obvious, but it's up to you.

**Comment by moses-palmer** [comment]
[`logging.Logger.exception`](https://docs.python.org/3/library/logging.html#logging.Logger.exception) includes a stack trace, and the presentation and target can be configured.

And sorry for being so stubborn ;-) I prefer to solve this problem by adding simple log statements---something I was already planning to do---rather than making the exception handling logic more complicated.

**Comment by RedFantom** [comment]
That's okay. If there is at least some way to get immediate feedback without too much hassle (like requiring users to catch all exceptions themselves through function decorators or otherwise), I think any of the given options would work just fine. Even if we disagree on what would be the most informative, flexible or otherwise preferable way of doing so, that is just fine.

Thank you for taking the time to answer my question, as well as expanding on it. Your library is really useful!
