### ISSUE TITLE
Middle Button not working in Win8.1

### ISSUE THREAD

**Issue by jollysean** [moses-palmer/pynput#11]
Hi,

Is there any known issue that middle button(wheel), can't work?
I see it is defined in [1](https://github.com/moses-palmer/pynput/blob/0bba82583a3892b495227b0c85f022524493c25c/lib/pynput/mouse/_base.py#L43) & [2](https://github.com/moses-palmer/pynput/blob/0bba82583a3892b495227b0c85f022524493c25c/lib/pynput/mouse/_win32.py#L49)

**Comment by moses-palmer** [comment]
Up until now it was an unknown issue :-)

This has been fixed in version *1.1.7*.
