### ISSUE TITLE
Sphinx dependency

### ISSUE THREAD

**Issue by marcinn** [moses-palmer/pynput#110]
Hi.

Dependency on sphinx is not necessary. It is required for making a release, but not to run/use pynput itself. I'd recommend to prepare additional `requirements.txt` file for devtools, or define spinx in `extras_require` instead of `install_requires`.

https://stackoverflow.com/a/28842733/512594 

Thank you.

**Comment by moses-palmer** [comment]
Did you intent to report this issue for this project?

_sphinx_ is not a runtime dependency of _pynput_. This can be verified by running `pip install pynput`. It is a setup dependency passed in the `setup_requires` argument though.

**Comment by marcinn** [comment]
Oh, I'm so sorry. I didn't noticed that. And yes, AUR packages have incorrect deps. Please delete/close the issue.
