### ISSUE TITLE
Question: About the windows limitation

### ISSUE THREAD

**Issue by gabycperezdias** [moses-palmer/pynput#111]
Hi,

I am trying to use the library, but I noticed that the way it works on Windows is very random. I know this is a platform limitation listed in the docs, but I would like to know if there is a plan to fix it... Or at least, do you know why this happens? I am not very familiar with how all the magic works behind the curtains, but maybe if you say (if you already know, of course) the problem we might be able to help each other...

Thanks

**Comment by moses-palmer** [comment]
Hi,

I appreciate your offering to help! As far as I know, the greatest limitation on _Windows_ is with the keyboard listener and how it composes characters from dead keys. Is this your experience as well? Another issue is with certain applications, such as `cmd.exe`, interfering with the keyboard layout and while focused causing the operating system to emit unexpected key codes.

I think both these problems stem from the use of [`ToUnicodeEx`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-tounicodeex). As stated in the documentation, it modifies the in-kernel keyboard buffer, and will thus not produce the same output if called twice with the same input.

The solution, I suppose, would be to maintain a separate buffer in the listener instance, and manually combine keys. This would somehow need to take into account the keyboard layout.

If you would like to make an attempt to implement this, you're welcome! I may be able to give you a few pointers, but I don't use Windows as my main operating system---I have it installed in a VM just to be able to run the tests.

**Comment by gabycperezdias** [comment]
In my case, when running the script, the majority of times I don't receive any events of pressed keys...
It is not even the case of wrong keycodes... is no keys at all... but it does work inside a console for example... but the same code inside a script.py doesn't.

And yes, inside the console, I get the same keycode for ctrl and Enter for example...

**Comment by moses-palmer** [comment]
The Windows keyboard listener limitation is supposedly resolved. Is it possible for you to test the _master_ branch?

**Comment by moses-palmer** [comment]
Due to lack of feedback, I will close this issue.
