### ISSUE TITLE
Not able to select text in pynput

### ISSUE THREAD

**Issue by Kaushal28** [moses-palmer/pynput#113]
For this purpose, I'm first pressing shift and then pressing multiple times left arrow key. So that the text left to the cursor id selected and can be further used for copying purpose.

`from pynput.keyboard import Key
from pynput.keyboard import Controller

keyboard = Controller()

with keyboard.pressed(Key.shift):
    keyboard.press(Key.left)
    keyboard.release(Key.left)
    keyboard.press(Key.left)
    keyboard.release(Key.left)`

This moves my cursor to left by 2 steps but even if the shift is pressed, the text is not getting selected.

**Comment by moses-palmer** [comment]
Thank you for your report.

What operating system do you use? The behaviour appears to be slightly different, and *pynput* may need to handle modifiers better for some platforms.

**Comment by Kaushal28** [comment]
I'm using windows 10

**Comment by tan-90** [comment]
I have the same problem and it happens both when using ´with keyboard.pressed(Key.shift):´ and when using `keyboard.press(Key.shift) # move cursor keyboard.release(Key.shift)`.

I'm also using Windows 10.

**Comment by climaticGuru** [comment]
Is there a Workaround for following not working code under Windows 7:
```
with self.keyboard.pressed(Key.shift):
    with self.keyboard.pressed(Key.ctrl):
        self.keyboard.press(Key.down)
        self.keyboard.release(Key.down)
```
Everything works fine but unfortunately the Shift+Ctrl command for selecting table rows is not working.

Python 3.6.2
Pynput 1.11.0
Windows 7

**Comment by moses-palmer** [comment]
The current _master_ branch contains a solution to this problem, so I will close this issue.
