### ISSUE TITLE
Recognize action like typing on a text field in conjunction with mouse polling

### ISSUE THREAD

**Issue by theshinyknight** [moses-palmer/pynput#119]
Hi, I am really enjoying the library; which is very helpful to automate keyboard and mouse.

Currently I am writing a parser that is able to read actions from mouse and keyboard, so I can. then play back these actions. your listeners are helping a lot in this effort; although I am finding hard to recognize some actions.

In particular, when using shortcuts, like CMD-C, CMD-v and such.  also if you consider a simple workflow of a user going on a website, clicking on the text field to input username, then click or tab to go to the password field and then click log in; you may notice that to record this behavior you need to cache a sequence of chars typed in the field, and know that if tab or return or click; you need to save that stream in a string and move on to the next action.

Is there an easy way to record workflows for keypress combinations and scenarios where you interact with both mouse and keyboard? I am writing my implementation but I would rather use something that exist already. I did check the documentation for pynput and found nothing.

Thanks

**Comment by moses-palmer** [comment]
Thank you for the positive feedback!

As far as I know there is no published package providing this functionality. *pynput* does not provide it as it is somewhat out of scope. I wish you good luck in finding an implementation, or finishing your own!
