### ISSUE TITLE
Convert Keys to System Unicode

### ISSUE THREAD

**Issue by jollysean** [moses-palmer/pynput#12]
Hi,

I am trying to convert Keys(mouse and keyboard) to there unicode characters, by 
`ord(key)`

But, I get this error.

> TypeError: ord() expected string of length 1, but KeyCode found

Is there a way to convert it? Or a table to do conversion https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731%28v=vs.85%29.aspx

**Comment by moses-palmer** [comment]
A `KeyCode` has [a `char` attribute](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L37) that you can use to get the unicode ordinal. It may be `None` for special keys with no corresponding string representation; in that case you may use [the `vk` attribute](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L43), which is *some* platform dependent integer value. On *Windows*, the `vk` attribute corresponds to the values in the document you linked.
