### ISSUE TITLE
key combination listener not implemented

### ISSUE THREAD

**Issue by aditya-rawat-99** [moses-palmer/pynput#120]
pynput is a  great library and is exactly what I wanted for my project. But I see you still haven't implemented the listener for handling key combinations, I know you mentioned a workaround for the problem and it's really great too. I am really excited about it and hope to hear from you really soon.

Thank you

**Comment by segalion** [comment]
Try [bindglobal
](https://github.com/segalion/bindglobal)

`pip install bindglobal`

**Comment by moses-palmer** [comment]
With *pystray 1.6.0*, support for global hotkeys has been merged.
