### ISSUE TITLE
Listener(..., suppress=True) is "a bit" too powerful

### ISSUE THREAD

**Issue by mcondarelli** [moses-palmer/pynput#121]
Opening a `Listener` with `suppress=True` actually grabs all chars typed wherever on any window (X11), this is far too much.

How can I grab chars typed in the window where the script was launched (and, eventually, in any window spawned by the sane process) without affecting "unrelated" windows?

Current behavior prevents even debugger usage and, after a while, triggers X11 shutdown/restart.

I just wanted to suppress char echo, but I ended up choking the system!

Perhaps I'm not using the right tool.
What I need is to get characters as soon as they arrive (no "cooked" line discipline) and consume them (no echo).
Did I miss something?
TiA!

**Comment by HetorusNL** [comment]
I would like to know whether this is possible too, also experienced the X11 shutdown/restart (eventually resulting in a segfault killing the entire DE and returning to login screen:  
`Nov 27 14:54:09 Machine-name kernel: [20994.789364] Chrome_~dThread[1920]: segfault at 0 ip 00007f1ad60ac799 sp 00007f1ad1097b00 error 6 in libxul.so[7f1ad5da0000+50c8000]`

**Comment by moses-palmer** [comment]
I have pushed a temporary branch [feature-xlib-suppress-select](https://github.com/moses-palmer/pynput/tree/feature-xlib-suppress-select) with an attempt to solve this.

This feature branch adds an argument to the listener constructors: `xorg_suppress_selector`. The value should be the window for which to suppress events.

Please note that I have not yet tested this feature---I am currently on a system running *Wayland*---but I would appreciate if you did find the time!

**Comment by mcondarelli** [comment]
I dropped use of pynput and I'm a bit busy at the moment, but I will try to find dome time to test the branch. Probably next weekend.

**Comment by fariquelme** [comment]
Any luck with this bug ?

**Comment by fariquelme** [comment]
i installed the [feature-xlib-suppress-select](https://github.com/moses-palmer/pynput/tree/feature-xlib-suppress-select) and i'm getting the following errors (plus X11 is still crushes):

Whenever i starting/stopping the Listener with suppress set to True by ``` return False ``` on a Callback, i get the following error:
```
Unhandled exception in listener callback
Traceback (most recent call last):
  File "/home/fariquelme/.pyenv/versions/py36/lib/python3.6/site-packages/pynput/_util/__init__.py", line 157, in inner
    return f(self, *args, **kwargs)
  File "/home/fariquelme/.pyenv/versions/py36/lib/python3.6/site-packages/pynput/_util/xorg.py", line 458, in _handler
    self._handle(self._display_stop, event)
  File "/home/fariquelme/.pyenv/versions/py36/lib/python3.6/site-packages/pynput/keyboard/_xorg.py", line 518, in _handle
    self.on_press(key)
  File "/home/fariquelme/.pyenv/versions/py36/lib/python3.6/site-packages/pynput/_util/__init__.py", line 79, in inner
    raise self.StopException()
pynput._util.AbstractListener.StopException
```

**Comment by moses-palmer** [comment]
Due to lack of feedback, I will close this issue. If you still think it is relevant, please reopen.
