### ISSUE TITLE
On mac, holding shift to type certain characters(like %) doesn't work

### ISSUE THREAD

**Issue by kevin132713** [moses-palmer/pynput#124]
Sometimes holding shift works fine, like for all letters and :, but for others, like %, trying to type it(shift + 5 in this case) just types the original character and not the shifted version(5 in this case)

**Comment by moses-palmer** [comment]
Duplicate of #83

**Comment by moses-palmer** [comment]
#83 contains two separate issues, of which one is fixed. I will reopen this issue, since it contains only the remaining one.
