### ISSUE TITLE
Horizontal mouse scroll does not work

### ISSUE THREAD

**Issue by gilleswijnker** [moses-palmer/pynput#13]
A horizontal mouse scroll on Windows does not work.
In 'mouse./_win32.py', the '_scroll' function uses the 'dy' variable on both SendInput calls. The second call should state 'mouseData=dx' (line 88).

**Comment by moses-palmer** [comment]
Thank you for the detailed report!

I just relased *pynput 1.2*, which includes a fix for this issue.
