### ISSUE TITLE
from_vk cannot recreate keys

### ISSUE THREAD

**Issue by DerDonut** [moses-palmer/pynput#130]
Detecting keys with pynput on my machine (Ubuntu 18.10 using python 3.6) works well an i use the following code to display the virtual key code:
```
import pynput

def on_press(key):
    if type(key) is pynput.keyboard.Key:
        print('{0} pressed, vk: {1}'.format(key, key.value.vk))
    elif type(key) is pynput.keyboard.KeyCode:
        print('{0} pressed, vk: {1}'.format(key, key.vk))

def on_release(key):
    if type(key) is pynput.keyboard.Key:
        print('{0} released, vk: {1}'.format(key, key.value.vk))
    elif type(key) is pynput.keyboard.KeyCode:
        print('{0} released, vk: {1}'.format(key, key.vk))

with pynput.keyboard.Listener (
    on_press=on_press,
    on_release=on_release
) as listener:
    listener.join()
```
If i try to trigger these keys in code, the key pressed on the keyboard and that triggered by the library does not match. For Example, if I press 'a' on my keyboard, the code above outputs:
> 'a' pressed, vk: 38
> 'a' released, vk: 38

If I now use that in another script on the same machine:
```
import pynput

keyboardController = pynput.keyboard.Controller()
key = pynput.keyboard.KeyCode.from_vk(38)
keyboardController.press(key)
keyboardController.release(key)
```
the library will type '6' and not 'a'. Are there additional parameters to pass with function from_vk() to recreated recorded virtual key codes? It seems like the function from_vk() expects ascii code style values, but the triggered keys do not deliver those. Using `key = pynput.keyboard.KeyCode.from_vk(97)` will type 'a' (as 97 is the ascii code for 'a').

**Comment by DerDonut** [comment]
Update: My misunderstanding seems not to be related to function from_vk. I wrote a script which should just retype a key on release:
```
import pynput


def on_press(key):
    global softwareTriggered

    if type(key) is pynput.keyboard.Key:
        output = '{0} pressed, vk: {1}'.format(key, key.value.vk)
    elif type(key) is pynput.keyboard.KeyCode:
        output ='{0} pressed, vk: {1}'.format(key, key.vk)

    if softwareTriggered:
        print("software Triggered: " + output)
    else:
        print("System Triggered: " + output)

def on_release(key):
    global keycontr, softwareTriggered

    if type(key) is pynput.keyboard.Key:
        output = '{0} released, vk: {1}'.format(key, key.value.vk)
    elif type(key) is pynput.keyboard.KeyCode:
        output ='{0} released, vk: {1}'.format(key, key.vk)

    if softwareTriggered:
        print("software Triggered: " + output)
    else:
        print("System Triggered: " + output)

    if not softwareTriggered:
        print("Retyping.")
        softwareTriggered = True
        keycontr.press(key)
        keycontr.release(key)
        softwareTriggered = False


keycontr = pynput.keyboard.Controller()
softwareTriggered = False
print("Waiting 3 seconds...")
time.sleep(3)
print("Starting Key Tests.")

with pynput.keyboard.Listener(
    on_press=on_press,
    on_release=on_release
) as listener:
    listener.join()
```
and pressing the 'a' key on my keyboard will produce the following output (I removed the stacktrace):

> Waiting 3 seconds...
> Starting Key Tests.
> System Triggered: 'a' pressed, vk: 38
> System Triggered: 'a' released, vk: 38
> Retyping.
> software Triggered: 'a' pressed, vk: 38
> software Triggered: 'a' released, vk: 38
> System Triggered: '6' pressed, vk: 15
> System Triggered: '6' released, vk: 15
> Retyping.
> pynput._util.xorg.X11Error: [(BadValue(<Xlib.display._BaseDisplay object at 0x7f552ee7e630>, b'\x00\x02\x13\x00\x00\x00\x00\x00\x02\x00\x84\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'), None)]

The editor (atom in my case) in which the cursor is placed shows: a6 after the script crashed.

So, one a is triggered correctly from the system. The listener detects the software-triggered press of 'a' (with vk=38), but the editor does not. Afterwards the system additionally triggers the press and release of '6' - i have no idea why. This non-existing keystroke leads to a software-triggered key input with vk=15 which causes an exception in pynput._xorg.
What am I missing?

**Comment by moses-palmer** [comment]
When I run you snippet, I get an infinite number of key presses. This is caused by the asynchronous nature of X; you attempt to use use softwareTriggered as a lock around the injected events, but you will likely not receive the callback until after you have exited your code block, an thus the software triggered event will yet again trigger an event injection.

As to why you get the a/6 combination, I do not know; what keyboard layout do you use? When running the script, I consistently get a `KeyCode.from_vk(97)`.

**Comment by moses-palmer** [comment]
Ah, but I tested from the master branch!

Commit [12d6f77](https://github.com/moses-palmer/pynput/commit/12d6f779462114459dc6730459887888b95e49ae) specifically addresses this. Could you test it and see if it fixes you issue?

**Comment by DerDonut** [comment]
Oh yes, that did the trick.
I installed pynput into my virtual environment in pycharm. Pycharm was not able to get version 1.4.1, even when I added this repository directly when using the package manager (i had v1.4). Using the environment terminal he finally installed version 1.4.1
