### ISSUE TITLE
Mouse listener suppress clicks, but not movement?

### ISSUE THREAD

**Issue by fieryspoon** [moses-palmer/pynput#131]
I'm running on linux.  I'm trying to record locations on the screen the user clicks, without sending the clicks through to the underlying process.

Unfortunately, when I use 
`mouse.Listener(on_move=on_move, on_click=on_click, suppress=True)`

The mouse cursor stops updating on the screen, which makes it pretty difficult to use.  It's sort of expected I guess, since the documentation for the `suppress` argument does say that it will suppress all signals.

If I have the on_move function print out the cursor location, I can see that it is getting the updated movement in the listener though, which I suppose is also expected.

So, how can I just suppress clicks on linux/xorg?  I tried looking into the intercept/event_filter mechanism, but it looks like those are only available on osx or windows.

Thanks,
Ben

**Comment by moses-palmer** [comment]
On what system are you running this? When I test the snippet below, I get reports of clicks and movement for five second of not being able to click, but the cursor does update as expected.

```python
import time

from pynput import mouse


def on_move(*args):
    print('move', args)


def on_click(*args):
    print('click', args)


with mouse.Listener(on_move=on_move, on_click=on_click, suppress=True):
    time.sleep(5)
```

**Comment by fieryspoon** [comment]
Hm, you're right.  It works well with this simple example.  It must be something else getting in the way.  Sorry about that.  Thanks again.
