### ISSUE TITLE
Python 2.7.15 cannot import pynput

### ISSUE THREAD

**Issue by RedmatchQa1** [moses-palmer/pynput#132]
Hi , 

I am trying to import pynput to my code unsuccessfully

I use python 2.7.15 (the latest version for 2.7 as i know) and pynput 1.4

![image](https://user-images.githubusercontent.com/38884835/51251728-9e22fc00-19a2-11e9-8f61-bdc15aa538ce.png)

![image](https://user-images.githubusercontent.com/38884835/51251763-b3982600-19a2-11e9-80ea-cc5edc4612f2.png)

Can someone assist please?

**Comment by ishqinfinite** [comment]
first,make sure you figure out your path directory accurately then try changing the directory with the correct path.
hope that will do

**Comment by RedmatchQa1** [comment]
Do you mean python version variables?
![image](https://user-images.githubusercontent.com/38884835/51305400-6324d500-1a43-11e9-9eae-ed816ecebceb.png)


@ishqinfinite  , thanks for your help

**Comment by moses-palmer** [comment]
I will close this, as it appears to be an issue with you IDE. If you disagree, please reopen.
