### ISSUE TITLE
Where to handle StopException?

### ISSUE THREAD

**Issue by DerDonut** [moses-palmer/pynput#135]
I've worked a bit with pynput now and the main functionality works as expected - thank you very much for this module. I wrote a script that connects to a socket to send inputs to a server.
However, if the connection is terminated, the script tries to reconnect. For that purpose i want to re-init all listeners etc.
For that I want to end all threads and listener properly. For pynput I'm running into a problem. Whenever I stop a listener (no matter if returning False in a callback or calling .stop()), a StopException is thrown. Is this exception thrown because of calling the stop itself or does that mean that one of the callbacks threw an exception at any point it was working?
I wrote an example to show that the exception seems to be thrown in any case. How can i handle it?
```
import time
from pynput import keyboard


def on_press(self, key):
    return


def on_release(self, key):
    return

keyboard_listener = keyboard.Listener(on_press, on_release)
keyboard_listener.start()

time.sleep(3)

keyboard_listener.stop()  # will always cause a StopException
```
> The Exception message:
> Unhandled exception in listener callback
> Traceback (most recent call last):
>   File "[...]/lib/python3.6/site-packages/pynput/_util/__init__.py", line 157, in inner
>     return f(self, *args, **kwargs)
>   File "[...]/lib/python3.6/site-packages/pynput/_util/xorg.py", line 451, in _handler
>     raise self.StopException()
> pynput._util.AbstractListener.StopException

**Comment by moses-palmer** [comment]
Thank you for your report.

This bug appeared a couple of versions back when the logging of listener events was introduced. It does not affect actual behaviour, which can be verified by adding a `print` call after invoking `stop` and observing that it is actually executed; it is simply a log message.

Nonetheless, it is unnecessary clutter, and I have explicitly removed it in a [commit on `master`](https://github.com/moses-palmer/pynput/commit/a269c0eda31745d4e8f3d14e53679ce5fbfc7210).
