### ISSUE TITLE
ctrl+x doesn't "cut" (copy) but only print ^X in the console

### ISSUE THREAD

**Issue by Jdodo45** [moses-palmer/pynput#14]
following pynput documentation I tried this to "cut":

1: I did select some text in an editor

2: run this_code.py using a shortcut (without leaving the active windows)

```
from pynput.keyboard import Key, Controller
keyboard = Controller()
with keyboard.pressed(Key.ctrl):
    keyboard.press('x')
    keyboard.release('x')
```

The python console open actually print: ^X. The combination of keys are right bu**t it doesn't do what it's suppose to do: cut the selected text store it in the clipboard**. (I'm not interested to just store the clipboard content in a variable, I just need the code to acte like Ctrl+C does)

I guess this answer will also solve the remaining part: Ctrl+V (to past some data which will be first inserted in the clipboard)

**Comment by moses-palmer** [comment]
What terminal do you use, and what operating system? Does selecting text and pressing _ctrl+x_ actually cut it?

Generally you will need to press _shift_ as well, or _cmd_ on _OSX_ to copy or paste in a terminal; I have never come across a terminal where you can actually cut text though.

**Comment by moses-palmer** [comment]
I have verified that the following snippet works on all supported platforms (_Xorg_, _Windows_ and _OSX_), so I will close this issue. I have tested with applications that support cutting and pasting text (_Atom_, _Notepad_ and _Sublime_).

    import sys
    import time

    from pynput.keyboard import Controller, Key


    controller = Controller()


    # OSX uses cmd as modifier
    modifier = Key.cmd if sys.platform == 'darwin' else Key.ctrl


    print('Select text to cut')
    time.sleep(2)
    with controller.pressed(modifier):
        controller.type('x')


    print('Select target')
    time.sleep(2)
    with controller.pressed(modifier):
        controller.type('v')

**Comment by WiliTest** [comment]
thanks for your reply moses
