### ISSUE TITLE
Input problems and workaround

### ISSUE THREAD

**Issue by ManuelLevi** [moses-palmer/pynput#140]
ltdr: If you're having input problems, try changing your keyboard layout.

I was noticing that when I wanted to input ":" I was getting an "a" instead. 
Eventually, I found out that if I use a different keyboard layout (English), the code works fine.

I've seen problems that seem related to this, but not exactly the same. 

Hope this helps users and pynput developers to support worldwide input.

EDIT: I just noticed this doesn't work for all the symbols, but it does work for some. Maybe I need to try yet a different layout?..

**Comment by SpecialCharacter** [comment]
Hm, I think you encounter a version of what we are discussing at #139.
Characters will work eventually, but not punctuation.
Should we ask the developer whether he can fix it by a built-in function?

**Comment by SpecialCharacter** [comment]
Have you downloaded the latest version? Do you get an : now?

**Comment by moses-palmer** [comment]
@ManuelLevi, what platform and keyboard layout do you use? Do you have a minimal code example that exhibits the issue?

**Comment by ManuelLevi** [comment]
OSx 10.14.2 
pynput==1.4.2
Python 3.7.0

```
from pynput.keyboard import Key, Controller

keyboard = Controller()
keyboard.type(':')
```

Outputs an `a`.

**Comment by gera2ld** [comment]
Hi, @moses-palmer I've created a PR for this, could you check on it please? The problem fails a lot of keys on Mac OS X.
