### ISSUE TITLE
pynput returns too many characters on MacOS

### ISSUE THREAD

**Issue by bwanaaa** [moses-palmer/pynput#141]
On MacOS Mojave and python 2.7.15, this code:

```
from pynput import keyboard

def on_press(key):
    print('Key {} pressed.'.format(key))

def on_release(key):
    print('Key {} released.'.format(key))
    if str(key) == 'Key.esc':
        print('Exiting...')
        return False

with keyboard.Listener(
    on_press = on_press,
    on_release = on_release) as listener:
    listener.join()
```
produces this output when the keys, 'h j s escape' are pressed in sequence

```
hKey 'h' pressed.
Key 'h' released.
Key 'j' pressed.
jKey 'j' released.
Key 's' pressed.
sKey 's' released.
Key Key.esc pressed.
^[Key Key.esc released.
Exiting...
%hjs
```
I do not understand why

1) the letter 'h' precedes the output of the on_press function

2) the letters 'j', 's' , ' ^[Key ' precede the output of the on_release function

3) the letters 'hjs' appear after the terminal prompt after the program execution has terminated

I have a feeling that the keyboard input is intercepted by pynput but then pynput then echoes it out again to the terminal during program execution. Can this be suppressed? But then the letters AGAIN appear after the program has concluded. Where do these come from and how do I suppress that behavior?

I am trying to add non blocking keyboard input for exiting a program which has a loop that runs continually

**Comment by moses-palmer** [comment]
*pynput* intercepts keypresses, but they are still received by the application in the foreground---in this case your terminal. Try to move focus out of your terminal to verify.

**Comment by bwanaaa** [comment]
thank you
