### ISSUE TITLE
Pynput adds an extra letter at the end when using keyboard.press() and can't print Upper-Case and special characters

### ISSUE THREAD

**Issue by Gwerb** [moses-palmer/pynput#152]
So I have this function:
``` 
from pynput.keyboard import Key, Controller, KeyCode
keyboard = Controller()

def write(c):
  keys = list(c)
  for k in keys:
    keyboard.press(k)
    keyboard.release(k)
```
For example I want to type "terminal" with that function. It types terminal and adds an extra letter at the end for me its "a" so it types "terminala". Also when I try to write "Hello World!", it types aello aorldaa, every upper case letter and every special character becomes "a", it also types an extra "a" again. I am using a new MacOS Sierra, Version: 10.12.6. I have no idea why this is happening.

**Comment by moses-palmer** [comment]
Is this still an issue? This was presumably fixed in _pynput 1.4.4_. If it is, please reopen.
