### ISSUE TITLE
Get the incorrect position when monitoring the mouse on win10 (scale  125%+)

### ISSUE THREAD

**Issue by taojy123** [moses-palmer/pynput#153]
My code:
```
def on_click(x, y, button, pressed):
    print('{0} at {1}'.format(
        'Pressed' if pressed else 'Released',
        (x, y)))
listener = mouse.Listener(on_click=on_click)
listener.start()
```
When I run it on macos or win7, it correct!
But run it on win10 and set the screen scale to 125% or 150%, 200%.... , the (x, y) is incorrect.
For example:
I set scale to 150%, and I click (100, 100) point on  the screen, but it says I click (150, 150)

Is there any solution? Thank you!

**Comment by thisisbenmanley** [comment]
I'm having a similar issue with scaling.

For example, I'm in Windows 125% scale mode (the recommended mode). I manually click at (100,100). The pynput.Listener correctly reads (100,100). When I use those coordinates in the pynput.Controller and set mouse.position to (100,100), the mouse on the screen moves to (125,125), but the Listener still sees (100,100). Only after I click manually again at (125,125) does the Listener pick up (125,125).

**Comment by david-szarka** [comment]
you can try  this at start  of code:   
import ctypes
awareness = ctypes.c_int()
ctypes.windll.shcore.SetProcessDpiAwareness(2)

Today I add it to my papagaj.py"https://github.com/david-szarka/papagaj"
 it looks nice, but I will test it on another PCs

check description here:
https://stackoverflow.com/questions/44398075/can-dpi-scaling-be-enabled-disabled-programmatically-on-a-per-session-basis/44422362#44422362

**Comment by taojy123** [comment]
@david-szarka  Thankyou verymush

**Comment by moses-palmer** [comment]
@david-szarka, Thank you very much! I will update the _pynput_ documentation, and add a thank-you to the release notes.
