### ISSUE TITLE
Key.shift returns as a number in on_release()

### ISSUE THREAD

**Issue by omarcartera** [moses-palmer/pynput#154]
When I press any button, both functions print the button name.

BUT

Starting from earlier this week, the function `on_relase()` prints <65032> instead of Key.shift, but behaves normally with all the other buttons. The print function in `on_press()` still works properly.

```
def listener_fn():
    with keyboard.Listener(on_press, on_release) as listener:
    listener.join()

def on_press(key):
    # this prints (Key.shift)
    print('ADD: ', key)


def on_release(key):
    # this prints <65032>
    print('REM: ', str(key))
```

Ubuntu 19.04

**Comment by moses-palmer** [comment]
Thank you for your report.

Starting from this week? Did you upgrade *pynput* or *Ubuntu*? What versions did you use before?

**Comment by omarcartera** [comment]
Thanks for your reply, it was an issue of three months ago and I handled it in my code and didn't bother me since then. But now I  tried again and the problem was solved, maybe I updated the package or something.

Ubuntu 19.04 .. pynput 1.4.2 .. python 3
