### ISSUE TITLE
Get an {'vk': 0, 'char': None} KeyCode when press multiple keys in the same time

### ISSUE THREAD

**Issue by Warren-Wong** [moses-palmer/pynput#156]
When put a "sleep(3)" in the on_press() keyboard callback, then press two keys, such as 'shift' and 'c' in the same time, wait, then press any other key, an abnormal KeyCode will be received.
The KeyCode is like: `{'vk': 0, 'char': None, 'is_dead': False, 'combining': None}`

Having some bug, then I finally located that problem. My program didn't use `sleep()`, but has a lot of works to do in the `on_press()` callback.

### Test code:
```
from pynput.keyboard import Key, KeyCode, Controller, Listener
from time import sleep

def on_press(key):
    print('press',key.__dict__)
    sleep(3)

def on_release(key):
    print('release',key.__dict__)

with Listener(on_press=on_press,on_release=on_release) as listener:
    listener.join()
```

Then I type 'V', so that press `shift` then `v` then release `v` then release `shift`. After all output finished, press any other key, for example `x`, then:
```
press {'_value_': <56>, '_name_': 'shift', '__objclass__': <enum 'Key'>}
press {'vk': 9, 'char': 'V', 'is_dead': False, 'combining': None}
release {'vk': 9, 'char': 'V', 'is_dead': False, 'combining': None}
release {'_value_': <56>, '_name_': 'shift', '__objclass__': <enum 'Key'>}
release {'vk': 0, 'char': None, 'is_dead': False, 'combining': None}
release {'vk': 7, 'char': 'x', 'is_dead': False, 'combining': None}
```
GIF:
[https://drive.google.com/file/d/1o6OkAfH3Jym5pvKmjvzxmOUba7nLLGKV/view?usp=sharing](url)

### Other Information:
Python version:
```
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
```
pynput install information:
```
Collecting pynput
  Using cached https://files.pythonhosted.org/packages/94/92/9e83e382f808b57330bed06855489242b77c262406aeca4960a16c8666d9/pynput-1.4.2-py2.py3-none-any.whl
Requirement already satisfied: pyobjc-framework-Quartz>=3.0; sys_platform == "darwin" in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pynput) (5.2)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pynput) (1.12.0)
Requirement already satisfied: pyobjc-core>=5.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc-framework-Quartz>=3.0; sys_platform == "darwin"->pynput) (5.2)
Requirement already satisfied: pyobjc-framework-Cocoa>=5.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pyobjc-framework-Quartz>=3.0; sys_platform == "darwin"->pynput) (5.2)
Installing collected packages: pynput
Successfully installed pynput-1.4.2
```
System:
```
macOS Mojave Version 10.14.4
MacBook Pro (Retina, 13-inch, Early 2015)
```

**Comment by moses-palmer** [comment]
Please consult the documentation about blocking operations in the event callback [here](https://pynput.readthedocs.io/en/latest/keyboard.html#the-keyboard-listener-thread).

The _tldr;_ is that no _slowish_ operations should be performed in the event callback, as it will impose severe lag on the system input handling.

If you need to perform long running operations in response to an event, the [`queue`](https://docs.python.org/3/library/queue.html) module and a dedicated thread reading from it works well.
