### ISSUE TITLE
Suppress controller output to listener?

### ISSUE THREAD

**Issue by DeeJayhX** [moses-palmer/pynput#159]
I am using pynput to send rapid keystrokes for a particular purpose. I am also using a non-blocking listener to wait for a hotkey to end this function. The problem is that the listener is responding to the controller's output. It causes the system to hang as the CPU threads are quickly filled up by responding to each one of these keystrokes in a long series of strings being output.

Is there a way to suppress the controller's output to the listener, or is this not possible because the listener is grabbing information from a Window's messagepump and output from the controller is going through that?

**Comment by moses-palmer** [comment]
The branch [feature-injected](https://github.com/moses-palmer/pynput/tree/feature-injected) might be what you are looking for; it adds, for platforms where this is possible, a flat to input events signalling that they are _injected_. You could use this as a flag to ignore it.

**Comment by DeeJayhX** [comment]
That's exactly what I'm looking for. Thanks!

**Comment by DeeJayhX** [comment]
@moses-palmer side note, I ran the setup.py from a clone of your feature-injected branch, do I simply import pynput as normal or is there something special I need to do. Also, is there any documentation of how to use that feature, or do I need to read the code and fly by the seat of my pants?
