### ISSUE TITLE
A way to stop event propagation?

### ISSUE THREAD

**Issue by russelg** [moses-palmer/pynput#16]
I've been writing a sort-of window manager, and I use a certain shortcut to move windows (Ctrl+Alt+mouse middle click).

I've got handling written for this working fine. However, I'd like to not propagate the middle click there, since that will interact with the window.
Is there any way to not pass events on?

In pyHook it can be done by just returning `False` in a mouse handler.

**Comment by moses-palmer** [comment]
After looking through the _PyHook_ source code, I see that this is achieved by simply not calling the next system hook.

For the next release of _pynput_, I will add support for platform specific configuration flags; this is an excellent candidate for such a flag. Until then, you can use the following snippet:

    import pynput._util.win32

    pynput._util.win32.SystemHook._CallNextHookEx = staticmethod(
        lambda hook, code, msg, lpdata: 1)

This code will unconditionally prevent further propagation of all events, so you will have to tweak it based on the parameters.

**Comment by moses-palmer** [comment]
I have added this feature to *master*.

To test it, run the following snippet:

    from pynput import mouse


    def mouse_listener():
        def on_move(x, y):
            print('=> [%d, %d]' % (x, y))

        def on_click(x, y, button, pressed):
            print('%s %s [%d, %d]' % ('>' if pressed else '<', button, x, y))

        def on_scroll(x, y, dx, dy):
            print('[%d, %d], [%d, %d]' % (x, y, dx, dy))

        return mouse.Listener(
                on_move=on_move,
                on_click=on_click,
                on_scroll=on_scroll,
                win32_event_filter=lambda msg, data:
                    msg not in (
                        mouse.Listener.WM_MBUTTONDOWN,
                        mouse.Listener.WM_MBUTTONUP))


    with mouse_listener() as ml:
        ml.join()

This will print mouse events to the console, and prevent middle click from being propagated.

**Comment by russelg** [comment]
Awesome work, thanks a lot!
