### ISSUE TITLE
can't type some key combinations such as some with 'shift' f.e. to obtain 'ë'

### ISSUE THREAD

**Issue by yasinkurt61** [moses-palmer/pynput#161]
When the keyboard listener is active, I can't type certain special characters anymore system wide.
For example I'm unable to type the character 'ë'.

My program is just for listening to key presses and log how many keys are pressed.

**Comment by moses-palmer** [comment]
Thank you for your report.

I am fairly certain this is related to issue #49. I will close this issue and refer to the already existing one.

**Comment by yasinkurt61** [comment]
Hi,

I have 2 main problems besides the one I mentioned before with the char
input systemwide.

The mouse listener stops sometimes en doesn't start again till the app is
restarted. Is there a way I can make the listener to listen forever and
ignore exceptions and possible errors? I only count the amount of
mouseclicks and scrolls.

Secondly I can't capture keyboard events when in a remote desktop session
(RDC). The program can't receive the key inputs. The mouse however works
well in RDC.

I hope you can help me with these problems.

Thanks in advance

Op vr 24 mei 2019 20:58 schreef moses-palmer <notifications@github.com>:
