### ISSUE TITLE
The `suppress `parameter  should block all input events from being passed to the rest of the system.

### ISSUE THREAD

**Issue by redstoneleo** [moses-palmer/pynput#163]
My program want to listen to key combination Alt+Z and  block the key combination event passed to the rest of the system, so I set suppress=True , but pynput also blocked Ctrl +C.
My suggestion is the `suppress `parameter of `pynput.keyboard.Listener(on_press=None, on_release=None, suppress=False, **kwargs)`  once set to true  should not block all input events from being passed to the rest of the system, but should only block the specified  key combination events.

**Comment by moses-palmer** [comment]
That seems very reasonable, but it is unfortunately not possible to implement in a platform agnostic way---at least *X.Org* only allows complete suppression.

You can however implement this using the platform specific options mentioned [here](https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Listener), at least for *Windows*.
