### ISSUE TITLE
Enabling Windows magnification

### ISSUE THREAD

**Issue by newenglandfall** [moses-palmer/pynput#165]
I am trying to enable Windows magnification which happens with the key combination of "windows" + "+".
I have the following code:
```
keyboard.press(Key.cmd)
keyboard.press('+')
keyboard.release('+')
keyboard.release(Key.cmd)
```
For some reason it simply isn't working for me. I had some others try it in Discord and they couldn't get it as well. Pressing the keys manually works.

Any suggestions as to what I may be doing wrong?

**Comment by moses-palmer** [comment]
I think this may be related to #113. There appears to be issues with modifier keys on *Windows 10*. Is that the operating system you are running?

**Comment by newenglandfall** [comment]
Yes, Windows 10. So it appears there is no solution.
