### ISSUE TITLE
Mouse listener to button click doesn't work when active process is running.

### ISSUE THREAD

**Issue by DanielHammerin** [moses-palmer/pynput#166]
I'm using pynput to automate some things. 

I have a function:

    def on_click(x, y, button, pressed):
        # If right-click, stop execution
        if button == Button.right and pressed:
            raise KeyboardInterrupt
        # If left-click start execution
        if button == Button.left and pressed:
            run(x, y)

If I left click it starts the script and if I right click it stops.
However, if I start and it goes into my run() where I run a while True, the listener doesn't pick up the right-click.
It does the same if i invert the buttons.
Isn't the listener always listening or am I missing something here?

**Comment by moses-palmer** [comment]
The listener callbacks are invoked in an undefined thread, but as the [documentation states](https://pynput.readthedocs.io/en/latest/mouse.html#the-mouse-listener-thread), you must not call any blocking functions from it---the behaviour is platform defined in this case.

If you need to perform a long running operation from a callback, you must do that in a separate thread. How you would do that depends on your use case.
