### ISSUE TITLE
Some combinations with Shift key do not work on Windows 7.

### ISSUE THREAD

**Issue by tuessetr** [moses-palmer/pynput#169]
For example Shift + Arrows do not work. I think that the \keyboard\_win32.py KeyCode class needs to be modified: variable "extendedkey" that stores 1 if key virtualcode or scancode in set of keys that has the prefix code E0 (at least) or 0 if it does not. and dwFlags line might look like this "dwFlags=flags | (KEYBDINPUT.KEYUP if not is_press else 0) **| extendedkey**". This works for Shift + Arrows, has not tested other combinations.

**Comment by moses-palmer** [comment]
Thank you for your report, and sorry for the long silence---I missed this issue among all the others!

I have incorporated your suggestion into the _master_ branch, and my testing suggests that it now works. I am waiting for confirmation of fixes for other outstanding issues, but once they have all been merged, I will make a new release.
