### ISSUE TITLE
launching shell window using raspberry pi hotkey breaks GPIO script

### ISSUE THREAD

**Issue by MidnightTanny** [moses-palmer/pynput#172]
I am using pynput in a short script to launch a terminal window on a raspberry pi using the GPIO pins to initiate the keyboard controller. (These Pi units will not have a mouse or keyboard on them, only a simple 2-button interface to start and stop the program)

What I am running into is that when I use pynput to press ctrl+alt+t to open the terminal window, the script suddenly stops all GPIO input. Am I doing something wrong? Script below:

`import RPi.GPIO as GPIO
from pynput.keyboard import Key, Controller

keyboard = Controller()

def startcall(channel): # this breaks the script
    with keyboard.pressed(Key.ctrl):
        with keyboard.pressed(Key.alt):
        keyboard.press('t')
        keyboard.release('t')
    time.sleep(2)
    keyboard.type('chromium-browser')
    keyboard.press(Key.enter)
    keyboard.release(Key.enter)
    
def endvideo(channel): # I can press this all I want and it keeps running.
    keyboard.press(Key.alt)
    keyboard.press(Key.f4)
    keyboard.release(Key.f4)
    keyboard.release(Key.alt)

GPIO.setmode(GPIO.BOARD)
GPIO.setup(10, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.add_event_detect(10,GPIO.RISING,callback=startcall)
GPIO.setup(8, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
GPIO.add_event_detect(8,GPIO.RISING,callback=endvideo)`

**Comment by moses-palmer** [comment]
I'm afraid that I have no idea what could cause your issues.

Do you get any error messages? What happens if you sprinkle `startcall` with calls to `print`? What happens if you add a call to `time.sleep` to `endvideo`?

**Comment by moses-palmer** [comment]
Due to lack of feedback, I will close this issue.
