### ISSUE TITLE
Deprecation of Enum containment check in Python 3.8

### ISSUE THREAD

**Issue by asweigart** [moses-palmer/pynput#173]
I encountered this error when calling press():

    TypeError: unsupported operand type(s) for 'in': 'str' and 'EnumMeta'

This happens in Python 3.8 because you can't do `someEnum in EnumClass` code anymore. (There was a deprecation warning in 3.7).

I'll post a PR with a backwards-compatible fix shortly.

**Comment by moses-palmer** [comment]
This has been merged into _master_.
