### ISSUE TITLE
Reading HID Reserved keycode

### ISSUE THREAD

**Issue by harshitgoel96** [moses-palmer/pynput#175]
Hi,

From key HID Keyboard, if I send the HID Reserved HEX keycodes like 0xDE, how can I read it ?
I see there is a KeyCode object, but I don't find a method to match/read the hex keycode

**Comment by moses-palmer** [comment]
Hi,

Have you tried reading the [`vk`](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L44) attribute of the argument passed to the listener callback?

**Comment by harshitgoel96** [comment]
Looks like OS is not forwarding the key to applications.
