### ISSUE TITLE
Issue with pynput

### ISSUE THREAD

**Issue by BeardedSilence** [moses-palmer/pynput#178]
Exception has occurred: ModuleNotFoundError
No module named 'pynput'
  File "C:\Users\Jorda\Desktop\Keylogger.py", line 1, in <module>
    from pynput.keyboard import Key, Listener

I keep receiving this message while running debug. I have pip installed pynput and im still having trouble. Any advice would be greatly appreciated

**Comment by moses-palmer** [comment]
This error is completely unrelated to *pynput*, and I will thus close it. You might find more information in a tutorial for Python on Windows.
