### ISSUE TITLE
Arguments keyboard listener on_click

### ISSUE THREAD

**Issue by ebonmati** [moses-palmer/pynput#179]
I would like to do something like this:

Function definition:

def on_press(key, **config**):

In the main function:

listener = keyboard.Listener(on_press=on_press(**config**))
listener.start()

However, I am not sure what is the best way to handle arguments, or if its possible as the on_press function is in a different thread?

**Comment by moses-palmer** [comment]
Hello,

The callbacks can be any type of callables. One way to supply a context, or a configuration, is thus:
```python
from pynput import keyboard


class Context:
    def __init__(self):
        self.value = 42

    def on_press(self, key):
        print('>', key, self.value)

    def on_release(self, key):
        print('<', key, self.value)
        if key == keyboard.Key.esc:
            raise keyboard.Listener.StopException()


context = Context()
with keyboard.Listener(
        on_press=context.on_press,
        on_release=context.on_release) as l:
    l.join()
```
