### ISSUE TITLE
Is it possible to get system mouse cursor type?

### ISSUE THREAD

**Issue by jollysean** [moses-palmer/pynput#18]
Hi,
I have a need to track the mouse cursor type. I have been looking at pyglet [here](https://pythonhosted.org/pyglet/api/pyglet.window.Window-class.html#get_system_mouse_cursor)

Is it possible that pynput can give this information as well?

**Comment by moses-palmer** [comment]
This appears to be somewhat possible on _win32_, _X_ and _OSX_.

 *  On _win32_, [GetCursorInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648389(v=vs.85).aspx) combined with `LoadCursor` could possibly be used.
 *  On _OSX_, the `currentSystemCursor` attribute could be used.
 *  On _X_, _XFIXES_ could possibly be used if the rest of the system can be relied upon to set a cursor name.

All in all, this would be quite a lot of work. What is your use case?

**Comment by jollysean** [comment]
A common interface for getting that info could have been useful. I am primarily concerned with drag actions which may be used to move objects or change window sizes. It would be convenient if the mouse cursor info is available to differentiate those 2 actions.

**Comment by moses-palmer** [comment]
I have done some preliminary testing on _Windows_, and the result is positive. The interface I am testing out adds the property `pynput.mouse.Listener.cursor`, which is of an `enum` type similar to `pynput.mouse.Button`.

**Comment by moses-palmer** [comment]
I will close this. The implementation turned out to be too unreliable, and impossible to get to work cross-platform.
