### ISSUE TITLE
Q: Is it posible to write text independent of keyboard layout\language?

### ISSUE THREAD

**Issue by banderlog** [moses-palmer/pynput#187]
Hi, I am using `pynput` to input text into web forms on WINDOWS host. But it appeared that `keyboard.type()` will use selected system keyboard language.

E.g.:  `keyboard.type('qwerty')` will type `йцукен` if keyboard language is set to "Russian"

Is there any way to avoid this?

**Comment by moses-palmer** [comment]
Thank you for your report.

*pynput* is supposed to be keyboard layout agnostic, so this is a bug. I suspect commit [63aab1a](https://github.com/moses-palmer/pynput/commit/63aab1acf3b66b37f4ebac72be958a505e382a06) may have caused this, since that commit causes the application to only use the keyboard layout active for the window and thread that launches *pynput*, and that if often the `cmd` process, which appears to have a very strange layout handling.

Is is possible for you to test with that commit reverted? I just tested, and `git revert 63aab1a` works without conflicts.

**Comment by banderlog** [comment]
>Is is possible for you to test with that commit reverted?

Yes, no differences though:

```bash
# create new venv
conda create --name test_pyinp
conda activate test_pyinp
conda install git

# prepare git
git clone https://github.com/moses-palmer/pynput
cd pynput
git revert 63aab1a 
cd lib
python3
```

```python
from pynput.keyboard import Key, Controller

keyboard = Controller()
keyboard.type('qwerty')
>>>qwerty

# Alt+Shift to change layout to Russian
keyboard.type('qwerty')
>>>йцукен

keyboard2 = Controller()
keyboard2.type('qwerty')
>>>йцукен

```

**Comment by moses-palmer** [comment]
Could you please test again with the following script?

```python
import pynput, time

print('Please switch focus to a different application, such as notepad.exe')
time.sleep(5)
pynput.keyboard.Controller().type('qwerty')

print('Please change keyboard layout')
time.sleep(5)
pynput.keyboard.Controller().type('qwerty')
```

The reason for this is that historically, `cmd.exe` has interfered with the keyboard layout.

**Comment by banderlog** [comment]
I pulled fresh `pynput`, copied above code to `test_pyinput.py`  and run it with command `python3 test_pyinput.py`.
 It behaves like this:
+ If I run the script with Eng layout set and switch to Ru after 10 sec -- all is OK (`qwertyйцукен`)
+ If I run the script with Eng layout set and switch to Ru immediately -- all is OK (`йцукенqwerty`)
+ If I run the script in any other than Eng layout on -- it will type in Eng and it will not switch to any other layout (`qwertyqwerty`).

**Comment by SpecialCharacter** [comment]
In the worst case, you can use escape Unicode sequences, or? E.g. 'qwerty' = '\u0071''\u0077''\u0065''\u0072''\u0074''\u0079'.
Though admittedly ugly to see...

**Comment by moses-palmer** [comment]
Please note that, if you closed this issue due to the response above, that is no solution. Using Unicode escape sequences does not make a difference, as using them only obfuscated the source, and does not affect the state of the running system at all.

**Comment by banderlog** [comment]
@moses-palmer I am not sure what to do. The problem is not actual for me anymore. And above message just reminded me of its existence.
