### ISSUE TITLE
How to define a class for listeners?

### ISSUE THREAD

**Issue by joaomamede** [moses-palmer/pynput#192]
Hi, Thanks for pynput, it's great!

I am trying to create an object that I can call to basically get the position of the mouse when clicked.

```
class get_position(mouse.Listener):
    def __init__(self):
        mouse.Listener.__init__(self)

    def on_move(x, y):
        pass

    def on_click(x, y, button, pressed):
        print('{0} at {1}'.format(
            'Pressed' if pressed else 'Released',
            (x, y)))
        
        if not pressed:
            # Stop listener
            return False
            self.value = (x,y)

    def on_scroll(x, y, dx, dy):
       pass

```

if I start say:

a = get_position()

it does get created, 
but when I go something like

a.join() 
it says it was not initialized?

calling it like this would save me a lot of programming time. 
Can anyone point me to how to do this?

Thanks.

**Comment by joaomamede** [comment]
`def on_move(x, y):
    print('Pointer moved to {0}'.format(
        (x, y)))

def on_click(x, y, button, pressed):
    print('{0} at {1}'.format(
        'Pressed' if pressed else 'Released',
        (x, y)))
    if not pressed:
        # Stop listener
        return False

def on_scroll(x, y, dx, dy):
    print('Scrolled {0} at {1}'.format(
        'down' if dy < 0 else 'up',
        (x, y)))


class get_position(mouse.Listener):
    def __init__(self):
        mouse.Listener.__init__(self,on_move=on_move, on_click=on_click,on_scroll=on_scroll)
`
And then

`a = get_position()
a.start()
a.join()`

worked. I would still like to have the on_click, on_move, and on_scroll functionts within the class. 
Any tips for me?

**Comment by moses-palmer** [comment]
I think what you are looking for is [`pynput.mouse.Controller.position`](https://pynput.readthedocs.io/en/latest/mouse.html#pynput.mouse.Controller.position).

```python
from pynput import mouse

c = mouse.Controller()
print('{0}', c.position)
```

**Comment by joaomamede** [comment]
I want to get the position when clicked with left mouse button, can I still do it without the listener? 

I simplified what I want in the example. But I really wanted to make my own class. 

Thanks for the reply.

**Comment by moses-palmer** [comment]
If you want to make you own class, I suggest you use composition instead of inheritance---that is, let the listener be a field of you own class instead of its super class.

You may want to look into the arguments you pass to the `Listener` constructor---`(self,on_move=on_move, on_click=on_click,on_scroll=on_scroll)` does not seem right; don't you mean to pass `self.on_move` and so on?

**Comment by joaomamede** [comment]
That's what I'm trying right now.

I realized that I had def on_move still defined as a global def and that's why it was running.

If I get this to work I'll share the code here.

Thanks.

**Comment by joaomamede** [comment]
That was exactly it.

```
from pynput import mouse
import pyperclip
import numpy as np
from pynput.mouse import Button, Controller

class get_position(mouse.Listener):
    def __init__(self):
        mouse.Listener.__init__(self,on_move=self.on_move, on_click=self.on_click)
        self.start()

    def on_move(self,x, y):
        print('Pointer moved to {0}'.format(
            (x, y)))
        self.value = (x,y)

    def on_click(self,x, y, button, pressed):
        print('{0} at {1}'.format(
            'Pressed' if pressed else 'Released',
            (x, y)))
        self.value = (x,y)
        if not pressed:
            # Stop listener
            return False

```

It worked.

In [6]: a.join()
Pointer moved to (1451, 501)
Pointer moved to (1445, 495)
[...]
Pointer moved to (1693, 591)
Pointer moved to (1695, 591)
Pressed at (1695, 591)
Released at (1695, 591)

In [7]: a.value
Out[7]: (1695, 591)
