### ISSUE TITLE
No cyrillic keyboard input and typing for Linux

### ISSUE THREAD

**Issue by Maboroshy** [moses-palmer/pynput#193]
I use Manjaro Linux with Plasma DE and X.org Server 1.20.5. There are US English and Russian keyboard layouts on my system.

pynput work ok with US English but with Russian:
- input is recognized as a corresponding US English layout keys: `q` instead of `й` which is on the same key;
- `pynput.keyboard.Controller().type('абв')` does nothing

<details>
  <summary>xev output for `абв` looks ok...</summary>
KeyPress event, serial 40, synthetic NO, window 0x6600001,
    root 0x6ce, subw 0x0, time 1433257, (-446,410), root:(472,447),
    state 0x2000, keycode 41 (keysym 0x6c1, Cyrillic_a), same_screen YES,
    XLookupString gives 2 bytes: (d0 b0) "а"
    XmbLookupString gives 2 bytes: (d0 b0) "а"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x6600001,
    root 0x6ce, subw 0x0, time 1433335, (-446,410), root:(472,447),
    state 0x2000, keycode 41 (keysym 0x6c1, Cyrillic_a), same_screen YES,
    XLookupString gives 2 bytes: (d0 b0) "а"
    XFilterEvent returns: False

KeyPress event, serial 40, synthetic NO, window 0x6600001,
    root 0x6ce, subw 0x0, time 1433713, (-446,410), root:(472,447),
    state 0x2000, keycode 59 (keysym 0x6c2, Cyrillic_be), same_screen YES,
    XLookupString gives 2 bytes: (d0 b1) "б"
    XmbLookupString gives 2 bytes: (d0 b1) "б"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x6600001,
    root 0x6ce, subw 0x0, time 1433793, (-446,410), root:(472,447),
    state 0x2000, keycode 59 (keysym 0x6c2, Cyrillic_be), same_screen YES,
    XLookupString gives 2 bytes: (d0 b1) "б"
    XFilterEvent returns: False

KeyPress event, serial 40, synthetic NO, window 0x6600001,
    root 0x6ce, subw 0x0, time 1434147, (-446,410), root:(472,447),
    state 0x2000, keycode 40 (keysym 0x6d7, Cyrillic_ve), same_screen YES,
    XLookupString gives 2 bytes: (d0 b2) "в"
    XmbLookupString gives 2 bytes: (d0 b2) "в"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic NO, window 0x6600001,
    root 0x6ce, subw 0x0, time 1434227, (-446,410), root:(472,447),
    state 0x2000, keycode 40 (keysym 0x6d7, Cyrillic_ve), same_screen YES,
    XLookupString gives 2 bytes: (d0 b2) "в"
    XFilterEvent returns: False
</details>

**Comment by moses-palmer** [comment]
That seems like a strange bug; there is even a test for it [here](https://github.com/moses-palmer/pynput/blob/651d81011f1f773675ca38f39b3d56902f9e6b56/tests/keyboard_controller_tests.py#L287). Does running the test suite fail as well?

**Comment by Maboroshy** [comment]
That test fails on my system:

FAIL: test_type_nonascii (tests.keyboard_controller_tests.KeyboardControllerTest)
Asserts that type works for a non-ascii strings


Traceback (most recent call last):
  File "/home/mbr/Код/pynput/git/tests/keyboard_controller_tests.py", line 289, in test_type_nonascii
    u'Компьютерная клавиатура')
  File "/home/mbr/Код/pynput/git/tests/keyboard_controller_tests.py", line 95, in assert_input
    self.assertIn(expected, collect(), failure_message)
AssertionError: 'Компьютерная клавиатура' not found in (' ',) : Failed to type Russian string

Ran 17 tests in 5.124s

FAILED (failures=1)

**Comment by moses-palmer** [comment]
Thank you for your help!

What output do you get from `xev` when you run `python -c "import pynput; pynput.keyboard.Controller().type('абв')`?

**Comment by Maboroshy** [comment]
I'm not sure I know how to get the data.
`xev` creates a dummy X windows and prints events only for this window.
When I manually attach `xev` to a terminal window by `xev -id` I see only some `MappingNotify` events while the command runs, no key events except for return key I press to run a command. I've run it by current user and by root to be sure.

**Comment by moses-palmer** [comment]
Perhaps the following script would suffice?

```python
import pynput, time

time.sleep(5)
pynput.keyboard.Controller().type('абв')
```

Run the script and quickly select the xev window.

**Comment by Maboroshy** [comment]
For `pynput.keyboard.Controller().type('абв')` I get:
<details>
  <summary>output</summary>
KeyPress event, serial 49, synthetic YES, window 0x5600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 8 (keysym 0x0, NoSymbol), same_screen NO,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 58, synthetic YES, window 0x5600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 8 (keysym 0x0, NoSymbol), same_screen NO,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 67, synthetic YES, window 0x5600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 8 (keysym 0x0, NoSymbol), same_screen NO,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 76, synthetic YES, window 0x5600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 8 (keysym 0x0, NoSymbol), same_screen NO,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 85, synthetic YES, window 0x5600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 8 (keysym 0x0, NoSymbol), same_screen NO,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 94, synthetic YES, window 0x5600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 8 (keysym 0x0, NoSymbol), same_screen NO,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
</details>
For `pynput.keyboard.Controller().type('abc')` I get:
<details>
  <summary>output</summary>
KeyPress event, serial 40, synthetic YES, window 0x4600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 38 (keysym 0x61, a), same_screen NO,
    XLookupString gives 1 bytes: (61) "a"
    XmbLookupString gives 1 bytes: (61) "a"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic YES, window 0x4600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 38 (keysym 0x61, a), same_screen NO,
    XLookupString gives 1 bytes: (61) "a"
    XFilterEvent returns: False

KeyPress event, serial 40, synthetic YES, window 0x4600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 56 (keysym 0x62, b), same_screen NO,
    XLookupString gives 1 bytes: (62) "b"
    XmbLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic YES, window 0x4600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 56 (keysym 0x62, b), same_screen NO,
    XLookupString gives 1 bytes: (62) "b"
    XFilterEvent returns: False

KeyPress event, serial 40, synthetic YES, window 0x4600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 54 (keysym 0x63, c), same_screen NO,
    XLookupString gives 1 bytes: (63) "c"
    XmbLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False

KeyRelease event, serial 40, synthetic YES, window 0x4600001,
    root 0x72b, subw 0x0, time 0, (0,0), root:(0,0),
    state 0x0, keycode 54 (keysym 0x63, c), same_screen NO,
    XLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False
</details>

**Comment by mox512** [comment]
This is still not working Ubuntu 23.04 
X.Org X Server 1.21.1.7
Layouts obviously in the system.


`
denis@yoga:~$ python -c "import pynput; pynput.keyboard.Controller().type('Мороженка')"
Traceback (most recent call last):
  File "/home/denis/Documents/CVBuild/venv/lib/python3.11/site-packages/pynput/keyboard/_base.py", line 492, in type
    self.release(key)
  File "/home/denis/Documents/CVBuild/venv/lib/python3.11/site-packages/pynput/keyboard/_base.py", line 427, in release
    self._handle(resolved, False)
  File "/home/denis/Documents/CVBuild/venv/lib/python3.11/site-packages/pynput/keyboard/_xorg.py", line 236, in _handle
    raise self.InvalidKeyException(key)
pynput.keyboard._base.Controller.InvalidKeyException: 'М'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/denis/Documents/CVBuild/venv/lib/python3.11/site-packages/pynput/keyboard/_base.py", line 495, in type
    raise self.InvalidCharacterException(i, character)
pynput.keyboard._base.Controller.InvalidCharacterException: (0, 'М')
`

**Comment by fish-dd** [comment]
Found out it crashes when trying to `type("д")` (Cyrillic d) meanwhile it doesn't crashes on many other Cyrillic symbols. Sounds bad because this is only solution working with Embedded Python.

**Comment by SpecialCharacter** [comment]
Is your encoding set to Unicode or to ISO-whatever?
