### ISSUE TITLE
Is there any way to simulate inputs in a web browser?

### ISSUE THREAD

**Issue by FrostWolf1** [moses-palmer/pynput#194]
I am building a program that will interact with google chrome through pynput, as I am unable to use selenium. Unfortunately, when I try to interact with chrome by pressing enter, the enter input is instead done in the IDLE environment. Is there a way to have the input occur in chrome instead.

I will attach my code here, but with the link blanked out.

import sys
import time
import webbrowser
from pynput.keyboard import Key, Controller

sys.path.insert(0, 'C:\\Program Files (x86)\\Google\\Chrome\\Application')
chromepath = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s'
url = '----------------------------'

keyboard = Controller()

webbrowser.get(chromepath).open(url)

time.sleep(4)

keyboard.press(Key.enter)
keyboard.release(Key.enter)

**Comment by moses-palmer** [comment]
*pynput* does not send the keyboard press events to any particular window; rather it relies on the operating system to send events to the focused window.

Are you certain that the browser is focused?

**Comment by FrostWolf1** [comment]
Focused? Do you mean open? If so, yes.

**Comment by FrostWolf1** [comment]
Looked into the issue a bit further and found the solution (error on web page not with my code). Thank you for trying anyway.
