### ISSUE TITLE
Question about "supress" mode

### ISSUE THREAD

**Issue by segalion** [moses-palmer/pynput#203]
I would like to globally disable all keys and mouse events for a while (i.e. while my rpi is powering TV on waking-up from a sleep-time), and I have seen 'supress' mode on listeners, to do that.

How it works when create two listeners, first with supress, and second without supress?
Second listener receive events?
Could be possible to has 'supress' mode dinamically enabled and disabled on the listener? I.e `keyboard_listener.supress()`, `keyboard_listener.unsupress()`

**Comment by panoschal** [comment]
I think that currently, you have to stop the listener and create a new one, every time you need to change something, like said here: https://pynput.readthedocs.io/en/stable/keyboard.html#toggling-event-listening-for-the-keyboard-listener

**Comment by moses-palmer** [comment]
That is correct.

To expand on what the documentation reads, this is a flag that cannot be modified once set on some platforms, so it is best left to consumers of this library to decide how to restart listening.
