### ISSUE TITLE
cannot import name '_NORMAL_MODIFIERS' from 'pynput'

### ISSUE THREAD

**Issue by Ivoz** [moses-palmer/pynput#208]
I think latest release broke the `keyboard` module.

See https://github.com/moses-palmer/pynput/commit/f58e8f93c7c6510542d0dbd72a351ff911944c6d#r36600476 for details

**Comment by moses-palmer** [comment]
Thank you for your report!

I have uploaded a new release.

**Comment by Ivoz** [comment]
Hi @moses-palmer , you missed changing `..` to `.` , we don't need to traverse up a package 😅

**Comment by Ivoz** [comment]
Does the test suite pick up the error?

**Comment by moses-palmer** [comment]
Ah, sorry about that!

Yes, it does, but it appears that I'm a bit holiday-lazy...

**Comment by Ivoz** [comment]
Maybe you can put checking the test suite into tools/make-release.py :D

**Comment by moses-palmer** [comment]
Yeah, automating this would be great... Unfortunately it needs to run on three very different platforms, none of which I have easy access to.
