### ISSUE TITLE
Use of Controller().type(string) returns ImportError

### ISSUE THREAD

**Issue by rhystedstone** [moses-palmer/pynput#210]
I seem to get an ImportError each type I call Controller().type(string).
The following code:
```from pynput.keyboard import Key, Controller
keyboard = Controller()
keyboard.type('Hello World')
```
Results in the following error:
```Traceback (most recent call last):
  File "<pyshell#24>", line 1, in <module>
    keyboard.type('Hello World')
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\pynput\keyboard\_base.py", line 460, in type
    from .. import _CONTROL_CODES
ImportError: cannot import name '_CONTROL_CODES' from 'pynput' (C:\Program Files (x86)\Python38-32\lib\site-packages\pynput\__init__.py)
```
I have checked that I am using the latest version of PynPut & Python, and the error apparently occurs on Python 3.7 & 3.8

***Edit:*** The problem seems to occur on versions above 1.6.0. I have reinstalled versions 1.6.3, 1.6.2 & 1.6.1, all returning the same error. 1.6.0 seems to be the latest version without the problem. Hope this helps.

**Comment by GeorgeCiesinski** [comment]
I have a second example of this when using the type method in Controller(): 

```
File "C:\Users\georg\Repositories\text-script\venv\lib\site-packages\pynput\keyboard\_base.py", line 460, in type
    from .. import _CONTROL_CODES
ImportError: cannot import name '_CONTROL_CODES' from 'pynput' (C:\Users\georg\Repositories\text-script\venv\lib\site-packages\pynput\__init__.py)
```

I believe that:
`from .. import _CONTROL_CODES`
should be 
`from . import _CONTROL_CODES `
(one period after from)

I resolved this locally by going to _base.py and line 460, then erasing one of the periods. Worked like a charm.

**Comment by moses-palmer** [comment]
Thank you for your report!

Yes, the last releases have unfortunately been lacking in QA, since none of my current systems support any of the *pynput* backends.

I have made a new release addressing this issue; *pynput 1.6.4*.

**Comment by dqv12908** [comment]
this is my code:

from pynput import Controller
mymouse= Controller()
print(mymouse.position)

and it comes out with this error:
Exception has occurred: ImportError
cannot import name 'Controller' from 'pynput' (C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pynput\__init__.py)
  File "C:\Users\Admin\Desktop\du an cuoi khoa\main.py", line 5, in <module>
    from pynput import Controller

**Comment by dqv12908** [comment]
> @dqv12908, change it to `from pynput.mouse import Controller`.

thanks a lot bro
