### ISSUE TITLE
I am use GlobalHotKeys it's neither error nor print(12323) I don't where was wrong

### ISSUE THREAD

**Issue by WingDust** [moses-palmer/pynput#211]
![2](https://user-images.githubusercontent.com/45911286/71762227-fe8ab080-2f07-11ea-93b9-cda6c196f237.gif)

![image](https://user-images.githubusercontent.com/45911286/71762254-25e17d80-2f08-11ea-9216-3e55ea69e607.png)

**Comment by moses-palmer** [comment]
Thank you for your report.

Can you please provide your code as a code snippet?

**Comment by moses-palmer** [comment]
I will close this issue due to lack of feedback. Please reopen if you can provide a snippet.
