### ISSUE TITLE
is it possible to listen keyboard input but not show character on display?

### ISSUE THREAD

**Issue by nquantum** [moses-palmer/pynput#216]
I scan keyboard input for control output: say for control robot direction a = left, d = right, e = up, s = down. So library is work well on receive input character. However when press any key, the character  also show on display too. Is it possible to just scan keyboard input without show what key that pressed?

**Comment by moses-palmer** [comment]
Please have a look at the [documentation](https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Listener):

* **You may use the `suppress` argument to suppress events from being passed on to the system.** Please note that this will block _all_ keyboard events, and may result in system instability on _Linux_.

* **You may use the `darwin_intercept` and `win32_event_filter` arguments.** Please note that they work somewhat differently, and they require handling lower level events. The upside is that you get to choose which events to block.
