### ISSUE TITLE
The example code in version 1.6.5 document doesn't work

### ISSUE THREAD

**Issue by jfongattw** [moses-palmer/pynput#217]
Windows Vista, Python 3.6.8 32bit
The example code in "Global hotkeys" section,
hotkey = keyboard.HotKey(keyboard.HotKey.parse('<ctrl>+<alt>+h'), on_activate)
doesn't work. The pressed 'h' key is <72>, not 'h', when ctrl+alt is pressed. Also, the pressed key is Key.ctrl_l. not Key.ctrl

And also, the "return False" won't work in on_activate() callback.

**Comment by moses-palmer** [comment]
Thank you for noticing!

I have updated the examples to perform the same canonicalisation as the specialised listener does.

Regarding your other finding, I think I will have to make a decision on which behaviour to keep---the actual behaviour or the one from the documentation.
