### ISSUE TITLE
mouse position or move don't work in X Window, but gets positions

### ISSUE THREAD

**Issue by inceabdullah** [moses-palmer/pynput#220]
I use Debian 9 in Docker so, I have read similar [issue in Raspberry Pi](https://github.com/moses-palmer/pynput/issues/48). 

I use Ubuntu 16.04 and Debian 9 in Docker. In both I have tried with python2 and python3 and pynput versions: 1.5.2, 1.6.0 and last version, even purge then install again. But does not work.

I can get mouse position with **Controller().position** but
**Controller().position = (0, 0)**
or
**Controller().move(5, 5)**
don't work.

**Comment by moses-palmer** [comment]
Thank you for your report.

What do you run on the host?

**Comment by inceabdullah** [comment]
`uname -a`
**Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux**

by the way: it works perfectly in host.

**Comment by inceabdullah** [comment]
I am sorry I was in a hurry. I have just figured out that **Controller().position = (x, y) and .mode(x,y)** do work even `cursor keeps location in screen`
