### ISSUE TITLE
Illegal hardware instruction on macOS 10.15.2

### ISSUE THREAD

**Issue by creepinson** [moses-palmer/pynput#223]
Python crashes with
4825 illegal hardware instruction  python3 
I can't find anything online about this.
I'm pretty certain it has to do with the keyController.press

This is my current code:
```python
from pynput.keyboard import Key, Controller, Listener
import time
import sys
import threading
import logging 
import tkinter as tk

keyController = Controller()
running = False

def keypress(event):
    global running
    print(event.keysym)
    if(event.keysym == "F10"):
        running = not running

def thread_function():
    global running
    print("Thread starting for wasd key bot")

    while(True):
        try:
            if running:
                keyController.press("w")
                time.sleep(500)
                keyController.release("w")
                keyController.press("a")

                time.sleep(500)
                keyController.release("a")
                keyController.press("s")

                time.sleep(500)
                keyController.release("s")
                keyController.press("d")
                
                time.sleep(500)
        except KeyboardInterrupt:
            sys.exit()

x = threading.Thread(target=thread_function, args=())
x.setDaemon(True)
x.start()

root = tk.Tk()
root.bind_all('<Key>', keypress)


root.mainloop()
````

**Comment by creepinson** [comment]
By the way, I'm on Mac OSX 10.15.2

**Comment by moses-palmer** [comment]
Thank you for your very strange report.

I am rather certain that this does not stem from _pynput_. This library is a pure Python package. It does, however, rely on objective C bindings (_pyobjc-framework-Quartz_) on _macOS_. Have you read [this thread](https://discourse.brew.sh/t/almost-all-applications-crash-with-illegal-hardware-instruction-on-old-2009-macbook-pro/4089)?

**Comment by jesuslopezlugo** [comment]
I have the same issue on OS X 10.15.3. I'm using PySide2 v5.14.0 and pyinput v1.6.8. I just implemented  mouse and keyboard listeners

When running only pyinput works perfectly but when running with PySide2 GUI get this error in the console:
```[1]    4638 illegal hardware instruction sudo python main.py -vv```

I'm sure the error happens at the start of Keyboard Listener after running PySide2 Application thread.

This is my Keyboard class:

```python
from pynput import keyboard
class KeyboardActivity:
   keyboard_events_count = 0
   listener = None

   @classmethod
   def start(cls):
       try:
          cls.listener = keyboard.Listener(on_release=cls.on_release)
          cls.listener.start()
       except Exception as e:
          console.error(e)

   @classmethod
    def on_release(cls, key):
        cls.keyboard_events_count += 1

   @classmethod
    def stop(cls):
       cls.listener.stop()
```

Then, the main script execute the `start` method after run PySide2

Note: My terminal has accessibility permissions and also run as root. The `mouse` listener works perfectly but the `keyboard` don't with PySide2

**Comment by moses-palmer** [comment]
I'll close this issue, as I cannot se another other reason than the CPU being incompatible with native libraries.
