### ISSUE TITLE
Define an unnamed key as global hotkey

### ISSUE THREAD

**Issue by Babber** [moses-palmer/pynput#228]
Hi,
I am trying to define hotkeys with some otherwise useless keys on my keyboard. The Listener returned keycodes for these, like <269025072>, but I couldn't find the right syntax yet to feed these into my script where I would define the hotkeys:

```
hotkeys = keyboard.GlobalHotKeys({
'<cmd>+<shift>+<left>': func1,
'<cmd>+<shift>+<right>': func2,
# 269025072: func3,       # or rather?..
'<key.none: <269025072="">>': func3})
```

Is this possible at all? If yes, what would be the proper way to do this? If no, I would love to add this to the feature requests.
Thanks!

**Comment by moses-palmer** [comment]
Thank you for your report.

This is currently not supported; the string between brackets is looked up in `pynput.keyboard.Key`. Your feature requests seems reasonable though, so I will add it to the next version.

**Comment by Babber** [comment]
Great, thank you!

**Comment by moses-palmer** [comment]
Since this has landed in *master*, I will close this issue.
