### ISSUE TITLE
I need some further examples for global hotkeys

### ISSUE THREAD

**Issue by jfayre** [moses-palmer/pynput#229]
Hi,
I'm relatively new to Python.
I'm writing an application that currently uses the Keyboard module for setting global hotkeys.
Some of my users are reporting some odd issues when registering global hotkeys, so I want to try pynput.
I need to know how to set up a series of global hotkeys, then keep checking for those while the ap is running. I also need to perform other logic while the listener is running. 
If I use the example from the documentation using the globalHotKey function and then using h.join() inside the with block, everything blocks other than the hotkeys.
I'm unclear which portion of my code should go inside the with block.
I apologize if this is a newbie question.
For reference, my existing project can be found at:
http://www.github.com/jfayre/talking-flight-monitor

**Comment by moses-palmer** [comment]
Hi,

This question pops up quite often, so I am inclined to create a FAQ... In an case, have a look at the documentation [here](https://pynput.readthedocs.io/en/latest/keyboard.html#monitoring-the-keyboard), specifically under the *...or, in a non-blocking fashion* comment.
