### ISSUE TITLE
pynput not working in another game app

### ISSUE THREAD

**Issue by Zoha** [moses-palmer/pynput#230]
Hello
I am using pynput in windows 
I'm trying to get user key presses in another game application and then maybe execute some custom key presses 
I using very basic default example of pynput 
Problem is that events triggered in outside of the game 
But in game events not triggered

```
from pynput import keyboard

def on_press(key):
    try:
        print('alphanumeric key {0} pressed'.format(
            key.char))
    except AttributeError:
        print('special key {0} pressed'.format(
            key))

def on_release(key):
    print('{0} released'.format(
        key))
    if key == keyboard.Key.esc:
        # Stop listener
        return False

# Collect events until released
with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()

# ...or, in a non-blocking fashion:
listener = keyboard.Listener(
    on_press=on_press,
    on_release=on_release)
listener.start()
```
Is this possible to get events in the game? can I do anything about it?

**Comment by moses-palmer** [comment]
Thank you for your report.

What version of *pynput* do you use? [Commit 7a2a9bc](https://github.com/moses-palmer/pynput/commit/7a2a9bc673159d239960b45e752eee16414e0dc3), which is included in the *master* branch, presumably contains a fix for this, but I have not yet received confirmation of this. Perhaps you can test?

**Comment by Zoha** [comment]
Thank you for your answer.
I installed master branch and tested it but still not working.
Perhaps this game will not allow events to go to higher level.
Is there anyway to bypass

**Comment by Zoha** [comment]
I run the script as administrator and it is working now

**Comment by moses-palmer** [comment]
OK, good to know.

Just out of curiosity, did the original version work, or only the *master* branch?

**Comment by Zoha** [comment]
I still using master branch but I will test release version too

**Comment by malay190** [comment]
I'm facing the similar issue while recording the game play. I'm using the updated version of pynput, but it is not recording the keyboard stroke inside the game play. Any suggestion...
