### ISSUE TITLE
Crash my keyboard inputs

### ISSUE THREAD

**Issue by jeff007ali** [moses-palmer/pynput#233]
What I am trying to do is? Instead of writing something repeatedly, you can assign it to code. Then just type that code and it will change that code into assigned text. For example, instead of writing your signature, simply type -sig and it will convert code into "Regards,\nXYZ".

So here my code is : 
```python
from pynput.keyboard import Key, KeyCode, Controller
import pyperclip

def get_recent_text(keyword):
    select_text(keyword)
    copy_text()
    return read_clipboard_data()

def select_text(text):
    print("in select text")
    keyboard = Controller()
    keyboard.press(Key.shift)
    for _ in text:
        keyboard.press(Key.left)
        keyboard.release(Key.left)
    keyboard.release(Key.shift)

def copy_text():
    # print('copy')
    keyboard = Controller()
    keyboard.press(Key.ctrl_l)
    keyboard.press('c')
    keyboard.release('c')
    keyboard.release(Key.ctrl_l)
    time.sleep(0.1)

def paste_text():
    # print('paste')
    keyboard = Controller()
    keyboard.press(Key.ctrl_l)
    keyboard.press('v')
    keyboard.release('v')
    keyboard.release(Key.ctrl_l)

def read_clipboard_data():
    return pyperclip.paste()

def write_clipboard_data(data):
    pyperclip.copy(data)

def replace_keyword(keyword, text):
    write_clipboard_data(text)
    delete_text(keyword)
    paste_text()

def delete_text(string):
    keyboard = Controller()
    for _ in string:
        keyboard.press(Key.backspace)
        keyboard.release(Key.backspace)
        time.sleep(0.05)

def on_press(key):
        for keyword in ["-sig"]:
            if keyword == get_recent_text(keyword): # crashing on this line
                replace_keyword(keyword, "Regards,\nXYZ")

 with Listener(on_press=self.on_press) as listener:
            listener.join()
```

Can you please help me with this weird issue?

**Comment by moses-palmer** [comment]
Thank you for your report.

Can you please provide a stacktrace? The line that you indicate does not seem to be able to produce a crash, but the inner functions seem suspicious, especially your creating a `Controller` in the callback, and possibly also interactions with *pyperclip*.

I suggest that you instantiate your controller outside of the callbacks, just before the listener context block. You may also want to check out [synchronous event listening](https://pynput.readthedocs.io/en/latest/keyboard.html#synchronous-event-listening-for-the-keyboard-listener) to have your code run outside of any callbacks.

And a *github* tip: If you type three backticks (`) as the only characters on a line, you can generate a code snippet. Monospace and indentation will be preserved until you type a line of three backticks once again. And if you after the first backticks immediately type the name of a programming langauge, you will even get syntax highlighting:

    ```python
    from pynput import keyboard, mouse  
    ```

will render as

```python
from pynput import keyboard, mouse  
```

Doing this will allow readers of your comment to copy it into their editors.

**Comment by jeff007ali** [comment]
I have updated my code snippet. Now you can copy paste and run it in editor.

The line which I have mentioned is containing one function call. That function creates the Controller object. That can cause the issue?

**Comment by jeff007ali** [comment]
I think I got the issue. I am trying to call ```get_recent_text(keyword)``` on every on_press event.
In that function also we are pressing shift key which means it will call on_press. So it is going into an infinite loop. 

Do we have any way to bypass on_press event explicitly?

**Comment by moses-palmer** [comment]
Yeah, performing all these manipulations of the keyboard/selection state while typing seems like a recipe for disaster; depending on the application, it may render the keyboard completely useless even if you find a way to limit the number of times it is triggered.

There is an old [experimental branch](https://github.com/moses-palmer/pynput/tree/feature-injected) which I updated just now that adds an "injected" flag to callbacks which you could used to break the recursion, but I don't think that would be enough.
