### ISSUE TITLE
Does it will support listen mouse side button in the future?

### ISSUE THREAD

**Issue by jizhihaoSAMA** [moses-palmer/pynput#238]

**Comment by moses-palmer** [comment]
What platform do you use? On _XOrg_, button values from 1 to 30 are supported, but _Windows_ and _macOS_ appear to have designated constants for the buttons supported by *pynput* but none other.

Depending on your platform, you may dig into the listener implementations found in `pynput/mouse/_<platform>.py` and add debug printing to the event handling; I would very much appreciate a listing of constant values produced this way.

**Comment by jizhihaoSAMA** [comment]
> What platform do you use? On _XOrg_, button values from 1 to 30 are supported, but _Windows_ and _macOS_ appear to have designated constants for the buttons supported by _pynput_ but none other.
> 
> Depending on your platform, you may dig into the listener implementations found in `pynput/mouse/_<platform>.py` and add debug printing to the event handling; I would very much appreciate a listing of constant values produced this way.

I don't know about macOS.I use windows.I know the constant value of side button.In MSDN,it seems that `XBUTTON1` or `XBUTTON2` are side buttons.And in win32.py:
```
    XBUTTON1 = 0x0001
    XBUTTON2 = 0x0002
```
This value could be seen in [MSDN official document](https://docs.microsoft.com/zh-cn/windows/win32/api/winuser/nf-winuser-mouse_event?redirectedfrom=MSDN).

**Comment by moses-palmer** [comment]
This was included in *pynput 1.7*, so I will close this issue now.

**Comment by timojuez** [comment]
Hey Moses, Does that mean that 
`pynput.mouse.Button.button9`
is not platform independent?

**Comment by moses-palmer** [comment]
That is correct. Only values in the [base implementation](https://github.com/moses-palmer/pynput/blob/4cd5f420315acce9b742bf038fa155fc9fdd7395/lib/pynput/mouse/_base.py#L33) are.
