### ISSUE TITLE
Not able to control the keyboard and mouse in one program.

### ISSUE THREAD

**Issue by BigBrain21** [moses-palmer/pynput#240]
I am trying to write a program that will move the mouse, but it keeps giving this error. Is there any way to fix it?

Traceback (most recent call last):
  File "**************", line 5, in <module>
    mouse.click(Button.left, 1)
AttributeError: 'Controller' object has no attribute 'click'

**Comment by BigBrain21** [comment]
here is my code:


from pynput.mouse import Button, Controller
from pynput.keyboard import Key, Controller
mouse = Controller()
mouse.position = (1262, 546)
mouse.click(Button.left, 1)

keyboard = Controller2()
keyboard.press("a")
keyboard.release("a")

**Comment by moses-palmer** [comment]
Your second statement `from pynput.keyboard import Key, Controller` shadows the `Controller` imported on your first line, so the variables `mouse` and `keyboard` are both instances of `pynput.keyboard.Controller`.

Have a look at the examples for the recommended way to access the types (`from pynput import keyboard, mouse` and then qualify types with the middle names).

**Comment by asyankeesfan** [comment]
Where would we find these "examples"? I am having the same issue trying to control both inputs with the same program.

**Comment by moses-palmer** [comment]
You will find them in the [documentation](https://pynput.readthedocs.io/en/latest/).
