### ISSUE TITLE
Event.get() throws exception on timeout

### ISSUE THREAD

**Issue by Adrian-Rosoga** [moses-palmer/pynput#244]
On timeout Event.get() throws queue.Empty instead of None as advertised in the method documentation.
This is not ideal as it exposes the user to internal implementation details (using a queue), should better not leak outside. More important, it is cleaner and simpler to either return the event or None.

Happened with pynput 1.6.8 on Windows 10 - should be the same on other OSes.

The code that triggered it was an attempt to implement the equivalent of getch(). See below.

Fix is trivial, pull request coming soon.

```
def getch(timeout=None):

    from pynput import keyboard
    with keyboard.Events() as events:
        event = events.get(timeout)
        if event is not None and hasattr(event.key, 'char'):
            return event.key.char
        return None
```

Got:
```
(base) C:\Users\Adi>C:/Users/Adi/Anaconda3/python.exe "d:/Root/Code/# Interview/play.py"
Option: Traceback (most recent call last):
  File "d:/Root/Code/# Interview/play.py", line 68, in <module>
    res = getch_non_blocking(4)
  File "d:/Root/Code/# Interview/play.py", line 22, in getch_non_blocking
    event = events.get(timeout)
  File "C:\Users\Adi\Anaconda3\lib\site-packages\pynput\_util\__init__.py", line 277, in get
    event = self._event_queue.get(timeout=timeout)
  File "C:\Users\Adi\Anaconda3\lib\queue.py", line 178, in get
    raise Empty
_queue.Empty
```

**Comment by moses-palmer** [comment]
Thank you for your report and your PR.

I actually had a WIP branch with this fix on my computer, but something got in the way, so it was never merged. Thanks for the remainder! I have merged into *master* and pushed.
