### ISSUE TITLE
ModuleNotFoundError: No module named 'pynput' even if it is installed

### ISSUE THREAD

**Issue by Mesteryl** [moses-palmer/pynput#248]

**Comment by moses-palmer** [comment]
Thank you for your report, but you really need to provide more information than this. How did you install it? On what platform? How do you attempt to use it?

**Comment by Teegreat** [comment]
I'm having the same issue here. I installed python on my PC with the option "Add to PATH" selected.
Also, all the necessary extensions to run python on VsCode was installed but I still get that error message

**Comment by Teegreat** [comment]
problem solved by install pynput.
in CMD "pip install pynput"

**Comment by TheJPMZ** [comment]
I have the same problem. 
Windows 10 with latest python on Thonny
I installed it in the windows powershell with "pip install pynput"
It was installed correctly and even has the file there. 

When I try to do "Import pynput" the following message appears on the shell
ModuleNotFoundError: No module named 'pynput'

**Comment by moses-palmer** [comment]
Thank you for you feedback.

This is related to your environments, and is not an issue with *pynput*, so I will close this issue. I am afraid that I cannot help you with *Powershell* related problems as I have never used it.
