### ISSUE TITLE
how to send special keyboard event through subprocess.PIPE

### ISSUE THREAD

**Issue by vansdev** [moses-palmer/pynput#25]
Hi
i'm trying to build a music player that can control playing state(pause, resume, forward ...) with keyboard
i run a mplayer in a subprocess and try to send keyboard events with the help of pynput.keyboard
(my OS is ubuntu 16.04) 
this is the code to start a mplayer in a subprocess
```
self.player_handler = subprocess.Popen(['mplayer', mp3_url],
                                                   stdin=subprocess.PIPE,
                                                   stdout=subprocess.PIPE,
                                                   stderr=subprocess.PIPE)
```

this is the keyboard listener code(only the on_press method here)
```
        def on_press(key):
            # print '{} pressed, capture by player listener.'.format(key)
            if self.is_player_alive and self.is_playing:
                if isinstance(key, Key):
                    if key == Key.right: # forward                       
                        self.player_handler.stdin.write(???)
                        self.player_handler.stdin.flush()                 

                elif isinstance(key, _xorg.KeyCode):
                    if key.char == u'p': # pause/resume
                        self.player_handler.stdin.write('p')
                        self.player_handler.stdin.flush()
```
note that mplayer itself has key p as pause and right arrow key as forward

now when the music is playing and i press button p, the press action is captured by the listener and the `stdin.write('p')` method writes the character 'p' into the subprocess, the mplayer in subprocess pauses the music as i expected

but what should i send to the subprocess to simulate the right key? does pynput support such function ? i have read some articles about keyboard events in linux but haven't been able to figure it out.

Thanks

**Comment by moses-palmer** [comment]
`stdin`, while reflecting keyboard presses when running a terminal application, is not really related to the keyboard at all. Are you sure that it is the writing to `stdin` of _mplayer_, and not just the fact that you pressed *p*, that triggers the pause?

I am not familiar with the inner workings of _mplayer_, so I can't really help you. Doesn't _mplayer_ support [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/)? I think that would be the way to control it programmatically.
