### ISSUE TITLE
I can't hold the letters

### ISSUE THREAD

**Issue by RED541** [moses-palmer/pynput#251]
I can't hold the letters keys but the special keys work
this doesn't works:
```
clavier.press("a")
time.sleep(3)
clavier.release("a")
```

But this works:
```
clavier.press(keyboard.Key.left)
time.sleep(3)
clavier.release(keyboard.Key.left)
```

**Comment by RED541** [comment]
clavier is my Controller

**Comment by moses-palmer** [comment]
Thank you for your report.

I will add this as a known issue to the documentation, as I have seen it reported before. This appears to be common with synthetic key events; the differ slightly from hardware generated events. The repeat rate seems to be limited to actual hardware keyboards.
