### ISSUE TITLE
cannot detect mouse and keyboard movements when in full screen windows

### ISSUE THREAD

**Issue by IngeniousCoder** [moses-palmer/pynput#252]
hello there,

I have a simple script running using pynput that is made to detect the last time the mouse / keyboard went.
However, this script cannot work when in a full screen window. I reproduced it on two games, MapleStory and Euro Truck Simulator 2.

Thanks

**Comment by IngeniousCoder** [comment]
hello there, an update

i did more extensive testing and found out that some windows pynput will also be unable to detect. one example is task manager. pynput cannot detect inputs in task manager.

**Comment by moses-palmer** [comment]
Thank you for your report.

The issues with *Task Manager*, I guess, stem from *User Account Control* or something relating to operating system protections.

But it seems like what you actually want is [GetLastInputInfo](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getlastinputinfo)---that seems to be exactly what you are looking for, and is provided by the operating system, so you will get a more reliable result.
