### ISSUE TITLE
how do you stop listening using with GlobalHotKey?

### ISSUE THREAD

**Issue by Chovin** [moses-palmer/pynput#255]
throughout the docs, `return False` is mentioned as how you would stop a Listener. This doesn't seem to work with GlobalHotKey

**Comment by moses-palmer** [comment]
Thank you for your report.

Yes, when reading through the code I realise that this simple cancellation method is not supported for `GlobalHotKeys`. The return value from the callback is dropped. However, the other [documented](https://pynput.readthedocs.io/en/latest/mouse.html#monitoring-the-mouse) methods of cancellation should work:

> Call pynput.mouse.Listener.stop from anywhere, raise StopException or return False from a callback to stop the listener.
