### ISSUE TITLE
pynput vs  pyautogui

### ISSUE THREAD

**Issue by NightMachinary** [moses-palmer/pynput#256]
Can you give me a pros/cons of the two? 
I was born with malformed hands, so I only have 5 fingers in total (and some other limitations). I have been thinking of creating a custom wrapper that reads joystick events and maps them to keyboard events, so I can type faster and more ergonomically. I currently have the read-the-joystick-crossplatformly part down using a custom wrapper on top of pygame, and I'm looking for the best way to simulate keyboard events (in a cross-platform way).
Both `pynput` and `pyautogui` seem to fit, and I am wondering what the trade-offs are.

**Comment by moses-palmer** [comment]
I'm afraid that I have no experience with *pyautogui*, but from its `README` I gather that it has a broader focus with support for higher level functions such as message boxes, screen capture and window interactions (for _Windows_ only, it appears); *pynput*, on the other hand, focuses solely on input devices. 

I compared the  _Xorg_ implementation---I personally run _Linux_, so this was easiest---of the keyboard part of the two packages, and *pyautogui* seems to be a bit more limited when it comes to non-US keyboard layouts. *pyautogui* does not appear to support running under *Wayland* on *Linux*.

Please bear in mind that I am very biased, and I do not know what your target platform is. If you just want to transform input events from a joystick to keyboard, I do not think that it matters much which library you choose; just go with whatever API you prefer.

**Comment by NightMachinary** [comment]
@moses-palmer Thanks for the info. Is there a way to use pynput to use a mouse/keyboard as exclusive input device of the running script? I want to use an additional mouse as a foot pedal, for example, and I don’t want this mouse to interfere with other programs. (Essentially, the mouse should only be seen by our program.)
If pynput doesn’t do this, do you have any idea where I should look for this?
(I really like to keep these all crossplatform, but I’m currently using macOS Catalina.)

**Comment by NightMachinary** [comment]
I looked at the docs, `suppress` seems like what I want, but I still have no clue how to limit the script to the second mouse and not interfere with the primary mouse ...

**Comment by moses-palmer** [comment]
Sorry for the late reply.

I'm afraid that that I can't help you with that---*pynput* operates under the assumption that there is only one pointing device, add that is what is presented by the operating system at level that this library installs itself.
