### ISSUE TITLE
Problem entering unicode character

### ISSUE THREAD

**Issue by mroavi** [moses-palmer/pynput#258]
I haven't been able to emulate writing Unicode characters. Here is my attempt:

```python
from pynput.keyboard import Key, Controller

keyboard = Controller()

keyboard.type(u'\u03C9')
keyboard.type('ω')
```
This program doesn't generate any output (also no errors). I read through all the issues regarding Unicode problems but couldn't find a solution. 

I'm running Ubuntu:
```bash
$ cat /proc/sys/kernel/{ostype,osrelease,version}
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Comment by SpecialCharacter** [comment]
Strange. I think Ubuntu might be the reason.
In Windows, I can type:
keyboard.type('\u0301') or
keyboard.type('Я')
Have not tried with Mac.
