### ISSUE TITLE
Crashing on mouse press

### ISSUE THREAD

**Issue by gatesyp** [moses-palmer/pynput#26]
Hello, loving the library so far. 

I set up a basic mouse listener (straight from your example code), and on button press my program is crashing. I tried to debug myself, but I think there is something I'm not understanding. 

For reference, I am using MBP 13.3 inch with no Touch Bar, and python 2.7. 

Here is the code I am using: 
```
   20 def on_click(x, y, button, pressed):
   19     print(button) # identify which button was pressed
   18     print(pressed)
<...>
    5 # Collect events until released
    4 with mouse.Listener(
    3         on_move=on_move,
    2         on_click=on_click,
    1         on_scroll=on_scroll) as listener:
  46      listener.join()
```

As you can see, this is very basic code. And here is the error: 

```
Traceback (most recent call last):
  File "mouse_monitor.py", line 46, in <module>
    listener.join()
  File "/usr/local/lib/python2.7/site-packages/pynput/_util/__init__.py", line 185, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "/usr/local/lib/python2.7/site-packages/pynput/_util/__init__.py", line 140, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pynput/_util/darwin.py", line 246, in _handler
    self._handle(proxy, event_type, event, refcon)
  File "/usr/local/lib/python2.7/site-packages/pynput/mouse/_darwin.py", line 201, in _handle
    (press, release, drag), _ = button.value
TypeError: 'NoneType' object is not iterable
```

This error occurs when I perform any type of button click using the mouse. 

The mouse movement and scrolling features are working just fine - I can collect all data from that. Only mouse clicks seem to prove an issue. 

Thank you!

**Comment by moses-palmer** [comment]
Hi,

Thank you for your report. This is a regression from version _1.3.1_. I have released version _1.3.2_ with a fix.

**Comment by gatesyp** [comment]
Oh wow, that works perfectly! 

Keep up the great work !~
