### ISSUE TITLE
Pynput Crashes as soon as I press a "  '  " or a "  "  "

### ISSUE THREAD

**Issue by Mauzepaus** [moses-palmer/pynput#262]
I get this error as soon as I press `'` or `"` while using a listener:
```
pynput\keyboard\_base.py", line 54, in __init__
    'COMBINING ' + unicodedata.name(self.char))
KeyError: "undefined character name 'COMBINING APOSTROPHE'"
```
and at the same time this error:

```
pynput\keyboard\_base.py", line 56, in __init__
    raise ValueError(self.char)
ValueError: '
```

**Comment by moses-palmer** [comment]
Thank you for your report.

This is a duplicate of #199. What keyboard layout do you use?

**Comment by Mauzepaus** [comment]
I use The US International keyboard lay-out. Could you please tell me how to use the fixup-uncombining-dead-keys?

**Comment by Mauzepaus** [comment]
Never mind, I figured it out!
