### ISSUE TITLE
Unable to capture  keys pressed inside a Remote Desktop Connection using pynput.

### ISSUE THREAD

**Issue by swadeeshs** [moses-palmer/pynput#263]
I am trying to capture the keys pressed by the user when Remote Desktop Connection is opened. Is there a way to accomplish this?

**Comment by meaglerick** [comment]
I was able to do this when my Remote Desktop session was not in Full Screen mode, additionally when using the new Windows Remote Desktop APP (not mstsc), it captures the keyboard input just fine.

**Comment by moses-palmer** [comment]
In that case, I will close this issue as a workaround exists.

**Comment by walid-chekkouri** [comment]
The issue is still occurring. I’m using the new Windows Remote Desktop app, and it requires the window to not be fully expanded, but for my special need I require it to be fully expanded, can this be fixed in Pynput @moses-palmer ?
