### ISSUE TITLE
differen vk codes on mac vs linux

### ISSUE THREAD

**Issue by MarcTheSpark** [moses-palmer/pynput#264]
Hi -- I'm noticing that on my mac and linux computers I get totally different numbers for KeyCode.vk for the same key. For instance, on my mac the letter "b" has a vk of 1, and on linux (both Fedora and Ubuntu) it's 56. The same is true for Key.value.vk with special keys: On mac, Key.alt has a .value.vk of 58. On linux, it has .value.vk of 65513.

What's going on here? To be honest, these seem like strange values in either case.

Is this a bug? Is there a way to get a consistent key code that isn't platform-dependent? What I really want is a code that represents the key pressed, not the character it represents.

Thanks!

**Comment by moses-palmer** [comment]
Thank you for your report.

This would be something akin to the "scan key", which is a representation of the physical position on the keyboard.

This is available for Windows, but I'm not aware of a reasonable way to get it on other platforms. I'm afraid that I will close this issue, as I'm not aware of any way to achieve this.
