### ISSUE TITLE
I have been trying for days but this library keeps crashing my raspberry pi

### ISSUE THREAD

**Issue by PauloFDO** [moses-palmer/pynput#266]
So, I really want to use this library but I'm having big problems with it, as soon as it creates 3 or 4 threads my raspberry pi dies, even if I try to close them with the . stop, I tried everything I could find or think about, I got this to work properly by its own and that made me very happy, but I also need to use input() so now I need to stop it (or it blocks everything) and my problems are back...

this is my code, which works perfectly fine and never crashes anything if I don't need the keyboard for anything else:

```
listener = None
listener = None

def on_press(key):
    if AllowKeys:
        if key == Key.enter:
            global saveFile
            saveFile = True  

def on_release(key):
    global xPosition
    global yPosition
    global zPosition

    if hasattr(key, 'char'):
        if key.char == ('d'):
            xPosition -= 0.03
        elif key.char == ('a'):
            xPosition += 0.03
        elif key.char == ('w'):
            zPosition += 0.03    
        elif key.char == ('s'):
            zPosition -= 0.03
        elif key.char == ('q'):
            yPosition += 0.03   
        elif key.char == ('e'):
            yPosition -= 0.03   

def CheckIfEnterIsPressedToStorePosition(currentPosition):
    global vector3
    global listener
    vector3 = currentPosition
    print("starting")

    if listener == None:  
        listener = Listener(on_press=on_press, on_release=on_release,suppress=True)
        listener.start()

    if saveFile:
        SaveFile()
```

now I need to use input() for a file name, so I thought about doing this:

```
def BlockKeys():
    global listener
    listener.stop()
    listener = None

def SaveFile():
    global saveFile
    BlockKeys()
    saveFile = False
    fileName = InputFileName()
    fileManager.StoreMotorPositionInFile(fileName,Speed(),HandMovement(),vector3)
```

so it stops the listener and repeats the cycle, but as mentioned as soon as it calls this line of code 3 or 4 times everything crashes:

```
listener = Listener(on_press=on_press, on_release=on_release,suppress=True)
listener.start()
```

I tried so many things over the last days and tried every solution I could see in the documentation but couldn't get anything to work, is pynput suppose to completely block Input()?

I also try the "with" and "listener.join" options, and I have the same problem (as soon as I press a key 4-5 times it will crash,plus a need a non blocking option)

**Comment by moses-palmer** [comment]
Thank you for your report.

As a general guideline, you cannot call blocking functions from the callbacks, as outlined in the [documentation](https://pynput.readthedocs.io/en/latest/keyboard.html#the-keyboard-listener-thread). This is especially true in this case, as more keyboard events will be delivered during the call to `input`.

I would suggest you call `input` from the main thread, and perhaps pass commands to it using a `queue.Queue`.
