### ISSUE TITLE
Support  for release keys in GlobalHotKeys

### ISSUE THREAD

**Issue by 10068953** [moses-palmer/pynput#267]
as same as issue #204，when i set a GlobalHotKey, it will be a press GlobalHotkey.(The press callback)

how can i set a realease GlobalHotkey?(The release callback)

thanks

**Comment by moses-palmer** [comment]
Please see the [documentation](https://pynput.readthedocs.io/en/latest/keyboard.html#global-hotkeys) for an example on how to manually implement hotkey functionality. I am sure you will be able to find an acceptable solution from there.
