### ISSUE TITLE
Triggering mouse and keyboard in a specific window

### ISSUE THREAD

**Issue by noodlez04** [moses-palmer/pynput#268]
Hi,
I've read the README and the issues, and haven't found a clear answer for this question:
Is it possible to trigger mouse and keyboard clicks to a specific window, even if it is not the focused one?

Thanks!

**Comment by moses-palmer** [comment]
Hi,

No, this is not possible using *pynput*. For that you want some sort of GUI automation tool, possibly one that hooks into the accessibility framework provided by the platform to avoid having to hardcore control coordinates.
