### ISSUE TITLE
MacOSX: Code not registering alphanumeric keys  [Resolved: accessibility config needed]

### ISSUE THREAD

**Issue by cschar** [moses-palmer/pynput#27]
I Tried running the code below on a macbookpro 8,1 , el capitan 10.11.6.
It only detected special keys, did not detect normal alphanumeric ones.... very odd.

![screen shot 2017-05-20 at 12 19 50 pm](https://cloud.githubusercontent.com/assets/296551/26277494/cbf9d2c2-3d56-11e7-8226-9a198dc4fc9f.png)

```
from pynput import keyboard

def on_press(key):
    try:
        print('alphanumeric key {0} pressed'.format(
            key.char))
    except AttributeError:
        print('special key {0} pressed'.format(
            key))

def on_release(key):
    print('{0} released'.format(
        key))
    if key == keyboard.Key.esc:
        # Stop listener
        return False

# Collect events until released
with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()
```

Any idea?

**Comment by cschar** [comment]
Oh and when I 'Command-Tab' to switch applications, and then relase the Command key, it then says   'a' released.

**Comment by moses-palmer** [comment]
Did you try running it as root? Mac OSX restricts what keys applications are allowed to intercept unless run as root or added to the trusted accessibility applications.

**Comment by cschar** [comment]
Ah yes, For future people who stumble across this issue:

you have to add the terminal application you run python from to the applications that are allowed to control your computer. This can be done in System Preferences > Privacy > Accessibility.

**Comment by suqi** [comment]
Thanks for the solution, I have a suggestion that we can add this note to documentation. 
Because this problem could be annoying, and cost time to search around for new-comers.

How do you think I give a PullRequest of doc update?

**Comment by moses-palmer** [comment]
This is already mentioned in the documentation:
http://pynput.readthedocs.io/en/latest/limitations.html#mac-osx.

**Comment by haoflynet** [comment]
The same code, run as root, still not working, it only detected special keys, did not detect normal alphanumeric.. is it working on macOS High Sierra(10.13.1)?
