### ISSUE TITLE
[Help] How do I not use threads?

### ISSUE THREAD

**Issue by Ipsoka** [moses-palmer/pynput#270]
Hi,
simple question. I dont want to use multithreading here. I am using pynputs keyboard listener to controll the flow of my program. The problem occurs with the threading, because one function requiers a user input via input() which should only be run in the main thread. Doing not so somehow ends up lagging the inputs. I found a solution to that, which seems quiet bad, which is: I use a queue where I put in elements when pressing certain keys. The main thread has a while True loop waiting for new entries in the queue via the queues .get() function.
Is there a way to not use threading here and simple send the keys pressed to the main thread?

**Comment by moses-palmer** [comment]
Hi,

You may want to use the [synchronous API](https://pynput.readthedocs.io/en/latest/keyboard.html#synchronous-event-listening-for-the-keyboard-listener). This is basically what you have implemented; it uses a `queue.Queue` to communicate events. This is one of a very limited number of possible solutions, as all platforms provide event monitoring services based on callbacks on one form or another.

The quick answer is thus: there is no way of avoiding threads, but a synchronous API is already provided.
