### ISSUE TITLE
Queue error on Synchronous event Listening

### ISSUE THREAD

**Issue by tangonaf** [moses-palmer/pynput#276]
Error:
> event = events.get(1.0)
>   File "/home/pi/.local/lib/python3.5/site-packages/pynput/_util/__init__.py", line 277, in get
>     event = self._event_queue.get(timeout=timeout)
>   File "/usr/lib/python3.5/queue.py", line 172, in get
>     raise Empty
> queue.Empty

Code:
```
from pynput import keyboard


def check_key_pressed():
    print("getting in check_key_pressed")
    print(keyboard.Events())
    with keyboard.Events() as events:
        print("getting in check_key_pressed with")
        # Block at most one second
        event = events.get(1.0)
        if event is None:
            print('You did not press a key within one second')
            return False
        else:
            print('Key {0} pressed'.format(event.key))
            return True


while True:
    check_key_pressed()
```

System:

> PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="9"
> VERSION="9 (stretch)"
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by moses-palmer** [comment]
This was fixed in 22bd1b784d30cb523d8ae3596370d21ab1b1a20b.
