### ISSUE TITLE
windows 10, pynput grabs '\x16' key events? what is this?

### ISSUE THREAD

**Issue by alexisdal** [moses-palmer/pynput#277]
Hello,

I'm using a java based UI application to send keyboard strokes to a legacy webapp. In a nutshell, the legacy app was design for a mouse/keyboard/usb_scanner context, and we want to use a touchscreen instead of having people scanning barcodes on table with a sub scanner.

Therefore, that app allows to send keyboard events as-if they had been scanned with a USB barcode reader...

I want to use a keylogger in python to trigger specific actions when specific keyboard events are received (typically sequences of keys like ***1***).

pynput does capture all such events. but what i receive '\x16' key strokes regarless of the key being typed... 
code

```
from pynput.keyboard import Key, Listener

def on_press(key):
    print("{0} on_press".format(key))
    
def on_release(key):
    print("{0} released".format(key))
    if key == Key.esc:
        return False
    
with Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()
```

typical output (ex: for letter 'a', but it seems to be the same for all keys)

```
Key.ctrl_l on_press
'\x16' on_press
'\x16' released
Key.ctrl_l released
```

i'm using python 3.6 in windows 10. pynput was installed with pip this morning. v1.6.8

(for the record, Autohokey does capture all key events normally but it sucks to code in ahk, i would prefer to use python/pynput instead, which is *much* nicer to use)

**Comment by alexisdal** [comment]
in fact, i nailed the origin or the issue. the java app dumps pastes strings in the clip board instead of actually typing. it's not related to pynput at at all. (surprinsingly autohotkey does not complain at all... go figure)

**Comment by Xpos587** [comment]
How you solved this problem?
