### ISSUE TITLE
Keycode with multiple keyboard layouts 

### ISSUE THREAD

**Issue by arikgelman** [moses-palmer/pynput#280]
Hi,
I'm trying to write software based on the pynput directory.
The software should detect a keystroke and, depending on the key code, perform some action.
The software should also work for multiple Keyboard Layouts and should also work on Windows and MAC
I copied the standard snippet of code that should print the user's key:

`
from pynput import keyboard

def on_press(key):
    try:
        print('alphanumeric key {0} pressed'.format(
            key.char))
    except AttributeError:
        print('special key {0} pressed'.format(
            key))

def on_release(key):
    print('{0} released'.format(
        key))
    if key == keyboard.Key.esc:
        # Stop listener
        return False

with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()
`

On a Mac operating system there seems to be no problem when changing a keyboard layout, the software can print the correct character according to the user-selected keyboard layout.

On a Windows operating system there seems to be a problem, the software locks onto the keyboard that was selected during the running phase of the application, and does not recognize the keyboard layout change and therefore prints the character of the keyboard layout that was selected during running the software. 
For example, if the English keyboard layout is selected at runtime, characters are printed in English and even if I change to other keyboard layout such as Arabic, the chatcters printed in English letters. And on the contrary, if the Arabic keyboard layout is selected at runtime, even if you switch back to the English keyboard layout, the software does not recognize the change and therefore continues to print letters in Arabic.

I searched for the topic on the Internet and saw that programmers with a similar problem to mine solved it by using the Pywin32 library, the problem with which I not only want to identify the keyboard layout but also identify the exact character that the user typed.

Thank you very much for your help
Arik

**Comment by moses-palmer** [comment]
Thank you for your report.

*pynput* makes an effort to respond to keyboard layout changes by means of the [`WM_INPUTLANGCHANGE`](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-inputlangchange) message. It does not however seem to be delivered to the library.

The documentation mentions that it is delivered to the *topmost affected window*. [This](https://stackoverflow.com/questions/17907855/how-to-be-informed-when-user-changes-the-language-keyboard-layout-in-windows) *stackoverflow* question talks about it, and the accepted answer laments that implementing the required interface from *C* would be a hassle; doing it from *Python* would be even worse... The *pythoncom* library seems like a possible starting point, by it appears to be a difficult dependency to ship.

**Comment by moses-palmer** [comment]
Given the difficulty to implement this, I will add a note to the [roadmap](https://github.com/moses-palmer/pynput/wiki) and close this issue.

**Comment by i3130002** [comment]
@moses-palmer 
- I should point out that on ubuntu 20 no matter what, key.char is always you're default language layout. 

- pynput.keyboard.Controller().type does not work correctly for Persian standard. سلام turnes be سللم

```bash
1575
alphanumeric key ا pressed
ا'ا' released
1579
alphanumeric key ث pressed
ث'ث' released
1605
alphanumeric key م pressed
م'م' released
1605
alphanumeric key م pressed
م'م' released
1582
alphanumeric key خ pressed
خ'خ' released
48
special key Key.cmd pressed
48
special key Key.space pressed
Key.space released
Key.cmd released
1575
alphanumeric key ا pressed
h'ا' released
1579
alphanumeric key ث pressed
e'ث' released
1605
alphanumeric key م pressed
l'م' released
1605
alphanumeric key م pressed
l'م' released
1582
alphanumeric key خ pressed
o'خ' released
```
