### ISSUE TITLE
🦶 When activate suppress, first key doesn't work

### ISSUE THREAD

**Issue by yedhrab** [moses-palmer/pynput#289]
If I run this code, I can't use <kbd>window</kbd> (`<cmd>`), key is there any option to suppress just<kbd>window</kbd> + <kbd>r</kbd> (`<cmd>+r`)
```py
from pynput.keyboard import Controller, GlobalHotKeys

def on_activate_h():
    Controller().type("🦅🚀👨‍💻🏃‍♂️👮‍♂️👮‍♀️")

with GlobalHotKeys({'<cmd>+r': on_activate_h}) as h:
    h.join()
```

**Comment by SpecialCharacter** [comment]
When I run your code and type <cmd>+r, it gives me "Unhandled exception in listener callback".

**Comment by moses-palmer** [comment]
Yes, you will not be able to reliably type keys that are not mapped in a keyboard layout.

**Comment by yedhrab** [comment]
The main problem is not about controller, main problem is key suppressing. 

_I also updated code_

**Comment by yedhrab** [comment]
> Yes, you will not be able to reliably type keys that are not mapped in a keyboard layout.

I have opened PR for it, could you check it?
