### ISSUE TITLE
Keycodes for media buttons on Linux have different values from standard readings

### ISSUE THREAD

**Issue by smihael** [moses-palmer/pynput#293]
I use this MWE to capture key presses:

```
from pynput import keyboard
def on_press(key):
     print('{0}'.format(key))
listener = keyboard.Listener(on_press=on_press)
listener.start()
```

If I press theXF86AudioLowerVolume button on my Bluetooth keyboard (http://wiki.linuxquestions.org/wiki/XF86_keyboard_symbols), the button gets recognized as <269025041> instead of <122> what I would expect from the xev/xinput reading.
```
$ xinput test 15
key press   122
```

**Comment by moses-palmer** [comment]
The values printed by `xinput` are key codes---somewhat corresponding to physical keys on the keyboard---whereas the values you see returned by *pystray* are keysyms.

So where a key code has the meaning "the button to the top-right", a keysym has the meaning "volume down". You can find a listing of some keysyms [here](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/xorg_keysyms.py).
