### ISSUE TITLE
Remapper with a twist?

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#295]
Hi, I noticed that remapping keys seems kind of difficult in pynput if you do not want to use `win32_event_filter` / `darwin`.
I have come so far that a physical key is pressed, released, deleted, and remapped to another key.
Question:
Is it possible to put this key in a variable instead, say `key = input()[0]`, then `def press_callback(key):` and/or `def release_callback(key):` work their magic, and it puts the remapped key out? I.e. no showing and deleting of the original key?
How would an example code look like?
Thank you very much in advance.

**Comment by SpecialCharacter** [comment]
PS: Just tried the `win32_event_filter` version, does not work :( 
31 should be the virtual key code for a, right?

```
	def win32_event_filter(msg, data):

		global a

		#if msg == 256 and data.vkCode == 31: 
		if data.vkCode == 31: 
			print("Suppressing a up") 
			
			#a = True
			if a == True:
				a = False
			elif a == False:
				a = True
			print("Suppressing a up", a)

			listener._suppress = True
			
		else:
	 		listener._suppress = False # return False # if you return False, your on_press/on_release will not be called
		return True
```

**Comment by SpecialCharacter** [comment]
It gets even stranger, I tested the data.vkCodes from 1 to 10 and they also do not work. I tried them with and without msg == 256. What am I missing?

**Comment by moses-palmer** [comment]
Please consult [the documentation](https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Listener); the filter callback is supposed to return a Boolean to indicate whether to suppress the event. Your code unconditionally returns `True`.

**Comment by SpecialCharacter** [comment]
Oops, I deleted `listener._suppress = True`, now it _almost_ works... except I still see the original letter flashing up before being replaced.
`if (msg == 257 or msg == 256) and (data.vkCode == 8 or data.vkCode == 9 or data.vkCode == 10): # aou`
It should be completely hidden from the OS, right? Or is Python somehow lagging?

**Comment by moses-palmer** [comment]
Unless you have made other changes as well, your code still returns `True` unconditionally. To suppress a keyboard event, please return `False`; assignments to `listener._suppress` have no effect.

**Comment by SpecialCharacter** [comment]
This is my code snippet:
```
	def win32_event_filter(msg, data):
		global Transkription_k
		
		if msg == 256 and data.vkCode == 120:
			print("Suppressing F9 up", Transkription_k)
			
			if Transkription_k == True:
				Transkription_k = False
			elif Transkription_k == False:
				Transkription_k = True
	
		if Transkription_k == True:
			if (msg == 257 or msg == 256) and (data.vkCode == 8 or data.vkCode == 9 or data.vkCode == 10):
				print("S u p p r e s s i n g  aou")
			
		else:
	 		listener._suppress = False # if you return False, your on_press/on_release will not be called
		return True
```

It returns "S u p p r e s s i n g  aou", but still shows the original character for a split second before being replaced.

**Comment by SpecialCharacter** [comment]
PS: And when I add `return False`, the character are completely blocked. But I want just the _original_ characters blocked, not the transcription.

**Comment by SpecialCharacter** [comment]
Is the a way that I can block characters but not system keys? I tried msg == 258 WM_CHAR but it had no effect.

**Comment by SpecialCharacter** [comment]
So basically when the original characters is blocked from being shown on screen, I see the background code/transformations running in the python window as before, but the transformation does not reach the screen. I guess because the blockage is still active?
I even tried to re-inject the letter "a" into the release_callback, but to no avail. Sorry, I am still learning python.

**Comment by SpecialCharacter** [comment]
If there is really no way to do it via the suppressing function, could I use "a" as a hotkey to type "f" etc., without "a" appearing on the screen?

**Comment by SpecialCharacter** [comment]
OK, the hotkey method works alone, but not in tandem with the global listener. Or do I have to insert the hotkeys in a special place? Also the original character is shown, which is the very thing I wanted to avoid...

**Comment by SpecialCharacter** [comment]
Sorry for all that rambling, all I want is something that matches the * (asterisk) option for a AutoHotkey Hotstring (replacement the moment I touch the key). When I read the AHK manual, it looks like pynput and AHK do pretty much the same (write + replace), but I can see the "write" in pynput, whereas the "replace" seems to be instantly in AHK.

**Comment by SpecialCharacter** [comment]
Completely re-designed my script; now it works.

**Comment by moses-palmer** [comment]
Great to hear!
