### ISSUE TITLE
Too many GlobalHotKeys

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#298]
If I execute the script below, it will give me a whole chain of events on a single keypress rather than one event:

TYOU PRESSED SHIFT*T!YOU PRESSED SHIFT*T!YOU PRESSED SHIFT*T!YOU PRESSED SHIFT*T!YOU PREssed shift+t!You pressed shift+T!You pressed shift+t!You pressed shift+T!You pressed shift+t!You pressed shift+T!You pressed shift+t!You pressed shift+T!You pressed shift+t!You pressed shift+T!You pressed shift+t!You pressed shift+T!

How can I limit it to **one** event per single keypress?

```
from pynput import keyboard
kbc = keyboard.Controller()

def on_activate_Shift_t():
	kbc.type('You pressed shift+t!')

def on_activate_Shift_T():
	kbc.type('You pressed shift+T!')

with keyboard.GlobalHotKeys({
        '<shift>+t': on_activate_Shift_t,
        '<shift>+T': on_activate_Shift_T,
        }) as h:
    h.join()
```

**Comment by moses-palmer** [comment]
You have passed two callbacks.

The case of letters does not matter for hotkeys---otherwise you would have to take that into account when using <kbd>shift</kbd> for hotkeys. What are you trying to achieve by passing two separate callbacks?

**Comment by SpecialCharacter** [comment]
So if I just use lowercase letters... oh yes, now it works! Great :)

Does it work together with the normal keyboard listener? Or do I have to keep keyboard.GlobalHotKeys as a separate item?

**Comment by moses-palmer** [comment]
You may want to have a look at the source code for [`GlobalHotKeys`](https://github.com/moses-palmer/pynput/blob/305d8c19a606ba42ab73b5c20e35c1a0784c2833/lib/pynput/keyboard/__init__.py#L194).

You will notice that it is a rather thin wrapper around a `Listener`; if you incorporate the special handling defined in `_on_press` and `_on_release` in your own callbacks, you do not need the `GlobalHotKeys` instance at all.

**Comment by SpecialCharacter** [comment]
Turns out I *need* case-sensitive hotkeys...
Do you plant to add case-sensitive hotkeys in the future?
(Maybe add a Boolean variable for those who do not need case-sensitivity?)

**Comment by SpecialCharacter** [comment]
"_if you incorporate the special handling defined in _on_press and _on_release in your own callback_": how do I exactly do that?
I tried
```
def on_press(key):
	print('on press', key)
def on_activate_a():
	kbc.type('\b''f')
```
followed by
```
with keyboard.Listener(
	'a': on_activate_a,
	on_press=on_press,
	on_release=on_release) as listener:
    listener.join()
```
but it says sytax error.
Examples would help...

**Comment by moses-palmer** [comment]
Please see below:

```python
from pynput import keyboard


def on_hotkey():
    print('Hot key pressed!')

HOTKEYS = [
    keyboard.HotKey(keyboard.HotKey.parse('<shift>+t'), on_hotkey)]


def on_press(self, key):
    for hotkey in HOTKEYS:
        hotkey.press(self.canonical(key))
    # Handle pressed keys


def on_release(self, key):
    for hotkey in HOTKEYS:
        hotkey.release(self.canonical(key))
    # Handle released keys


with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as l:
    l.join()
```

And I would really suggest you find an online Python tutorial. This is an open source library that I have built over the last five years on my free time; I don't have enough of that to help you learn programming. Good luck though!

**Comment by SpecialCharacter** [comment]
And it is much appreciated! :)
The thing is, I want to use _different_ hotkeys for _different_ actions. So I can not use the example above, or?
This works alone:
```
from pynput import keyboard
kbc = keyboard.Controller()

def on_activate_a():
	kbc.type('\b''f')
def on_activate_b():
	kbc.type('\b''k')

with keyboard.GlobalHotKeys({
	'a': on_activate_a,
	'b': on_activate_b
        }) as h:
    h.join()
```
But I fail to get it to work with a listener.
I found this, but it's in Spanish: https://www.codigopiton.com/detectar-pulsacion-de-tecla-en-python/
So I tried: def on_press(key): ... try ... def on_release(key): ... try ... def on_activate_a(): ... def on_activate_b(): ... 
```
hotkeys = {
	'a': on_activate_a,
	'b': on_activate_b
	}
with keyboard.Listener(
	hotkeys=keyboard.GlobalHotKeys(hotkeys), # <-- this is probably wrong
	on_press=on_press,
	on_release=on_release) as listener:
    listener.join()
```
Now the listener works, but the hotkeys do not.

**Comment by moses-palmer** [comment]
You can use the example above, but you will need to define additional hotkeys:

```python
from pynput import keyboard


def on_hotkey_a():
    print('Hot key A pressed!')

def on_hotkey_b():
    print('Hot key B pressed!')

HOTKEYS = [
    keyboard.HotKey(keyboard.HotKey.parse('<shift>+a'), on_hotkey_a),
    keyboard.HotKey(keyboard.HotKey.parse('<shift>+b'), on_hotkey_b)]


def on_press(self, key):
    for hotkey in HOTKEYS:
        hotkey.press(self.canonical(key))
    # Handle pressed keys


def on_release(self, key):
    for hotkey in HOTKEYS:
        hotkey.release(self.canonical(key))
    # Handle released keys


with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as l:
    l.join()
```

**Comment by SpecialCharacter** [comment]
Sorry to ask again, but it gives me an error (I entered q):
```
========== RESTART: D:\data_2020\executable\module_listener+hotkey3.py =========
**Unhandled exception in listener callback**
Traceback (most recent call last):
  File "C:\Users\Bernd\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\Bernd\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\keyboard\_win32.py", line 280, in _process
    self.on_press(key)
  File "C:\Users\Bernd\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
**TypeError: on_press() missing 1 required positional argument: 'key'**
Traceback (most recent call last):
  File "D:\data_2020\executable\module_listener+hotkey3.py", line 40, in <module>
    l.join()
  File "C:\Users\Bernd\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\_util\__init__.py", line 210, in join
    six.reraise(exc_type, exc_value, exc_traceback)
  File "C:\Users\Bernd\AppData\Local\Programs\Python\Python38-32\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Bernd\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\Bernd\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\keyboard\_win32.py", line 280, in _process
    self.on_press(key)
  File "C:\Users\Bernd\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\_util\__init__.py", line 78, in inner
    if f(*args) is False:
TypeError: on_press() missing 1 required positional argument: 'key'
q
>>> 
```

**Comment by moses-palmer** [comment]
See edit.

**Comment by SpecialCharacter** [comment]
Had to replace hotkey.release(**self**.canonical(key)) by hotkey.release(**l**.canonical(key)). Now it works! :)

**Comment by SpecialCharacter** [comment]
OK, here is something weird:
a) print
```
def on_hotkey_a():
    print('Hot key A pressed!')
```
--> Hot key A pressed!

b) type
```
def on_hotkey_a():
    kbc.type('Hot key A pressed!')
```
--> HOT KEY A PRESSED!

So basically the programme suddenly doesn't see a combined hotkey, but only "shift" followed by "a/A". Was this expected?

**Comment by SpecialCharacter** [comment]
I attached a memory variable:
```
def on_hotkey_sb():
memory = 'B'

def on_hotkey_b():
memory = 'b'
```
When I run "shift+b", it put out "B", but the memory is still b. Therefore I know it splits the hotkey.
(I use Windows 10.) Does it work for you?

**Comment by SpecialCharacter** [comment]
Oh, I think 'b' actually overwrites the letter 'shift+b'.
Tried it with the grave accent (= shift+acute), execution was а́̀ (= shift+acute, acute) instead of à.
How to stop it from doing such unsolicited action?

**Comment by moses-palmer** [comment]
As for your example above, assigning to a variable in a function modifies a variable in the function scope, not a global variable. For that, you will need to add the `global` modifier.

Again, I suggest you find a Python tutorial. I really do not have enough free time to help you learn. I will now unsubscribe to notifications from this thread.
