### ISSUE TITLE
No module named Xlib.display

### ISSUE THREAD

**Issue by ionakathryn** [moses-palmer/pynput#30]
Hi I had to run sudo to install the setup.py with python and I believe it downloaded correctly. However when I try to import pynput I am getting the error:

```
>>> import pynput
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pynput/__init__.py", line 23, in <module>
  File "build/bdist.linux-x86_64/egg/pynput/keyboard/__init__.py", line 49, in <module>
  File "build/bdist.linux-x86_64/egg/pynput/keyboard/_xorg.py", line 30, in <module>
ImportError: No module named Xlib.display
```
Hopefully someone can help,
Thanks

**Comment by moses-palmer** [comment]
Thank you for your report.

The issue was cause by platform dependencies being declared as optional. I have made a new release, _1.3.3_, which corrects this issue.

**Comment by ionakathryn** [comment]
Thanks Moses. I cloned the repo last night, has it been updated today. If I
clone the repo again and start again do you think this will solve the
problem?

Thanks

**Comment by moses-palmer** [comment]
Yes, I made the new release a few minutes ago.

**Comment by ionakathryn** [comment]
Hi I cloned the new version, installed and tried importing the pynput module however am getting the same error. Hopefully this can be solved.
These are the last few lines when installing setup.py 

`    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (enum34 1.1.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('enum34>=1.1.3'))
`

Thanks

**Comment by moses-palmer** [comment]
You will need to manually update enum34, as pip does not do that
automatically.

**Comment by ionakathryn** [comment]
OK there is a problem upgrading to the latest pip in Ubuntu and to get around this I had to use easy_install command. 

Thanks for your help.
