### ISSUE TITLE
Request to update pip version and master branch code bug feedback

### ISSUE THREAD

**Issue by BruceLee569** [moses-palmer/pynput#300]
The current pip version 1.6.8(Feb 28, 2020) is a bit old, and the bugs are still there, like [this issue](https://github.com/moses-palmer/pynput/commit/d7dd43d0c81d5355c51f6010fb44c24aa78a86d6#diff-ad05ddabfaab37ea86da8e09576debef), to avoid this bug, I reinstalled the master version.

The master version has a bug as follows:

After running the first example given in the official documentation:
```Python
from pynput import keyboard

def on_press(key):
    try:
        print('alphanumeric key {0} pressed'.format(
            key.char))
    except AttributeError:
        print('special key {0} pressed'.format(
            key))

def on_release(key):
    print('{0} released'.format(
        key))
    if key == keyboard.Key.esc:
        # Stop listener
        return False

# Collect events until released
with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()
```

When I press the copied shortcut key Ctrl+C, the output displayed is as follows:
```
special key Key.ctrl_l pressed
alphanumeric key  pressed
'\x03' released
Key.ctrl_l released
```

So the KeyC.char after Key.ctrl_l pressed is a garbled character, please check, thanks a lot! 😉

**Comment by moses-palmer** [comment]
There are a few known bugs (#94 and #296) that I would like to solve before making the next release---*pynput 1.7*.

**Comment by moses-palmer** [comment]
I have uploaded *pynput 1.7.0* to *PyPi*.
