### ISSUE TITLE
Mouse controler cannot simulate and listener cannot detect the mouse side buttons

### ISSUE THREAD

**Issue by BruceLee569** [moses-palmer/pynput#301]
Many mice have fourth and fifth buttons located near the thumb, their functions are usually used to move forward and backward.

There are no these two special buttons in `pynput.mouse.Button`, and the mouse listener cannot detect the event after I press the side button.

After that, I went to see the well-known [keyboard](https://github.com/boppreh/keyboard) and [mouse](https://github.com/boppreh/mouse) modules. They do not support mac, but the advanced functions of the keyboard are very easy to use. The hook of the mouse package can also monitor the side buttons of the mouse, but after simulating pressing the side buttons (called x and x1 in it), the application does not respond.

Originally, I planned to use these two packages, but when I modified the corresponding functions, there would be a splash screen issue just after running, and the mouse and keyboard were stuck until I called a cpu bound function, and the same function was in pynput It runs nearly twice as fast.

Maybe because the keyboard package is implemented in pure python, I care more about speed, so now I use pynput again😂

**Comment by moses-palmer** [comment]
I assume that you use *Windows*, as *Linux* has support for additional buttons.

I gather from the [documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput) that *Windows* does indeed support additional buttons.

**Comment by moses-palmer** [comment]
I have pushed an initial attempt at a resolution to [`feature-win32-mouse-xbuttons`](https://github.com/moses-palmer/pynput/tree/feature-win32-mouse-xbuttons).

When testing it, I realised that I don't own a mouse with any additional buttons. Is it possible for you to test the branch? The following script should do:

```python
from pynput import mouse

def handle(*args):
    print(args)

with mouse.Listener(on_click=handle, on_scroll=handle) as l:
    l.join()
```

**Comment by BruceLee569** [comment]
> 我已初步尝试解决一个问题[`feature-win32-mouse-xbuttons`](https://github.com/moses-palmer/pynput/tree/feature-win32-mouse-xbuttons)。
> 
> 在测试时，我意识到我没有任何其他按钮的鼠标。您可以测试分支吗？以下脚本应该执行：
> 
> ```python
> from pynput import mouse
> 
> def handle(*args):
>     print(args)
> 
> with mouse.Listener(on_click=handle, on_scroll=handle) as l:
>     l.join()
> ```



> I have pushed an initial attempt at a resolution to [`feature-win32-mouse-xbuttons`](https://github.com/moses-palmer/pynput/tree/feature-win32-mouse-xbuttons).
> 
> When testing it, I realised that I don't own a mouse with any additional buttons. Is it possible for you to test the branch? The following script should do:
> 
> ```python
> from pynput import mouse
> 
> def handle(*args):
>     print(args)
> 
> with mouse.Listener(on_click=handle, on_scroll=handle) as l:
>     l.join()
> ```

Left-click, right-click, middle-click, and middle button scroll can all be detected, but the two buttons on the side, there is no output after I pressed.

**Comment by moses-palmer** [comment]
Then I suppose those are not mapped as X buttons...

Can you please find [this](https://github.com/moses-palmer/pynput/blob/b4d31e1f9c1cf009b2176dc9fb9383a8c51a4f5d/lib/pynput/mouse/_win32.py#L200) line and add the statement `print(data)`? Also verify that you have [this](https://github.com/moses-palmer/pynput/blob/b4d31e1f9c1cf009b2176dc9fb9383a8c51a4f5d/lib/pynput/mouse/_win32.py#L211) line in your cloned repo.

**Comment by BruceLee569** [comment]
> Then I suppose those are not mapped as X buttons...
> 
> Can you please find [this](https://github.com/moses-palmer/pynput/blob/b4d31e1f9c1cf009b2176dc9fb9383a8c51a4f5d/lib/pynput/mouse/_win32.py#L200) line and add the statement `print(data)`? Also verify that you have [this](https://github.com/moses-palmer/pynput/blob/b4d31e1f9c1cf009b2176dc9fb9383a8c51a4f5d/lib/pynput/mouse/_win32.py#L211) line in your cloned repo.

It's my fault, the clone and download address in the branch link you gave is the master branch code. I just tested the new code. After pressing the side forward button, the error is reported as follows:

```Python
File "C:\Users\bruce\PycharmProjects\pynput\lib\pynput\mouse\_win32.py", line 230, in _handle
    button, pressed = self.X_BUTTONS[msg][data.mouseData >> 16]
IndexError: tuple index out of range
```
Debug Info as follows:
name | value
-- | --
msg | 523
self.X_BUTTONS[msg] | ({32: <Button.x1: (256, 128, 1)>, 64: <Button.x2: (256, 128, 2)>}, True)
data | <lib.pynput.mouse._win32.Listener._MSLLHOOKSTRUCT object at 0x0000021C4127DDC8>
data.mouseData | 131072

And after pressing the side backward button, debug Info as follows:
name | value
-- | --
msg | 523
self.X_BUTTONS[msg] | ({32: <Button.x1: (256, 128, 1)>, 64: <Button.x2: (256, 128, 2)>}, True)
data | <lib.pynput.mouse._win32.Listener._MSLLHOOKSTRUCT object at 0x0000022D53B2DE48>
data.mouseData | 65536

So I think the two lines of code can be modified to :
```Python
button = self.X_BUTTONS[msg][0][data.mouseData >> 11]
pressed = self.X_BUTTONS[msg][1]
self.on_click(data.pt.x, data.pt.y, button, pressed)
```
so that there will be no errors. and the printed messages of forward and backward side button are :
```
(3180, 1653, <Button.x2: (256, 128, 2)>, True)
(3180, 1653, <Button.x2: (256, 128, 2)>, False)
(3180, 1653, <Button.x1: (256, 128, 1)>, True)
(3180, 1653, <Button.x1: (256, 128, 1)>, False)
```
At the same time, I also tested the call of the simulated click `pynput.mouse.Button.x1` and `pynput.mouse.Button.x2`. After the execution, the application responded accordingly. Is great! Look at how the code is modified, whether I made a pull request or what, I'm sorry, I am not familiar with git branch operations.

**Comment by moses-palmer** [comment]
I updated the branch slightly. With the feature branch checked out, please run

```
git fetch
git reset --hard origin/feature-win32-mouse-xbuttons
```

I corrected the layout of the data, but did not incorporate your bitmask change (`data.mouseData >> 11`), since the documentation is very clear on that point. Would you mind testing again?

**Comment by BruceLee569** [comment]
> I updated the branch slightly. With the feature branch checked out, please run
> 
> ```
> git fetch
> git reset --hard origin/feature-win32-mouse-xbuttons
> ```
> 
> I corrected the layout of the data, but did not incorporate your bitmask change (`data.mouseData >> 11`), since the documentation is very clear on that point. Would you mind testing again?

After pressed button x1, raise a KeyError:

```Python
  File "C:\Users\bruce\PycharmProjects\pynput\lib\pynput\mouse\_win32.py", line 218, in _handle
    button, pressed = self.X_BUTTONS[msg][data.mouseData >> 16]
KeyError: 1
```

name | value
-- | --
msg | 523
self.X_BUTTONS[msg] | {32: (<Button.x1: (256, 128, 1)>, True), 64: (<Button.x2: (256, 128, 2)>, True)}
data | <lib.pynput.mouse._win32.Listener._MSLLHOOKSTRUCT object at 0x0000020394EACEC8>
data.mouseData | 65536


`data.mouseData >> 16` is equl to `65536 >> 16`, result is 1. `self.X_BUTTONS[msg]` is a dict only with key 32 and 64, so maybe the key name of `X_BUTTONS` should modify to 1 and 2 ?

**Comment by moses-palmer** [comment]
Ah, turns out the keys should not be `MK_XBUTTONn` but rather `XBUTTONn`. I have made another update that should fix this.

**Comment by BruceLee569** [comment]
Now the test passes 😄

**Comment by BruceLee569** [comment]
> Ah, turns out the keys should not be `MK_XBUTTONn` but rather `XBUTTONn`. I have made another update that should fix this.

Now the test passes 😄

**Comment by moses-palmer** [comment]
Great! I have merged the feature branch and uploaded *pynput 1.7.0*.

**Comment by deekb** [comment]
works on linux:
output: `Python 3.8.10 (/usr/bin/python3)
>>> %Run autoclick.py
(191, 682, <Button.button9: 9>, True)
(191, 682, <Button.button9: 9>, False)
(191, 682, <Button.button8: 8>, True)
(191, 682, <Button.button8: 8>, False)
(191, 682, <Button.button9: 9>, True)
(191, 682, <Button.button9: 9>, False)
(191, 682, <Button.button8: 8>, True)
(191, 682, <Button.button8: 8>, False)`
