### ISSUE TITLE
Example for darwin_intercept?

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#303]
Seems there are not many examples for how to use `darwin_intercept` in a concrete case...

I want to turn this code snippet from `win32_event_filter` into `darwin_intercept`:

```
def win32_event_filter(msg, data):
...
if msg == 256 and data.vkCode == 120: # Key down + F9 down
if... # Boolean
listener._suppress = True
return False
...
else:
listener._suppress = False
return True
...
else:
listener._suppress = False # if you return False, your on_press/on_release will not be called
return True
```

I looked at `_darwin.py` but I am still lost.
Thank you very much in advance.

**Comment by SpecialCharacter** [comment]
Tried it with `def darwin_intercept(msg, data):` (on a Mac) just for fun, but it threw some error messages involving `_darwin.py`, so I guess the easy way does not work.

Any hint/website on how to solve this would be highly appeciated.

**Comment by moses-palmer** [comment]
Sorry for the late reply.

The best resource for this would be the the [Apple documentation](https://developer.apple.com/documentation/coregraphics/cgeventtapcallback). The callback specified as `darwin_intercept` will be passed the `type` and `event` arguments.

**Comment by SpecialCharacter** [comment]
Thanks! Can you give an example?
I don't even know where to start :(
I want simply to run pynput, not learn how to program Apple devices...

Naively, I would suppose `def win32_event_filter(msg, data)` becomes `def darwin_intercept(type, event)`, and everything else (if ... then statements) remain the same?
