### ISSUE TITLE
It's not tracking the mouse in Wayland when the cursor is above certain windows

### ISSUE THREAD

**Issue by vstoykovbg** [moses-palmer/pynput#304]
It does not receive mouse movement data when the mouse cursor is over certain apps (GNOME terminal, Gedit, Gnome Calculator). It works over kwrite and over the wallpaper on the desktop.

This happens only on Wayland.

(Can't make a video, because the screen recorder does not work on Wayland.)

```
#!/usr/bin/python3

from pynput import mouse

def on_move(x, y):
    print('Pointer moved to {0}'.format(
        (x, y)))

def on_click(x, y, button, pressed):
    print('{0} at {1}'.format(
        'Pressed' if pressed else 'Released',
        (x, y)))
    if not pressed:
        # Stop listener
        return False

def on_scroll(x, y, dx, dy):
    print('Scrolled {0} at {1}'.format(
        'down' if dy < 0 else 'up',
        (x, y)))

# Collect events until released
#with mouse.Listener(
#        on_move=on_move,
#        on_click=on_click,
#        on_scroll=on_scroll) as listener:
#    listener.join()

# ...or, in a non-blocking fashion:
listener = mouse.Listener(
    on_move=on_move,
    on_click=on_click,
    on_scroll=on_scroll)
listener.start()


read = input("Press enter")
```

**Comment by moses-palmer** [comment]
This is expected and is caused by the X server emulator (`Xwayland`). You will generally only receive events from applications that under the emulator. You can verify this by running any of the applications you mention with the environment variable `GDK_BACKEND` set to `x11`.
