### ISSUE TITLE
How to use Mouse Controller and Listener at the same time ?

### ISSUE THREAD

**Issue by wsdea** [moses-palmer/pynput#305]
Hello, 

I would like to revert the mouse movement. By reverting I mean, if I drag my mouse to the right, I want the cursor to go left. Same for up and down.
I tried the following code, without success. I believe the issue is that I cannot move the mouse inside the `on_move` function because it triggers the event again. Is there a way to move the mouse without triggering `on_move` ? If not, is there a way to solve my problem ? 

Thank you

```
from pynput import mouse
from pynput.mouse import Controller

mouse_Controller = Controller()
PREVIOUS_POS = None

def on_move(x, y):
    global PREVIOUS_POS
    if PREVIOUS_POS is None:
       PREVIOUS_POS = x, y
       return
    movement = (x - PREVIOUS_POS[0], y - PREVIOUS_POS[1])
    PREVIOUS_POS = x, y

    print("Inverting movement {}".format(movement))

    #the following will fail because it triggers the on_move callback (infinite loop)
    mouse_Controller.move(-movement[0], -movement[1])


def on_click(x, y, button, pressed):
    print('{0} at {1}'.format(
        'Pressed' if pressed else 'Released',
        (x, y)))
    if not pressed:
        # Stop listener
        return False

# Collect events until released
with mouse.Listener(
        on_move=on_move,
        on_click=on_click,
        suppress=True
        ) as listener:
    listener.join()

```

**Comment by moses-palmer** [comment]
Thank you for your report.

The short answer to your question is: not really. When you receive the mouse move event, it is too late to cancel it. You attempt to solve this by sending an inverted movement (I suppose what you actually want is to double the negative movement to have it inverted? Your code example will indeed just lock your cursor, even without the additional issues mentioned here.) but this, as you note, will trigger a cascade of additional events.

If you are willing to accept this---the multitude of random movement events will probably break your use case anyway---you may want to check out the branch [`feature-injected`](https://github.com/moses-palmer/pynput/tree/feature-injected). It adds an additional parameter to the event callbacks to allow you to check for injected events and ignore those.

**Comment by BladeX-1** [comment]
@moses-palmer 
What if we want to trigger horizontal-scroll inside on_scroll on vertical scrolls, such that we do not cause cascading effect, why does it still cause problems?
