### ISSUE TITLE
[Feature] Adding keyDown and keyUp similar to pyautogui.

### ISSUE THREAD

**Issue by Jah-On** [moses-palmer/pynput#310]
Title says it all. Thank you!

**Comment by moses-palmer** [comment]
From a quick glance at the [pyautogui documentation](https://pyautogui.readthedocs.io/en/latest/keyboard.html), I cannot really see a difference between those functions and [`pynput.keyboard.Controller.press`](https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Controller.press) and [`pynput.keyboard.Controller.release`](https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Controller.release).

Please reopen if there is anything I have missed.

**Comment by Jah-On** [comment]
I believe while I was testing, it was not working correctly as in there was no delay between a new letter.

**Comment by Jah-On** [comment]
I tested it and press only sends the key once even though I have a time.sleep for 10 seconds before the release.
