### ISSUE TITLE
ImportError when using PyInstaller

### ISSUE THREAD

**Issue by danielkovarik** [moses-palmer/pynput#312]
Hello, I have been using pynut packaged with pyinstaller for years now without any issue. Since upgraded to version 1.7.1 I am getting ImportError when trying to run .exe.

```
[2712] LOADER: Running
Traceback (most recent call last):
  File "lokibots.py", line 13, in <module>
  File "c:\users\kovar\.virtualenvs\lokibots_record-replay-w5ghlkv-\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "classes\recorder.py", line 15, in <module>
  File "c:\users\kovar\.virtualenvs\lokibots_record-replay-w5ghlkv-\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pynput\__init__.py", line 40, in <module>
  File "c:\users\kovar\.virtualenvs\lokibots_record-replay-w5ghlkv-\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "pynput\keyboard\__init__.py", line 31, in <module>
  File "pynput\_util\__init__.py", line 82, in backend
ImportError
[2712] Failed to execute script
```

Latest working version of pynput is 1.6.8

**Comment by danielkovarik** [comment]
@moses-palmer Unfortunately I cannot fall back to 1.6.8 due to the [issue 285](https://github.com/moses-palmer/pynput/issues/285 ) - I can't access the link with the fix now and the fix what I made was overwritten with the lib upgrade.

**Comment by TheLegendOfKitty** [comment]
I am getting the same issue.

**Comment by moses-palmer** [comment]
Thank your for your report.

This might be caused by the changes to the backend import mechanism; to allow selecting backend by means of an environment variable, the import was made dynamic. 

This means that *PyInstaller* cannot see that the actual implementations are used. You will need to modify your PyInstaller configuration to explicitly include the backends that you need.

This, I think, warrants a documentation update.

**Comment by danielkovarik** [comment]
@moses-palmer Thank you. I am unfortunatelly unable to find the correct configuration for pyinstaller. Would you please direct me to the part of the code related with [issue 285](https://github.com/moses-palmer/pynput/issues/285)? I am currently unable to make any update of my app. Thank you very much

**Comment by TheLegendOfKitty** [comment]
What backends does it need?

**Comment by moses-palmer** [comment]
That depends on your target platform. [The documentation](https://pynput.readthedocs.io/en/latest/#forcing-a-specific-backend) contains a listing, and you can check [here](https://github.com/moses-palmer/pynput/tree/master/lib/pynput/keyboard) and [here](https://github.com/moses-palmer/pynput/tree/master/lib/pynput/mouse) to see listings of the corresponding files.

**Comment by TheLegendOfKitty** [comment]
I'm still confused. How can I fix this issue?

**Comment by moses-palmer** [comment]
[The PyInstaller documentation](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#listing-hidden-imports) contains a section about your specific problem. The files you need to include depend on your specific platform, but the import errors will help you.

**Comment by TheLegendOfKitty** [comment]
I'm still having trouble. Do I need to specify the backends with ``hidden-import=``?

**Comment by ioreshnikov** [comment]
@TheLegendOfKitty @danielkovarik Hi!

I have just encountered the same problem. I can confirm that @moses-palmer is right, and using `--hidden-import=` indeed fixes the issue. Here are the options I had to add to my Windows build:
```
  ...
  --hidden-import "pynput.keyboard._win32" ^
  --hidden-import "pynput.mouse._win32" ^
  ...
```
I assume that one needs to replace `_win32` for `_darwin` in case of MacOS build and `_linux` for a Linux build.

**Comment by TheLegendOfKitty** [comment]
Thanks! If I specify all three, will it work everywhere?

**Comment by jpower28** [comment]
@ioreshnikov Hey!

I'm having the same issue but I can't seem to figure out why  --hidden-import "pynput.keyboard._win32" won't work could you maybe explain it?

**Comment by ioreshnikov** [comment]
@jpower28 it looks like 1.7.3 was released some days ago. If the code layout on disk was changed during this release, then you need to figure out the new module path.

**Comment by forrestbao** [comment]
Thanks @ioreshnikov  

> I assume that one needs to replace `_win32` for `_darwin` in case of MacOS build and `_linux` for a Linux build.

For Linux, change `_win32` to `_xorg`:
```
--hidden-import "pynput.keyboard._xorg" 
--hidden-import "pynput.mouse._xorg" 
```
or put into a `spec` file: 

```
hiddenimports=["pynput.keyboard._xorg", "pynput.mouse._xorg"]
```

Tested on Ubuntu 18.04.

**Comment by messaouddhia** [comment]
Still have trouble now

**Comment by SpecialCharacter** [comment]
Can somebody please explain what to do on MacOS? Also `--hidden-import "pynput"` ?

**Comment by moses-palmer** [comment]
@SpecialCharacter, `--hidden-import pynput.keyboard._darwin` and `--hidden-import pynput.mouse._darwin` are the additional arguments for _macOS_, I think.

**Comment by SpecialCharacter** [comment]
Ah, without the quotations and with a . after `keyboard`. The Analysis goes through, but the error messages still say `missing module`. Weird.

**Comment by moses-palmer** [comment]
Does the error message not contain the name of the missing module?

**Comment by SpecialCharacter** [comment]
Still pynput.keyboard and pynput. But I just told pyinstaller `--hidden-import pynput.keyboard._darwin`.
