### ISSUE TITLE
double click and click

### ISSUE THREAD

**Issue by ultimaster1** [moses-palmer/pynput#314]
how can i detect both double click and click

**Comment by moses-palmer** [comment]
You cannot.

The events reported by this library are lower level than double click as you have noticed; you will receive two separate clicks, and will have to use your own filtering to detect double clicks. If the clicks are close, both spatially and chronologically, it is a double click. Your operating system will have settings for how close they must be to register as double clicks, but *pynput* does not provide a way to query that.
