### ISSUE TITLE
Listener argument to ignore Controller-generated events

### ISSUE THREAD

**Issue by juancroldan** [moses-palmer/pynput#318]
It would be great to have some parameter in the Listener so that it ignores the events dispatched by a Controller, so only user inputs are taken into account.

I'm coding a macro recorder application and this feature would be great to stop repeating a loop macro once the user presses any key.

**Comment by moses-palmer** [comment]
Thank you for your report.

This appears to be a duplicate of #69. I have attempted to create a solution, but I have yet to find a way to detect fake events on _X_. You will find the code in the branch [feature-injected](https://github.com/moses-palmer/pynput/tree/feature-injected).
