### ISSUE TITLE
While listener is on, pressing mouse left button would cause mouse pointer hang up.

### ISSUE THREAD

**Issue by 1600** [moses-palmer/pynput#32]
my code is rather simple

```
from pynput import mouse

def on_click(x, y, button, pressed):
    print('Key {0} was {1} at {2}'.format( button, 'Pressed' if pressed else 'Released', (x, y)))

with mouse.Listener(on_move=on_move, on_click=on_click, on_scroll=on_scroll) as listener:
    listener.join()
```

when used under windows, this would cause mouse pointer hanup, sometimes the mouse would start to come back after a while, but in a very unresponsive manner. all subsequent input event will not be captured.

please look into it if you have time.

**Comment by moses-palmer** [comment]
Thank you for your report.

When you say that you get a mouse pointer hangup, do you mean system wide, of just for your `Listener` instance?

**Comment by 1600** [comment]
What do you mean? I have only one mouse cursor, and switching to other application does not help, I think this is system-wide.

**Comment by moses-palmer** [comment]
Thank you for your clarification---I tested clicking around for quite a bit without experiencing anything odd.

The reason for the freeze is that clicking in the terminal window on _Windows_ freezes the application running inside the terminal when the terminal is set to automatically select text. This in turn will cause mouse input to severely lag, as the python thread running in the global event listener is trying to `print` your message to `stdout`.

I will add a suggestion to the documentation to avoid long running code in event callbacks, and to avoid possibly blocking operations.
