### ISSUE TITLE
hotkey with pressing time threshold?

### ISSUE THREAD

**Issue by mo-han** [moses-palmer/pynput#323]
say i'd like to define a hotkey like `<space>(500ms) + h`, which means `space` & `h`, with `space` pressed for at least 500ms time.
is it possible?

**Comment by moses-palmer** [comment]
This is certainly possible, but not directly supported by *pynput*; you would have to implement the logic yourself.

You might for example spawn a `threading.Timer` when you detect <kbd>space+h</kbd>, and cancel it if you receive a release event for space.
