### ISSUE TITLE
My code work properly on Linux and don't work on Windows

### ISSUE THREAD

**Issue by gaetan1903** [moses-palmer/pynput#325]
When i use keyboard.type(), 

if i use variable, it doesn't work on Windows.. but if make it static like keyboard.type("Hello world") , it works. 

So I'm confused : https://github.com/gaetan1903/persistent-paste

and, even Ctrl + Shift + Number doesn't work on Windows 😭 

![image](https://user-images.githubusercontent.com/43904633/100002419-940b8900-2dd5-11eb-93f1-2bcf5289a689.png)

**Comment by moses-palmer** [comment]
Thank you for your report.

Can you please provide a minimal sample snippet that exhibits the problem? I am afraid that I don't fully grasp what you are trying to do.

**Comment by gaetan1903** [comment]
Hi, Thank you for your answer : 

I want to paste the word in variable `_ecoute` when i press Combinaison associate in varibale `COMBINATION`.

It works proprely in Linux, 
on windows there is two problems: 
  - the combinaison doesn't work  
  - if i use another combinaison ( cmd + shift for example): it paste a word like `AJ0DX` but not the word i want

 ```
from pynput import keyboard
from pynput.keyboard import Key, Controller
from threading import Thread

COMBINATION = [
    {keyboard.Key.ctrl, keyboard.Key.shift, keyboard.KeyCode.from_char('1')},
    {keyboard.Key.ctrl, keyboard.Key.shift, keyboard.KeyCode.from_char('2')},
    {keyboard.Key.ctrl, keyboard.Key.shift, keyboard.KeyCode.from_char('3')},
 ]

current = set()
clavier = Controller()
_ecoute = ["paste 1", "paste 2", "paste 3"]


class Ecoute(Thread):
    def __init__(self):
        Thread.__init__(self)


    def run(self):
        with keyboard.Listener(on_press=self.on_press, on_release=self.on_release) as self.listener:
            self.listener.join()


    def on_press(self, key):

        if key in COMBINATION[0]:
            current.add(key)
            if all(k in current for k in COMBINATION[0]):
                clavier.type(_ecoute[0])

        elif key in COMBINATION[1]:
            current.add(key)
            if all(k in current for k in COMBINATION[1]):
                clavier.type(_ecoute[1])

        elif key in COMBINATION[2]:
            current.add(key)
            if all(k in current for k in COMBINATION[2]):
                clavier.type(_ecoute[2])



    def on_release(self, key):
        try:
            current.remove(key)
        except KeyError:
            pass
```

**Comment by moses-palmer** [comment]
I think you might want to check out the [global hotkey listener](https://pynput.readthedocs.io/en/latest/keyboard.html#global-hotkeys). It works similarly to your implementation, but correctly normalises key descriptors; I suspect lines like `keyboard.KeyCode.from_char('1')` are responsible for the different behaviours.
