### ISSUE TITLE
Modifiers not being added to keyboard.Controller.modifiers making shfit_pressed, ctrl_pressed, etc. return false perpetually

### ISSUE THREAD

**Issue by Ghandi263** [moses-palmer/pynput#33]
I've opened [this SO question](https://stackoverflow.com/q/44442256/2000793) , but everything else is so straightforward about pynput I'm starting to think this may be a bug.  I have code that looks like this: 

```
from pynput.keyboard import Controller, Listener

boo = True
keyboard = Controller()

fib_lst = [0, 1]


def on_release(key):
    with keyboard.modifiers as mods:
        print(mods)
        print(key)
        print(keyboard.shift_pressed)


Listener(on_release=on_release).start()

while boo:
    nxt = fib_lst[-1] + fib_lst[-2]
    input(nxt)
    fib_lst.append(nxt)

```

When I release a key it prints an empty set, the name of the key that I released, and False. This is the case regardless of whether or not I am holding down a modifier key. Is there something else I should be doing or does pynput have a bug?

fyi: I'm running pynput version 1.3.5 on python 3.6.1, Windows 7 Enterprise

**Comment by moses-palmer** [comment]
Thank you for your report.

This is a bug in the documentation. The various modifier state properties (`alt_pressed`, `alt_gr_pressed`, `ctrl_pressed` and `shift_pressed`) reflect only the state of the `Controller` instance; it maintains an inner modifier state which is applied when various keys are pressed---for example to uppercase characters from scripts that support it. This state is separate from the current operating system state.

I will update the documentation to make things more clear.

**Comment by Ghandi263** [comment]
After posting this I did see [this closed issue](https://github.com/moses-palmer/pynput/issues/20). I will use that pattern from now on. Thank you for your help.
