### ISSUE TITLE
Lastest version can't Create an Executable But Version 1.6.8 Working well (Python3.7)

### ISSUE THREAD

**Issue by webzone-vn** [moses-palmer/pynput#334]
hello.py

> from pynput import keyboard
> print("Hello World!") 

Tested with pyinstaller, cx_Freeze, py2exe

`pyinstaller.exe -y -F hello.py`

**Comment by moses-palmer** [comment]
Thank you for your report.

Please consult the [documentation](https://pynput.readthedocs.io/en/latest/faq.html#when-using-a-packager-i-get-an-importerror-on-startup).
