### ISSUE TITLE
Stop keyboard and mouse stream

### ISSUE THREAD

**Issue by amitsou** [moses-palmer/pynput#337]
I need to get the keyboard and mouse stream every five minutes. I tried time.sleep() but it doesn't work. Is it possible in pynput?

**Comment by moses-palmer** [comment]
*pynput* will provide a continuous stream of events as they occur. I am uncertain what it would mean to get them every five minutes, would you please expand?

**Comment by amitsou** [comment]
Thank's for your time. I just wanted to create a cronjob in order to get the input and the mouse stream every 5 minutes, but I managed to achieve it using the schedule module in python3!

**Comment by moses-palmer** [comment]
Great! In that case, I will close this issue.
