### ISSUE TITLE
Can you pass vk values to pynput.keyboard.HotKey in place of parse?

### ISSUE THREAD

**Issue by tehruttiger** [moses-palmer/pynput#342]
Is it possible to pass vk values to pynput.keyboard.HotKey in place of parse?  I'm trying to use numpad keys (not overlapping keys with the number row) with parse, but couldn't find documentation on how to do that.  The documentation for parse says:

"The method pynput.keyboard.HotKey.parse is a convenience function to transform shortcut strings to key collections. Please see its documentation for more information."

Where is this information?  Is there a list of keys somewhere you can use in parse?

If this is not possible with parse, I'm certainly fine with sending vks, assuming I can also send modifiers with them (like <alt>+numpad_plus or <shift>+numpad_3 for example).

I am using pynput.keyboard.HotKey rather than the on_press/on_release/COMBO method as it is infinitely more successful at detecting presses during a flurry of other keys being pressed and released, whereas the other method frequently errors out.  My script is being run during a game, so the user is pressing loads of keys and combinations in quick succession.  HotKey deals with this extremely well.

I apologize if this is not the proper place to ask these questions.  I came up blank on stackoverflow, r/learnpython, etc.

**Comment by moses-palmer** [comment]
Yes, this is possible. Please see [here](https://github.com/moses-palmer/pynput/blob/b93b1b53028eb824c2557310c73702de2a609a46/lib/pynput/keyboard/__init__.py#L117).

It appears this piece of documentation in not included on readthedocs; I'll see to it that it gets included, and also the fact that you can pass VK's as `<123>`.

**Comment by tehruttiger** [comment]
I'm sorry, I'm still having trouble.  The VK for the 'a' key is 65, but this code did not cause my on_activate to fire:

```
MyHotkey = "<65>"
hotkey = keyboard.HotKey(keyboard.HotKey.parse(MyHotkey),on_activate)
```

nor did this for shift+a

```
MyHotkey = "<160>+<65>"
hotkey = keyboard.HotKey(keyboard.HotKey.parse(MyHotkey),on_activate)
```

I must still have the syntax wrong.

Thanks!

**Comment by tehruttiger** [comment]
> Yes, this is possible. Please see [here](https://github.com/moses-palmer/pynput/blob/b93b1b53028eb824c2557310c73702de2a609a46/lib/pynput/keyboard/__init__.py#L117).
> 
> It appears this piece of documentation in not included on readthedocs; I'll see to it that it gets included, and also the fact that you can pass VK's as `<123>`.

Sorry to be a pain, but can you give an example of the syntax?  I used the following to get VK values for 'shift' and 'a'

```
from pynput.keyboard import Key, KeyCode, Controller, Listener
from time import sleep

def on_press(key):
    print('press',key.__dict__)
    sleep(3)

def on_release(key):
    print('release',key.__dict__)

with Listener(on_press=on_press,on_release=on_release) as listener:
    listener.join()
```

That gave me 65 for 'a' and 160 for 'shift'.  I then tried this and attempted to trigger the event with the shift key with no luck.

```
from pynput import keyboard
from time import sleep

SkipHotkey = "<160>"
go = True

def dosomething():
    print("hi")

def on_activate():
    dosomething()

def for_canonical(f):
    return lambda k: f(listener.canonical(k))

hotkey = keyboard.HotKey(keyboard.HotKey.parse(SkipHotkey),on_activate)

listener = keyboard.Listener(
    on_press=for_canonical(hotkey.press),
    on_release=for_canonical(hotkey.release))
listener.start()

while go:
    sleep(1)
```

I also tried setting SkipHotkey to "160" which threw a ValueError.
