### ISSUE TITLE
Typing comes to a halt after excessive typing. Windows 10.

### ISSUE THREAD

**Issue by P-T1ps** [moses-palmer/pynput#343]
Hello, I am using windows 10 and a issue I keep running into is after excessive typing all keyboard input on my computer slows down to a halt to the point its printing out about 1 character /second code I'm using:
[https://pastebin.com/RPa81D7F](url) I tried it without the encryption I showed using the cryptography library but it didn't change a thing.

**Comment by moses-palmer** [comment]
Thank you for your report.

Have you tried without opening a new file for every event?

**Comment by moses-palmer** [comment]
I will close this issue, as I suspect it is caused by the excessive opening and closing of files. Please reopen if you think that this is caused by a bug in *pynput*.
