### ISSUE TITLE
Update _win32.py with defined but un-referenced win32 function keys F21-F24.

### ISSUE THREAD

**Issue by daveatkinson** [moses-palmer/pynput#344]
Hi there Moses,

I have a use case for the function keys F21 to F24 - I see they are defined in win32_vks.py but not referenced in _win32.py. I have submitted a patch to address this, would it be possible to merge it?

Thanks,
Dave

**Comment by moses-palmer** [comment]
Thank you for your contribution!

I have merged your PR. There are a few bug fixes for *macOS* in the pipeline, so your additions will unfortunately not be released immediately; I hope you will manage still.

**Comment by daveatkinson** [comment]
Thanks for the merge! No problem, I can work around it in the meantime. And thanks for the project ;-)
