### ISSUE TITLE
the input string be sent as command into the terminal make unexpected behavior

### ISSUE THREAD

**Issue by dangchianthoi** [moses-palmer/pynput#35]
Hi,
I want a menu which can interact with the keyboard as an input method. Something like the code bellow.

The problem is, it also sends the input string as a command into the terminal make unexpected behavior.
For example:
- the input='start', the 'start' command also be sent to the keyboard, causes new command window display.
- the input='exit',  the 'exit' command also be sent to the keyboard, causes the current command window terminated.

So, how can I prevent such input directly send to the keyboard?
Thank you

from pynput import keyboard
keys=[]
#TODO: it also send the input string as command into the terminal made unexpected behavior

def on_press(key):
    try:
        keys.append(key.char)
    except:
        pass

def on_release(key):
    if key == keyboard.Key.enter:
        str = ''.join(keys)
        keys[:] = []
        if str == "start":
            # do something with start command
            print(str)
        if str == "stop":
            # do something with stop command
            print(str)
        if str == "exit":
            # exit
            return False

#Collect events until released
with keyboard.Listener(
        on_press=on_press, on_release=on_release) as listener:
    listener.join()

**Comment by moses-palmer** [comment]
Hi,

I'm afraid I don't really understand what you are trying to achieve. Do you want to emulate `input` (or `raw_input` for *Python 2.7*)?

When listening for key events, no events will suppressed by default, which means that whatever you type will also be sent to the terminal. See [`win32_event_filter`](http://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Listener) for instructions on how to actually suppress key presses. I don't recommend this, however, as that would prevent every other applications from receiving the event.
