### ISSUE TITLE
suppress=True to listener makes Gnome display manager crash

### ISSUE THREAD

**Issue by mikeabbott10** [moses-palmer/pynput#352]
Just a duplicate of [#269](https://github.com/moses-palmer/pynput/issues/269). I didn't notice that.

**Comment by Himan10** [comment]
@mikeabbott10 Hey, did you get any working solution ? 
I'm also facing the same issues but still couldn't get any better way to stop this, Although assigning suppress=False doesn't really results in the same problem.
