### ISSUE TITLE
How do I type the left arrow key to my screen?

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#359]
I want to type the "left" key to my screen. I tried (keyboard.Key.left), (kbc.Key.left), (Key.left), (left) but nothing works. Did I just mess up the grammar or is it principally not possible? Do I have to use an escape key?

from pynput import keyboard
from pynput.keyboard import Controller, Listener
kbc = keyboard.Controller()
Key = keyboard.Key
...
kbc.type(...)

**Comment by SpecialCharacter** [comment]
OK, finally figured out a way to do it, in splitting it into kbc.type('whatever') and kbc.press(Key.left) / kbc.release(Key.left). I still don't understand why kbc.tap(Key.left) does not work...

**Comment by moses-palmer** [comment]
Thank you for your report.

Yes, `pynpyt.keyboard.Controller.type` is strictly for typing text; no special keys are supported. `pynpyt.keyboard.Controller.tap` should work though, as it is only short-hand for `pynpyt.keyboard.Controller.press(key); pynpyt.keyboard.Controller.release(key)`.
