### ISSUE TITLE
When using the mouse listener, is there a way to block/stop the original press from being sent?

### ISSUE THREAD

**Issue by MostHated** [moses-palmer/pynput#361]
Hello,
    I am having a bit of an issue where I am listening for the middle mouse press and then sending keyboard input instead. That is working well, the only issue is, after the keyboard input is sent, the middle mouse click still ends up being sent to the application, causing it to typically paste text. Is there a way to take the intercepted mouse input and stop it from going any further and only send the keyboard input?

<details>
<summary>Here is the relevant section of code.</summary>

```python
def on_click(x, y, button, pressed):
    global currently_pressed
    if button == mouse.Button.middle and pressed and not currently_pressed:
        keyboard.press(Key.ctrl_l)
        keyboard.press(Key.alt_l)
        keyboard.press('0')
        currently_pressed = True

    if button == mouse.Button.middle and not pressed and currently_pressed:
        keyboard.release(Key.ctrl_l)
        keyboard.release(Key.alt_l)
        keyboard.release('0')
        currently_pressed = False


def handle_change(new_state: dict):
    if ('Visual Studio Code - Insiders' in new_state['title']):
        with mouse.Listener(on_click=on_click) as listener:
            listener.join()

```

</details>

Thanks,
-MH

**Comment by moses-palmer** [comment]
Hello,

Please consult the [documentation](https://pynput.readthedocs.io/en/latest/faq.html#how-do-i-suppress-specific-events-only). As you might gather, this does not work particularly well cross-platform.
