### ISSUE TITLE
Using shift_l hotkey (KeyCode = 50)

### ISSUE THREAD

**Issue by wolf0001** [moses-palmer/pynput#396]
I would like to use the "shift_l", "ctrl_l" and "alt_l" hotkeys.  Here's my code which works:

with keyboard.GlobalHotKeys({
	'f': function_1,
	's': function_2,
	'q': function_3,
	'<shift>': function_4,
	'<ctrl>': function_5,
	'<alt>': function_6}) as h:
	h.join()

When I substitute '<shift_l>' and run the code both shifts still trigger when I want only the left shift to trigger.  For '<ctrl_l>' and '<alt_l>' nothing happens.  Can I substitute the keycodes here and how?
Thanks

**Comment by moses-palmer** [comment]
Thank you for your report.

This is not possible, as modifiers---<kbd>alt</kbd>, <kbd>ctrl</kbd> and <kbd>shift</kbd>---are internally normalised to any of the variants before checking whether a hotkey should be triggered.

The reason for this limitation is that most users would expect to be able to use any modifier key on the keyboard, and pre-normalisation was the simplest solution for this. You can find the implementation of the normalisation [here](https://github.com/moses-palmer/pynput/blob/c3af9c8132e73ed0a31f5e5c8b6b86e13df1d71e/lib/pynput/keyboard/_base.py#L707) if you would like to contribute an improvement!

**Comment by wolf0001** [comment]
I managed to find a solution, thank you to "Nitratine"
https://nitratine.net/blog/post/how-to-make-hotkeys-in-python/
I modified his code for my particular hotkeys as follows:
combination_to_function = {
  frozenset([KeyCode(vk=83)]): function_1,   # s
  frozenset([KeyCode(vk=70)]): function_2,   # f
  frozenset([KeyCode(vk=81)]): function_3,   # q
  frozenset([KeyCode(vk=160)]): function_4, # shift_l
  frozenset([KeyCode(vk=162)]): function_5,  # ctrl_l
  frozenset([KeyCode(vk=164)]): function_6,  # alt_l
}
Thanks for your help on this.  Although I am a programmer in other
languages, this is my first attempt at python.
Wolf
