### ISSUE TITLE
Python 3.9.6 Support

### ISSUE THREAD

**Issue by eric15342335** [moses-palmer/pynput#398]
**Description**
Python 3.9.6 changed the lib/enum.py, now the code
```
import pynput
keyboard = pynput.keyboard.Controller()
keyboard.press(pynput.keyboard.Key.V)
```
returns the following error:
```
Traceback (most recent call last):
  File "C:\Users\123er\AppData\Roaming\JetBrains\PyCharmCE2020.3\scratches\scratch_14.py", line 3, in <module>
    keyboard.press(pynput.keyboard.Key.V)
  File "e:\program files\python396\lib\enum.py", line 429, in __getattr__
    raise AttributeError(name) from None
AttributeError: V
```
While `pynput.keyboard.Key.ctrl_l` still works
links:
https://docs.python.org/release/3.9.6/whatsnew/changelog.html
maybe related? https://github.com/moses-palmer/pynput/blob/c3af9c8132e73ed0a31f5e5c8b6b86e13df1d71e/lib/pynput/keyboard/_base.py#L162

**Platform and pynput version**
Windows 10 19041
pynput 1.7.3

**To Reproduce**
```
import pynput
keyboard = pynput.keyboard.Controller()
keyboard.press(pynput.keyboard.Key.V)
```

**Comment by moses-palmer** [comment]
Thank you for your report.

I do not think this is related to changes in *Python*. Has your example ever worked? As far as I know, `V` has never been a `Key` enumeration value for any platform.

Perhaps you meant to write `keyboard.press('V')`?

**Comment by eric15342335** [comment]
Sorry for disturbing you, I am dumb.
