### ISSUE TITLE
Switching language by pynput

### ISSUE THREAD

**Issue by kuruhuru** [moses-palmer/pynput#399]
**Description**
I want to switch language in my Ubuntu laptop by pynput. Ex: win+space or I tried also cmd+space and I tried ctrl+shift (I bound ctrl+shift with switching language by add. Gnome settings) But this does not work.

**Platform and pynput version**
Ubuntu 21.04 pynput 1.7.3
**To Reproduce**
#!/usr/bin/env python3
import pynput.keyboard as kb

keyboard = kb.Controller()
with keyboard.pressed(kb.Key.ctrl):
    keyboard.press(kb.Key.shift)
    keyboard.release(kb.Key.shift)

or 

with keyboard.pressed(kb.Key.cmd):
    keyboard.press(kb.Key.space)
    keyboard.release(kb.Key.space)

Sincerely, 
Petr

**Comment by moses-palmer** [comment]
Thank you for your report.

In general, attempting to trigger system hotkeys using *pystray* does not work. I would suggest you try to do this programmatically; I'm sure there is a _D-BUS_ API or a binary to achieve this in a much more reliable way.
