### ISSUE TITLE
Mouse on_click and keyboard on_press is not being called

### ISSUE THREAD

**Issue by MahendraChoudhary** [moses-palmer/pynput#406]
**Description**
Mouse on_click and keyboard on_press is not being called while python script running as windows service. Windows service log on as Local system.

**Platform and pynput version**
Windows 10 and pynput 1.6.8

**To Reproduce**
1. Create a windows service using service framework.
2.  Register listener on service start
3. Generate exe from py file usin PyInstaller
4. Install service from cmd and start

It's observed that no events are listening by pynput
Pasted code below.

**Comment by MahendraChoudhary** [comment]
`from servicemanager import *
import servicemanager
import win32event
from win32serviceutil import *
from socket import *
from win32event import *
from win32service import *
from pynput import mouse
import time
from pynput import keyboard

class WindowsService(ServiceFramework):
    _svc_name_ = 'pynput'
    _svc_display_name_ = ''
    _svc_description_ = ''

    def __init__(self, args):
        ServiceFramework.__init__(self, args)
        self.hWaitStop = CreateEvent(None, 0, 0, None)
        setdefaulttimeout(60)
        self.keyCount =0
        self.mouseCount = 0
        with open('C:\\Track.log', 'a') as f:
            f.write('init \n')
        self.log('Init')

    def SvcStop(self):
        self.ReportServiceStatus(SERVICE_STOP_PENDING)
        SetEvent(self.hWaitStop)

    def SvcDoRun(self):
        rc = None
        mouse.Listener(on_click=self.__on_mouse_click__).start()
        keyboard.Listener(on_press=self.__on_key_press__).start()
        self.log('Starting service')
        while rc != WAIT_OBJECT_0:
            rc = win32event.WaitForSingleObject(self.hWaitStop, 5000)

    def __on_mouse_click__(self, x, y, button, pressed):
        if pressed:
            self.mouseCount+=1
        
        self.log('Mouse count is '+str(self.mouseCount))

    def __on_key_press__(self, key):
        self.keyCount+=1
        self.log('key press count is '+str(self.keyPressCount))

    def log(self, msg):
        with open('C:\\Track.log', 'a') as f:
            f.write(msg+' \n')

if __name__ == '__main__':
    if len(sys.argv) == 1:
        servicemanager.Initialize()
        servicemanager.PrepareToHostSingle(WindowsService)
        servicemanager.StartServiceCtrlDispatcher()
    else:
        HandleCommandLine(WindowsService)`

**Comment by moses-palmer** [comment]
Thank you for your report.

A _Windows service_ runs on a dedicated desktop, and thus has no access to events from your user desktop. I have a vague recollection that at least on older versions of _Windows_, there was an option to run the service on a user desktop, but I think this has been deprecated.

The solution is to run your application as a normal autostart application.

**Comment by MahendraChoudhary** [comment]
@moses-palmer thanks, autostart has solved my problem.
