### ISSUE TITLE
[MacOs BigSur] Move mouse position, new position not taken into account intermediately after changing position.

### ISSUE THREAD

**Issue by marcu87** [moses-palmer/pynput#415]
**Description**
When I change the position using `mouse.position`, the new position it's not taken into account immediately.  
This works fine on Linux, the bug is in MacOs BigSur.

**Platform and pynput version**
MacOs BigSur
Pynput 1.7.3

**To Reproduce**
```
from pynput.mouse import Controller as MouseController
mouse = MouseController()

mouse.position = (0, 0)
print(mouse.position) # expected to print (0, 0) | printed my last mouse position instead
print(mouse.position) # successfully printed (0, 0)
mouse.position = (50, 50)
print(mouse.position) # expected to be (50, 50) | printed (0, 0) instead
print(mouse.position) # successfully printed (50, 50)
```

**Comment by Saifa-96** [comment]
@marcu87 Hey, Bro I have this problem too. Can you tell me how to solve this?

**Comment by marcu87** [comment]
> @marcu87 Hey, Bro I have this problem too. Can you tell me how to solve this?

As moses-palmer says, the only ugly-work-around is to wait a bit... so you can just add an sleep or something like that.
