### ISSUE TITLE
how can i capture mouse middle press?

### ISSUE THREAD

**Issue by moonsummer** [moses-palmer/pynput#417]
how can i capture mouse middle press?

**Comment by moses-palmer** [comment]
Thank you for your report?

On what platform? I have tested the code [in the documentation](https://pynput.readthedocs.io/en/latest/mouse.html#monitoring-the-mouse) on every supported platform, and verified that `button` is `pynput.mouse.Button.middle` when pressing the middle button.

**Comment by moses-palmer** [comment]
Since this does not appear to be an issue with this library, I will close this issue.
