### ISSUE TITLE
Mouse position listened is out of screen size

### ISSUE THREAD

**Issue by ODtian** [moses-palmer/pynput#421]
**Description**
mouse.Listener on_move event will give a minus coordinate or one bouncing around screen size (not exactly the screen size)
**Platform and pynput version**
Win11 latest

**To Reproduce**
```
def on_move(x, y):
    print(x, y)


listener = mouse.Listener(on_move=on_move)
listener.start()
listener.join()
```

**Comment by moses-palmer** [comment]
This is a duplicate of #386.
