### ISSUE TITLE
Pynput not receiving Shift modifier when using Microsoft Edge

### ISSUE THREAD

**Issue by Impulse-PW** [moses-palmer/pynput#43]
Hello!

I'm writing an app that records the keyboard and mouse and allows the user to replay their actions based on what they've done.

I wanted to record my in Microsoft Edge because windows 10 comes with it by default. If I type:
"TestIng" anywhere in Edge it is recorded as:
"testing"

Meaning the shift modifier wasn't detected for some reason?

I cannot replicate this bug in a normal window like notepad.

**Comment by Piero-Bird** [comment]
I've edited the title, everyone I type no matter where on edge this issue persists.

**Comment by moses-palmer** [comment]
I can confirm.

I suspect that it may be related to [#15](https://github.com/moses-palmer/pynput/issues/15). Relying on the operating system keyboard state to generate the correct characters appears to be somewhat fragile.

**Comment by Piero-Bird** [comment]
Interesting, is there any known fix or is this something somewhat in the dark right now?

**Comment by moses-palmer** [comment]
If you can accept having to limit your program to working only under *Windows*, you may want to look into [`win32_event_filter`](https://github.com/moses-palmer/pynput/blob/e1e57f0581120fdef26abb501eb014df86d97c47/lib/pynput/keyboard/_base.py#L638).

It will allow you to record raw keyboard events, which is what you will actually want to properly replay the recording. Then you can create a class inheriting `pynput.keyboard._win32KeyCode`, overriding [_parameters](https://github.com/moses-palmer/pynput/blob/e1e57f0581120fdef26abb501eb014df86d97c47/lib/pynput/keyboard/_win32.py#L50) to return you recorded data.

**Comment by moses-palmer** [comment]
@Impulse-PW, does this still happen with the _master_ branch with a corrected keyboard listener?

**Comment by moses-palmer** [comment]
I have tested this with the _master_ branch, and the issue seems resolved. If not, please reopen.
