### ISSUE TITLE
AltGr is split in Key.ctrl_l and Key.alt_r

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#44]
I want to turn AltGr+P into ¶ (PILCROW SIGN):
        `if key == 'P':`
            `if keyboard.alt_gr_pressed:`
                `keyboard.type('\b''¶')`
But somehow I didn't manage.

When testing why, I realized that when I type the physical AltGr key alone, it gives me back 
    `key Key.ctrl_l released`
    `key Key.alt_r released`
Is that normal?

**Comment by SpecialCharacter** [comment]
Anyone??

**Comment by moses-palmer** [comment]
*Windows* treats *AltGr* as *Ctrl* + *Alt*, so you will not reliably be able to achieve what you want.

Additionally, [`pynput.keyboard.Controller.alt_gt_pressed`](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L492) does not do what you expect; it merely modifies the internal controller state.

My suggestion is to keep record of the keys you are interested in---for example using a `set` where you add *Control* and *alt* when they are pressed and remove them when they are released---and invoke your action when *P* is pressed and all modifiers active.

**Comment by SpecialCharacter** [comment]
Thank you for your quick reaction!

> /Windows/ treats /AltGr/ as /Ctrl/ + /Alt/, so you will not reliably 
> be able to achieve what you want.
>

Ah! :)

> Additionally, |pynput.keyboard.Controller.alt_gr_pressed| 
> <https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L492> 
> does not do what you expect; it merely modifies the internal 
> controller state.
>

OK.
Just out of interest, for what could I use the internal controller state?

> My suggestion is to keep record of the keys you are interested 
> in---for example using a |set| where you add /Control/ and /alt/ when 
> they are pressed and remove them when they are released---and invoke 
> your action when /P/ is pressed and all modifiers active.
>

Sorry, but I'm kind of new in Python... never have used sets before.
So do I simply type
      my_set = {/control_l, //alt_r/}
?
Or do I need to operate with
|pynput.keyboard.Controller.alt_gr_pressed| 
<https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L492>
     my_set.update(/control_l, //alt_r/)
     my_set.remove(/control_l, //alt_r/)
?

Bernd
