### ISSUE TITLE
Mouse controller functions hanging and makes process useless

### ISSUE THREAD

**Issue by sdfdger** [moses-palmer/pynput#443]
**Description**
Mouse controller click/press/release function won't complete and makes the python window unclosable. Keyboard functions and setting controller.position doesn't hang.

**Platform and pynput version**
x64 Windows 10 Home, 10.0.19043 Build 19043. 
Pynput version on 1.4.4 and 1.7.6 

**To Reproduce**
IDK what I did but I think it was
```
def on_click(x,y,button,pressed):
    controller.click(mouse.Button.left)
listener=mouse.Listener(on_click=on_click)
listener.start()
```
_clicks mouse button_
_computer lags for a bit
python program freezes, can't close the window, even with taskkill_

then on any python

```
>>> from pynput import mouse
>>> mouse.Controller().click/press/release(mouse.Button.left) #it does click/press/release the mouse
hangs forever, window now unclosable, CTRL-C does nothing
```

**Comment by moses-palmer** [comment]
Thank you for your report.

When you call `controller.click(mouse.Button.left)`, you will trigger another call to the listener, thus calling `controller.click(mouse.Button.left)` again and again.

This is the expected behaviour, as the listener will receive all clicks, both user generated or synthetic.

**Comment by sdfdger** [comment]
That's not my problem. The problem is that the controller ceases to work until a computer restart.

**Comment by moses-palmer** [comment]
You may be able to kill your application by pressing <kbd>ctrl+break</kbd> which I think it's the Windows equivalent of <kbd>ctrl+c</kbd>, but indiscriminately posting new input events every time an input events is received will never amount to anything but an infinite game of ping-pong between your application and your operating system.

If you need to trigger other events from a listener, you must apply a condition as to when to do that, and you must make sure that any events you generate do not match the condition.
