### ISSUE TITLE
incorrect behaviour when adding new accented latin characters

### ISSUE THREAD

**Issue by pfps** [moses-palmer/pynput#445]
**Description**
Under X11 pynput modifies the keyboard mapping.  But when it adds new mappings for accented latin characters (like agrave) the mapping entry ends up being different from what pynput expects.  So adding an an entry for agrave ends up with the following mapping instead of a mapping that only maps agrave:
      8    	0x00e0 (agrave)	0x00c0 (Agrave)	0x00e0 (agrave)	0x00c0 (Agrave)	0x00e0 (agrave)	0x00c0 (Agrave)	0x00e0 (agrave)	0x00c0 (Agrave)	
Here pynput doesn't realize that Agrave is also mapped.
Then adding an entry for Agrave ends up with the following mapping:
    103    	0x00e0 (agrave)	0x00c0 (Agrave)	0x00e0 (agrave)	0x00c0 (Agrave)	0x00e0 (agrave)	0x00c0 (Agrave)	0x00e0 (agrave)	0x00c0 (Agrave)	
Here pynput thinks that Agrave should be 103,0 but instead it is 103,1.  As a result Agrave is output as agrave.

**Platform and pynput version**
Linux X11.  Pynput 1.7.6

**To Reproduce**
#!/usr/bin/env python3
import pynput
keyboard = pynput.keyboard.Controller()

keyboard.type('a á e é o ó A Á E É O Ó A À E È O Ò a à e è o ò')

**Comment by moses-palmer** [comment]
Thank you for your report.

I have merged your PR, so I will close this issue.
