### ISSUE TITLE
Why is root is needed for the uinput backend?

### ISSUE THREAD

**Issue by schnabel** [moses-palmer/pynput#450]
Hi,

I think it is a big limitation that root is needed for the uinput backend. Could you explain why this is the case? 
I had a brief look at the pynput code and the evdev code. Since evdev does not require root and seems to offer key encoding, I figured it should be possible to use pynput without root (and dumpkeys).

**Comment by moses-palmer** [comment]
Thank you for your report.

You are correct in your observation that `evdev` does not require root, and I do agree that this requirement is an unfortunate limitation.

`dumpkeys` does, however, require super user privileges when called with the arguments required by this library. *pynput* does not check any privileges, but the call to `dumpkeys` fails when they are lacking [here](https://github.com/moses-palmer/pynput/blob/57504699b4b9a889bf6e15a0c0b9ed654a5677e1/lib/pynput/keyboard/_uinput.py#L439).

**Comment by schnabel** [comment]
Thank you @moses-palmer for your answer. Could you explain what dumpkeys is used for if evdev offers key encoding?

**Comment by moses-palmer** [comment]
`dumpkeys` is used to extract a keyboard layout. Without that, only virtual key codes would be supported.
