### ISSUE TITLE
How to run script with the environment variables?

### ISSUE THREAD

**Issue by Fornball** [moses-palmer/pynput#452]
I am really sorry I have to ask this, but how do I force the script to use uinput? I am trying to run the script on a headless machine with no xserver.  
When I enter this command:
```sudo python3 logger.py $PYNPUT_BACKEND_KEYBOARD=uinput```
I get the same error as when running without root privileges and the environment variable:
```
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name '""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running...
```

What am I doing wrong?

**Comment by moses-palmer** [comment]
Thank you for your report.

`PYNPUT_BACKEND_KEYBOARD=uinput` will override the backend for the keyboard module, but the mouse module will still use the default modules, and the checks for both are always run when importing `pynput`.

Use `PYNPUT_BACKEND_MOUSE=dummy` to force the dummy backend for mouse.
