### ISSUE TITLE
Pause the operation of the physical keyboard and the physical mouse when using this library to automatically operate the keyboard and mouse

### ISSUE THREAD

**Issue by wangmings** [moses-palmer/pynput#458]

**Comment by moses-palmer** [comment]
Thank you for your report.

I presume you mean that operation of the physical keyboard and mouse is inhibited when the `suppress` flag is passed? Or do you request that particular functionality?

I think that the previous paragraph has given you an insight into how to continue, and will thus close this issue. If that is not the case, please reopen.
