### ISSUE TITLE
Events based on selection?

### ISSUE THREAD

**Issue by kootenpv** [moses-palmer/pynput#46]
I was wondering if it is possible to get an event like "text selected keyboard/mouse button released"?
That is, the moment with e.g. Shift+arrow buttons released or after selecting text with the mouse, the mouse being released.
 
Any idea how to achieve it?

BTW: this is really fantastic!

**Comment by moses-palmer** [comment]
Sorry for the late reply.

I did a quick survey of the different supported platforms, and could find a possible solution only for *Xlib*. What platforms will you support?

In any case, this functionality will not be added to *pynput* unless I receive a pull request, as I do not really think it is an input core functionality.
