### ISSUE TITLE
Blocking a hotkey with multiple keys

### ISSUE THREAD

**Issue by bd-charu** [moses-palmer/pynput#469]
Hello, I'm using `win32_event_filter` to disable certain keys but this only disables one key. Is it possible to have it for key combinations like Ctrl+R

**Comment by moses-palmer** [comment]
Hello,

The Windows API only allows for clicking a single event. However, of you maintain state in your listener to keep track of whether any _ctrl_ key is pressed, you could block the _m_ event.
