### ISSUE TITLE
macos 12.4 F1 Press Invalid

### ISSUE THREAD

**Issue by jiayouzl** [moses-palmer/pynput#487]
```
from pynput import keyboard


def on_activate_h():
    print('F1 Press')


if __name__ == '__main__':
    with keyboard.GlobalHotKeys({'<F1>': on_activate_h}) as listener:
        listener.join()
```

MacOS F1-F12 Invalid.

**Comment by moses-palmer** [comment]
Thank you for your report.

Could you please fill in the bug report template? I will need a stack trace to be able to investigate, as I do not have access to a _macOS_ system.

**Comment by jiayouzl** [comment]
> Thank you for your report.
> 
> Could you please fill in the bug report template? I will need a stack trace to be able to investigate, as I do not have access to a _macOS_ system.

Sorry, I am not very good at using GitHub. Where is this error report?

**Comment by jiayouzl** [comment]
> Thank you for your report.
> 
> Could you please fill in the bug report template? I will need a stack trace to be able to investigate, as I do not have access to a _macOS_ system.

```
from pynput import keyboard


def on_activate_h():
    print('F1 Press')


if __name__ == '__main__':
    with keyboard.GlobalHotKeys({'<F1>': on_activate_h}) as listener:
        listener.join()
```
I have just tried it, and this code is invalid depending on the Windows10.

**Comment by jiayouzl** [comment]
hello?~

**Comment by moses-palmer** [comment]
Sorry for the confusion.

The bug report template requests the version of *pynput*, the version of your operating system, a stack trace and preferably code to reproduce.

I still need a stack trace though---I do not really know what you mean by the code is invalid.
