### ISSUE TITLE
Context manager Keyboard.pressed not releasing keys

### ISSUE THREAD

**Issue by the-south-well** [moses-palmer/pynput#5]
This sample code from your documentation doesn't work:

```python
with Keyboard.pressed(Key.shift):
    Keyboard.press('a')
    Keyboard.release('a')
```

An an "a" is emitted instead of "A". 

Changing the last line of the `pressed` method from`self.press(key)` to `self.release(key)` is probably the intended behaviour.

Thanks for the library.

Cheers, Toby

**Comment by moses-palmer** [comment]
Thank you for the report!

I have released [*pynput 1.1.6*](https://pypi.python.org/pypi/pynput/1.1.6) which fixes the issue.
