### ISSUE TITLE
 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly

### ISSUE THREAD

**Issue by abirabedinkhan** [moses-palmer/pynput#518]
When I try to run the script
```
Traceback (most recent call last):
  File "/home/abirabedinkhan/Desktop/RFID/app.py", line 1, in <module>
    import pynput
  File "/home/abirabedinkhan/Desktop/RFID/env/lib/python3.10/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/abirabedinkhan/Desktop/RFID/env/lib/python3.10/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/home/abirabedinkhan/Desktop/RFID/env/lib/python3.10/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ("failed to acquire X connection: No module named 'tkinter'", ModuleNotFoundError("No module named 'tkinter'"))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
```

**Comment by alvaromunoz** [comment]
https://www.geeksforgeeks.org/how-to-install-tkinter-on-linux/

**Comment by abirabedinkhan** [comment]
I did all of those. Btw, I am trying to use it with ssh.

**Comment by moses-palmer** [comment]
Thank you for your report.

When you say that you are trying to use it with SSH, do you mean that you intend to control/monitor a remote computer? In that case you must have an X server running remotely, and you must ensure that the `DISPLAY` environment variable is correctly set in the remote shell.

The error message, however, appears very strange: "No module named 'tkinter'". This happens when *pynput* attempts to import [`pynput._util.xorg`](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/xorg.py), which does not import _Tkinter_.

**Comment by abirabedinkhan** [comment]
Yeah did install ```apt-get install python3-tk``` before running my script. I encountered this problem before in my VM.```apt-get install python3-tk``` fixed my problem there.  However, when I am trying through ssh it shows the same error whether ```apt-get install python3-tk``` installed or not. How do I set the ```DISPLAY``` environment variable?

**Comment by alvaromunoz** [comment]
did you connect with -X argument? or are you using putty? remember the
linux installation must have a display server installed (x org for
example). https://www.baeldung.com/linux/forward-x-over-ssh is a good
tutorial

**Comment by moses-palmer** [comment]
In that case perhaps there easiest solution would be to open a terminal window in the desktop session and run the command `echo $DISPLAY`. Then, when you have SSH'd into the *armbian* host, launch your program thus: `DISPLAY=[output of echo command] python3 app.py`.

**Comment by dodgyrabbit** [comment]
FYI the root cause of this exception is here:
https://github.com/python-xlib/python-xlib/issues/240

In 0.33 it no longer happens
