### ISSUE TITLE
how to add mouse clicks to pynput keylogger?

### ISSUE THREAD

**Issue by bdantas** [moses-palmer/pynput#52]
Sorry if this is not the appropriate place for this, but it's the only place I could find where I could ask a question directly to pynput's developers.

I wrote the little keylogger below and it works like a charm. The only thing missing is for it to also log left mouse clicks. No need for window name or coordinates--merely fact that there was a click (e.g., output would show 'Key.mousebutton_left' or the like).

```
from pynput.keyboard import Key, Listener
import os

# get initial capslock state
exit_code = os.system('''xset q 2>/dev/null | grep -q -E 'Caps Lock: +on' ''')
if exit_code == 0:
	capslock = True
else:
	capslock = False

# this function runs each time a key is pressed
def on_press(key): 
	global capslock
	output = str(key)
	if output == 'Key.caps_lock': # if capslock pressed, swap capslock state
		capslock = not capslock
	if output.startswith('Key') == False: # i.e., if output is alphanumeric
		output = output[1:-1] # remove quotes around character
		if capslock:
			output = output.swapcase()
	print(output)

with Listener(on_press=on_press) as listener:
	listener.join()
```

Can you please help me modify this to also capture left mouse clicks? I've been going around in circles but just don't know python and pynput well enough.

**Comment by moses-palmer** [comment]
This is indeed the correct place for questions relating to _pynput_ :-)

To monitor pointing devices, use [the mouse listener](http://pynput.readthedocs.io/en/latest/mouse.html#monitoring-the-mouse).

**Comment by bdantas** [comment]
Thank you, moses-palmer. Please forgive me for being such a noob, but I'm having trouble combining the keyboard listener with the mouse listener. What's in bold is what I added:

```
from pynput.keyboard import Key, Listener
**from pynput import mouse**
import os

# get initial capslock state
exit_code = os.system('''xset q 2>/dev/null | grep -q -E 'Caps Lock: +on' ''')
if exit_code == 0:
	capslock = True
else:
	capslock = False

# this function runs each time a key is pressed
def on_press(key): 
	global capslock
	output = str(key)
	if output == 'Key.caps_lock': # if capslock pressed, swap capslock state
		capslock = not capslock
	if output.startswith('Key') == False: # i.e., if output is alphanumeric
		output = output[1:-1] # remove quotes around character
		if capslock:
			output = output.swapcase()
	print(output)

**def on_click(x, y, button, pressed):
	button = str(button)
	if pressed:
		if button == 'Button.left':
			print('Key.mousebutton_left')

with mouse.Listener(on_click=on_click) as listener:
    listener.join()**

with Listener(on_press=on_press) as listener:
	listener.join()
```

Please, how do I listen to mouse and keyboard concurrently? The above logs left mouse clicks but ignores keyboard.

**Comment by moses-palmer** [comment]
`Listener.join` will block until the listener is stopped, so your modifications will first listen to keyboard events and then mouse events.

You will have to create the second listener before joining the first one.

**Comment by bdantas** [comment]
Thank you. I think I understand the concept, but am getting tripped up with syntax (I'm completely new to pynput--discovered it yesterday). Would you kindly give me an example of how to do that?

**Comment by bdantas** [comment]
Through trial and error I think I figured it out:

```
from pynput import keyboard
from pynput import mouse
import os

# get initial capslock state
exit_code = os.system('''xset q 2>/dev/null | grep -q -E 'Caps Lock: +on' ''')
if exit_code == 0:
	capslock = True
else:
	capslock = False

# this function runs each time a key is pressed
def on_press(key): 
	global capslock
	output = str(key)
	if output == 'Key.caps_lock': # if capslock pressed, swap capslock state
		capslock = not capslock
	if output.startswith('Key') == False: # i.e., if output is alphanumeric
		output = output[1:-1] # remove quotes around character
		if capslock:
			output = output.swapcase()
	if output.startswith('Key.shift') == False: # i.e., ignore shift keys (e.g., we want to log a~ not aKey.shift~)
		print(output)

def on_click(x, y, button, pressed):
	button = str(button)
	if pressed:
		if button == 'Button.left':
			print('Key.mousebutton_left')

with mouse.Listener(on_click=on_click) as listener:
	with keyboard.Listener(on_press=on_press) as listener:
		listener.join()
```
I'm so happy I finally figured this out. I had struggled with pyxhook for many days before finally giving up and starting over with pynput yesterday. Your module rocks, thank you so much!
