### ISSUE TITLE
How could I detect if pyinput is being used on a Windows machine via remote desktop protocol?

### ISSUE THREAD

**Issue by echeateron** [moses-palmer/pynput#525]
I'm the owner of the remote machine (host), but I've no control on the client machine.

**Comment by echeateron** [comment]
Then it might be possible to install a software to detect SetWindowsHookEx usage on client machine.

But, I've no control over the client machines, and I can't install any software on them. And they could be a Linux, OsX or a Windows machine.

I've control over the host machine only (Windows).  Do you think that the host machine could detect the usage of SetWindowsHookEx by the RDP client machine?

**Comment by moses-palmer** [comment]
As I mentioned, I have no experience in administering or monitoring Windows machines, but the since the code, as I understand it, runs on your host, you should be able to detect it. Determining whether an instance of *pynput* is running on the clients is, I think, not possible.
