### ISSUE TITLE
Characters also appear in the Linux shell

### ISSUE THREAD

**Issue by techhead2** [moses-palmer/pynput#53]
Hi,

I try to use your module for timing cursor key pushes. What surprises me that all pushed characters are "piped" to the background shell and also to my Python program. So, when I push the up-arrow key my bash in the background executes it, too. Is there a way that user input gets only to the Python script?

Joseph

**Comment by moses-palmer** [comment]
Please see [this issue](https://github.com/moses-palmer/pynput/issues/47).
