### ISSUE TITLE
Any way to listen on a particular device on Windows?

### ISSUE THREAD

**Issue by mristin** [moses-palmer/pynput#544]
Hi,
Is it anyhow possible to listen on a particular device on Windows?

**Comment by moses-palmer** [comment]
As far as I know, this is not possible. The information provided to this library is described [here](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-keybdinput), and it does not contain any device specific information. The function used to register a listener is described [here](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexw), and it does not provide a way to limit by device.
