### ISSUE TITLE
Does not recognise '5' on numeric keypad

### ISSUE THREAD

**Issue by marko-pi** [moses-palmer/pynput#546]
For a key '5' on the numeric keypad, pynput.keyboard returns 65437, regardless of whether NumLock is locked or unlocked.

I used your example code (https://pynput.readthedocs.io/en/latest/keyboard.html).

The platform is Raspberry Pi, Python version 3.9.2, pynput version 1.7.6.

**Comment by ajwalkiewicz** [comment]
I believe that this issue was recognized here: https://github.com/moses-palmer/pynput/issues/530

**Comment by marko-pi** [comment]
You are right.  Should I close the issue?
