### ISSUE TITLE
pynput detects mouse scroll wheel movements only *partially* in the Wayland window manager in Linux, but fully in X11

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [moses-palmer/pynput#555]
**Description**
See below.

**Platform and pynput version**
Ubuntu 22.04.2--brand new install. How do I check the `pynput` library version? I don't know how to do that.

Update: `pip install pynput` seems to show I have 1.7.6:
```bash
$ pip install pynput
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pynput in /home/gabriel/.local/lib/python3.10/site-packages (1.7.6)
Requirement already satisfied: python-xlib>=0.17 in /usr/lib/python3/dist-packages (from pynput) (0.29)
Requirement already satisfied: evdev>=1.3 in /home/gabriel/.local/lib/python3.10/site-packages (from pynput) (1.6.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from pynput) (1.16.0)
```

**To Reproduce**

Originally posted here: https://github.com/albertz/mouse-scroll-wheel-acceleration-userspace/issues/8#issuecomment-1575389079

## `pynput` works only partially in Wayland

I just confirmed there is also a problem with `pynput`. When running the Wayland window manager on Ubuntu 22.04, `pynput` can detect scroll wheel movements in Chrome just fine, but _not_ in other programs such as the gnome-terminal, or Sublime Text. 

Here is a small Python test program I just wrote:
```py
# modified from here: https://pypi.org/project/pynput/

from pynput import mouse

def on_scroll(x, y, dx, dy):
    print('Scrolled {}; (x, y)=({:4d}, {:4d}); (dx, dy)={}'.format(
        'down' if dy < 0 else 'up  ',
        x, y,
        (dx, dy),
    ))

# block the main thread, listening
# Collect events until released
with mouse.Listener(
        on_scroll=on_scroll) as listener:
    listener.join()
```

And here is some sample output, which _only prints a line_ when scrolling in Chrome, but not in my terminal nor in Sublime Text:

```bash
$ ./pynput_mouse_wheel.py
Scrolled down; (x, y)=(4625, 1695); (dx, dy)=(0, -1)
Scrolled down; (x, y)=(4625, 1695); (dx, dy)=(0, -1)
Scrolled down; (x, y)=(4625, 1695); (dx, dy)=(0, -1)
Scrolled down; (x, y)=(4625, 1695); (dx, dy)=(0, -1)
Scrolled down; (x, y)=(4625, 1695); (dx, dy)=(0, -1)
Scrolled down; (x, y)=(4625, 1695); (dx, dy)=(0, -1)
Scrolled down; (x, y)=(4625, 1695); (dx, dy)=(0, -1)
Scrolled down; (x, y)=(4625, 1695); (dx, dy)=(0, -1)
Scrolled up  ; (x, y)=(4505, 1698); (dx, dy)=(0, 1)
Scrolled up  ; (x, y)=(4505, 1698); (dx, dy)=(0, 1)
Scrolled up  ; (x, y)=(4505, 1698); (dx, dy)=(0, 1)
Scrolled up  ; (x, y)=(4505, 1698); (dx, dy)=(0, 1)
Scrolled up  ; (x, y)=(4505, 1698); (dx, dy)=(0, 1)
Scrolled up  ; (x, y)=(4505, 1698); (dx, dy)=(0, 1)
Scrolled up  ; (x, y)=(4505, 1698); (dx, dy)=(0, 1)
Scrolled down; (x, y)=(4505, 1698); (dx, dy)=(0, -1)
Scrolled down; (x, y)=(4505, 1698); (dx, dy)=(0, -1)
Scrolled down; (x, y)=(4505, 1698); (dx, dy)=(0, -1)
```

## but it works fully in X11

But in the X11 Window manager, it works _fully_. My same program above is able to detect mouse scroll wheel movements in *all* programs, including Chrome, the terminal it's running in, Sublime Text, etc. That's a big difference and definitely a problem in Wayland!

**Comment by ElectricRCAircraftGuy** [comment]
Note: to switch between the X11 and Wayland window managers in Linux Ubuntu, see the "To use the X11 Window Manager in Ubuntu 20.04, 22.04, etc." section of my answer here: https://askubuntu.com/a/1109490/327339. 

In short, log out, click your name, click the gear in the bottom-right, choose the non-Wayland window manager option.

I also mention that here: https://askubuntu.com/a/1470563/327339

**Comment by moses-palmer** [comment]
Thank you for your report. 

This is a known issue,  please see [the documentation](https://pynput.readthedocs.io/en/latest/limitations.html#linux). In short, the security model of _Wayland_ prevents this library from working,  but you will notice partial support for applications running under _XWayland_, the X emulator. Notable examples of such applications are browsers derived from _Chromium_.

**Comment by albertz** [comment]
Sorry to revive this old issue. I was hoping to get back here at some later point and to find some solution. I understand that the security model of Wayland prevents this. But I was hoping that someone would maybe introduce an API to Wayland which would allow this then. I guess the problem of screen sharing / screen recording is quite similar. I as a user want to be able to give the permission to certain tools to have access to such things.

I'm not sure if there are any updates on Wayland regarding this. I'm not really into Wayland yet.

If not, maybe we should at least fill a feature request somewhere to allow for this. Where would be the best place for that?
