### ISSUE TITLE
Running pynput as a windows service

### ISSUE THREAD

**Issue by masoudr** [moses-palmer/pynput#56]
Hi,
I've written a simple script to save keyboard keystrokes to a text file. The script works fine when running directly by the user but when I create a windows service from, it can't detect the keystrokes.
I first create a standalone executable with `Pyinstaller` and then create a service with `sc.exe`.
Thanks.

**Comment by moses-palmer** [comment]
This is not possible on _Windows_ as of _Windows Vista_. Please see [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683502(v=vs.85).aspx).

**Comment by masoudr** [comment]
Thanks, Is there any workaround except editing registry?

**Comment by moses-palmer** [comment]
Not as far as I know; use an autostarted application instead.
