### ISSUE TITLE
`uinput_device_paths` Kwarg does not work on Windows

### ISSUE THREAD

**Issue by PowerBroker2** [moses-palmer/pynput#562]
**Description**
Tried using `uinput_device_paths` Kwarg to listen to only one specific keyboard, but inputs from all keyboards are "listened-to".

```
from pynput import keyboard

def on_press(key):
    try:
        print('alphanumeric key {0} pressed'.format(
            key.char))
    except AttributeError:
        print('special key {0} pressed'.format(
                key))

def on_release(key):
    print('{0} released'.format(
        key))
    if key == keyboard.Key.esc:
        # Stop listener
        return False

listener = keyboard.Listener(
    on_press=on_press,
    on_release=on_release,
    uinput_device_paths=[r'HID\VID_34EB&PID_1502\9&167F9EC7&0&0000'])
listener.start()
```

__NOTE__: I also tried to specify the device path as just a string (not a list of a string), but nothing changed

**Platform and pynput version**
Windows 11 and pynput 1.7.6.

**To Reproduce**
Use two keyboards and try to only listen to one of them on Windows

**Comment by moses-palmer** [comment]
Thank you for your report.

As noted in the documentation, *uinput* is a Linux based backend and thus does not work on Windows.

**Comment by PowerBroker2** [comment]
1. What documentation? I was only able to find this kwarg in a src docstring that didn't say anything about OS's. Not a big deal, just curious
2. Is it possible to add this feature for windows?

**Comment by moses-palmer** [comment]
The [documentation](https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Listener) describes the prefixed kwargs as *non-standard platform dependent options*. That may be a bit unclear in the context.

I have not found a way to detect the source of the event on Windows, so adding this functionality seems infeasible.
