### ISSUE TITLE
Doesn't support python 3.10.9

### ISSUE THREAD

**Issue by Genwei-Zhang** [moses-palmer/pynput#567]
**Description**
I cannot install conda  with pynput, it is always: Solving environment.
Can you guys update this to make it work with python 3.10?

**Platform and pynput version**
Windows

**Comment by moses-palmer** [comment]
Thank you for your report.

I am afraid that I have very little experience with the _conda_ ecosystem, and thus no idea what would make it not work. I personally have installed this library using _pip_ on most versions of _Python_ since 2.7, excluding _Python 3_ before _3.5_.

**Comment by moses-palmer** [comment]
Given the lack of feedback, and since it appears to be a tooling issue unrelated to this library, I will close this issue. If you think this is incorrect, please reopen.
