### ISSUE TITLE
Pynput with uinput backend in Linux sets incorrect key modifiers

### ISSUE THREAD

**Issue by andrew-palamar** [moses-palmer/pynput#568]
**Description**
Trivial 
```
keyboard.press('7')
keyboard.release('7')
```
leads to ALT + 7 press and release

**Platform and pynput version**
Debian 12 Bookworm;
*pynput* version from master branch;
*pynput* version from [debian package](https://packages.debian.org/bookworm/python3-pynput);
Python3.11.2

**To Reproduce**
In linux it is possible to run pynput without sudo. For that user should be in groups **tty** and **input**. And one little udev rule for /dev/uinput device.

Add user to group **input** to gain access to /dev/uinput and to group **tty** to gain access to *dumpkeys*
```
sudo usermod -a -G input $USER
sudo usermod -a -G tty $USER
```
Add udev rule
```
echo 'KERNEL=="uinput", MODE="0660", GROUP="input"' | sudo tee /etc/udev/rules.d/99-uinput.rules
```
Activate it!
```
sudo udevadm trigger
```
Automatically load uinput module on boot
```
echo "uinput" | sudo tee /etc/modules-load.d/uinput.conf
```
Set envs to use uinput backend
```
export PYNPUT_BACKEND_KEYBOARD=uinput
export PYNPUT_BACKEND_MOUSE=dummy
```
Run example code
```
from pynput.keyboard import Key, Controller

keyboard = Controller()

keyboard.press('7')
keyboard.release('7')
```

generates Alt_r press, then 7 press, then Alt_r release, then 7 release

[dumpkeys --full-table --keys-only output](https://github.com/moses-palmer/pynput/files/12358271/dumpkeys.txt)

**Comment by moses-palmer** [comment]
Thank you for your report.

I have not tested the _uinput_ backend in a while, and given your instructions on how to manage without _root_, I gave it a try. I can no longer get it to work at all; I'm currently on _Ubuntu 23.04_, and the last time I ran it was several versions ago.

I would very much appreciate your contributions if your research should find a solution!

**Comment by andrew-palamar** [comment]
Thank you for reply. This is strange that it does not work at all for you. I have one possible cause in mind. Could you tell if uinput kernel module is loaded:
```
lsmod | grep uinput
```

If no module loaded by default you could fix it like this:
```
echo "uinput" > /etc/modules-load.d/uinput.conf
```

Currently I had to comment out lines 207 - 208 to get rid of extra modifiers. 
https://github.com/moses-palmer/pynput/blob/12acf84dc0f721d91a957da65311497acb664933/lib/pynput/keyboard/_uinput.py#L207

**Comment by andrew-palamar** [comment]
Well I have tested the reciept from my first message and I can not confirm that there are any issue on other Debian 12 installations. 

It seems to work pretty good without any sudo. Probably you could add information from my first message to readme. I think it could be valuable for someone.

**Comment by toddwint** [comment]
> Thank you for reply. This is strange that it does not work at all for you. I have one possible cause in mind. Could you tell if uinput kernel module is loaded:
> 
> ```
> lsmod | grep uinput
> ```
> 
> If no module loaded by default you could fix it like this:
> 
> ```
> echo "uinput" | sudo tee /etc/modules-load.d/uinput.conf
> ```
> 
> Currently I had to comment out lines 207 - 208 to get rid of extra modifiers.
> 
> https://github.com/moses-palmer/pynput/blob/12acf84dc0f721d91a957da65311497acb664933/lib/pynput/keyboard/_uinput.py#L207
> 
> Will try to reproduce on Ubuntu 23.04 once return from vacation.

Operating System: Ubuntu 24.04.1 LTS                               
pynput 1.7.7
Python 3.12.6
printenv XDG_SESSION_TYPE wayland

I have the same issue with uinput sending ALT escape characters along with my text I want to send.

My program listens for 'F3'. Then I send 'sample text 01'. This is what I see on the console screen:
^[OR^[s^[a^[m^[p^[l^[e ^[t^[e^[x^[t 

If I comment out lines 207 and lines 208 of _uinput.py and add a closing ) after line 208 everything works fine.

```
199     def __init__(self):
200         def as_char(k):
201             return k.value.char if isinstance(k, Key) else k.char
202         self._vk_table = self._load()
203         self._char_table = {
204             as_char(key): (
205                 vk,
206                 set()
207                     #| {Key.shift} if i & 1 else set()
208                     #| {Key.alt_gr} if i & 2 else set()
209                     )
210             for vk, keys in self._vk_table.items()
211             for i, key in enumerate(keys)
212             if key is not None and as_char(key) is not None}

```

I haven't looked into this much as I am not a very experienced programmer. I'm just curious if maybe this has to do something with ISO vs ANSI keyboards? I know on ANSI keyboards ALT sends escape characters, and I think ISO keyboards do not do this. Just a thought.  Search "ANSI escape sequences".

If uinput isn't working at all on your device on Ubuntu 23.04 maybe you have to select the correct /dev/input/event0 device? Try python3 -m evdev.evtest to verify which device to use?

I can also confirm I am able to use uinput without sudo using the commands specified by @andrew-palamar in the initial post. +1. I am very happy about that. I think it should be added to the documentation. This is a better approach as for example my program launches a tkinter window and allows the user to save files. If it is launched as root the file would have a different owner and group. But launched as a user with permissions to an input group it is saved with the user's name and group.
