### ISSUE TITLE
Cannot install on linux Ubuntu (depends on pywin32)

### ISSUE THREAD

**Issue by vricosti** [moses-palmer/pynput#598]
pip3 install pyinput
Collecting pyinput
  Using cached pyinput-0.3.2-py2.py3-none-any.whl.metadata (383 bytes)
INFO: pip is looking at multiple versions of pyinput to determine which version is compatible with other requirements. This could take a while.
  Using cached pyinput-0.3.1-py2.py3-none-any.whl.metadata (383 bytes)
  Using cached pyinput-0.3.0-py2.py3-none-any.whl.metadata (383 bytes)
  Using cached pyinput-0.2.0-py2.py3-none-any.whl.metadata (382 bytes)
  Using cached pyinput-0.1.0-py2.py3-none-any.whl.metadata (382 bytes)
ERROR: Cannot install pyinput==0.1.0, pyinput==0.2.0, pyinput==0.3.0, pyinput==0.3.1 and pyinput==0.3.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    pyinput 0.3.2 depends on pywin32
    pyinput 0.3.1 depends on pywin32
    pyinput 0.3.0 depends on pywin32
    pyinput 0.2.0 depends on pywin32
    pyinput 0.1.0 depends on pywin32

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

Dont understand how to install pyinput on linux ...

**Comment by vricosti** [comment]
I have also tried on a virtual machine running the last Ubuntu (24.04 LTS) and same error message.

**Comment by moses-palmer** [comment]
Thank you for your report.

This is the repository for the library _pynput_, not _pyinput_. I will close this issue.
