### ISSUE TITLE
Get device ID for active mouse

### ISSUE THREAD

**Issue by pdo-smith** [moses-palmer/pynput#610]
**Question**
How can I get the device ID for the active mouse?

Background
I have a trackball and a mouse attached to my computer. I want to identify which device is the source of mouse.Listener() events so that can take different courses of action depending on whether the mouse.Listener() events come from the trackball device or the mouse device

**Platform and pynput version**
Ubuntu Linux

**Comment by moses-palmer** [comment]
I do not think this information is available when running under _Xorg_.

The events received by this library are described [here](https://tronche.com/gui/x/xlib/events/keyboard-pointer/keyboard-pointer.html) and do not contain any device identifier.
