### ISSUE TITLE
Python 3.13 unsupported

### ISSUE THREAD

**Issue by noahpodgurski** [moses-palmer/pynput#612]
**Description**
Python 3.13: Not Implemented

**Platform and pynput version**
Windows 10, Pynput@1.7.7

**To Reproduce**
Install Python 3.13 and pynput, and attempt to run.

**Comment by moses-palmer** [comment]
Thank you for your report.

I believe this is related to #614. Please see [this comment](https://github.com/moses-palmer/pynput/issues/614#issuecomment-2471355907) for a proposed fix. I would appreaciate if you could try it out!
