### ISSUE TITLE
invalidCharacterException when typing \n

### ISSUE THREAD

**Issue by bostrt** [moses-palmer/pynput#64]
I'm not sure if it is safe or how a `\n` should be handled but figured I would report it here:

```
  File "./script.py", line 41, in notify
    keyboard.type(phrase)
  File "/home/user/code/v/lib/python3.6/site-packages/pynput/keyboard/_base.py", line 453, in type
    raise self.InvalidCharacterException(i, character)
pynput.keyboard._base.InvalidCharacterException: (6, '\n')
```

**Comment by moses-palmer** [comment]
*pynput* does not support typing any control characters---you will get the same result if you try `pynput.keyboard.Controller().type('hello\tworld')`. Changing this would subtly break the API, so it would mean incrementing at least the minor version number.

If this feature should be added, perhaps it should be limited to `pynput.keyboard.Controller.type`? It would be rather straight-forward to add a filter when iterating over the character of the input string.

**Comment by moses-palmer** [comment]
I have merged this feature into master. It will be included in the next release.
