### ISSUE TITLE
How can I detect a double click?

### ISSUE THREAD

**Issue by gabycperezdias** [moses-palmer/pynput#67]
Is there any built-in property to let me know or will I have to compare time and distance between clicks?

**Comment by moses-palmer** [comment]
There is currently no way to detect double click events using *pynput*, so for the time being, you will have to do as you suggest.

Some platforms, such as *OSX* or *macOS*, do provide this information however, so I'll add it to the road map.

**Comment by gabycperezdias** [comment]
Thanks!
