### ISSUE TITLE
how to compile it 

### ISSUE THREAD

**Issue by goldalworming** [moses-palmer/pynput#7]
Hi, can you give example to compile it with pyinstaller?

**Comment by moses-palmer** [comment]
[This](https://github.com/moses-palmer/virtual-touchpad) project uses *pynput* while also packaging with *pyinstaller*. If you take a look at [the spec file](https://github.com/moses-palmer/virtual-touchpad/blob/master/pyi/VirtualTouchpad.spec), you'll see that it requires no special considerations.
