### ISSUE TITLE
Is there any example on how to suppress keyboard events locally ?

### ISSUE THREAD

**Issue by karamjaber** [moses-palmer/pynput#70]
I'm trying to create a listener using pynput which gets the keystrokes from the user and suppress them.
From the documentation i saw the following : 
`pynput.keyboard.Listener(on_press=None, on_release=None, **kwargs)`
 
Where kwargs supposed to be **win32_event_filter** for windows.

I didn't understand how to use this.
Do you have any example?

**Comment by moses-palmer** [comment]
Hi,

I am planning on adding this feature in a platform-agnostic manner for *pynput 1.4*. I will keep issue #68 open until the feature is added, and close this one to keep the issues list tidy.
