### ISSUE TITLE
Why ctrl + key generates hex on keyboard listener?

### ISSUE THREAD

**Issue by karamjaber** [moses-palmer/pynput#71]
When I press ctrl+ some key simultaneously I get a hex instead of ctrl button and then the other key.
for example: ctrl + c generates "\x13"  .

but for the other modifiers, it generates 2 keys for example shift + c will  generate "shift" and then "c"

**Comment by moses-palmer** [comment]
What operating system do you use?

**Comment by karamjaber** [comment]
Windows 8.1

**Comment by moses-palmer** [comment]
I have actually managed to reproduce this.

I normally try to reproduce issues on _Windows_ by running a test script in _Command Prompt_. Doing that for this issue initially does not reveal anything strange---keys are reported normally even with _ctrl_ pressed.

If, however, focus is shifted to a different window, normal keys are indeed transformed to hex codes. The effect starts as soon as focus leaves the _Command Prompt_, and it is not resolved until both _ctrl_ is released and focus returned.

Strange.

**Comment by moses-palmer** [comment]
This issue seems to have been fixed by commit [63aab1a](https://github.com/moses-palmer/pynput/commit/63aab1acf3b66b37f4ebac72be958a505e382a06), so I will close this issue.

Please reopen if you still experience the same issue.

**Comment by isecvirus** [comment]
Hey buddy.. the problem still exists till now, even in the prompt of windows 10/11.

also i wouldn't keep running it from the prompt even if it works.
