### ISSUE TITLE
Feature Request: Listener passes keycode for alphanumeric keys

### ISSUE THREAD

**Issue by TheoRet** [moses-palmer/pynput#73]
if I understand it right, the following happens when listening for keys and an alphanumeric key is pressed:

The keyboard.Listener instance will pass a keyboard.Keycode object to the callback function. Lets call it mykey. Now mykey.char is set, but mykey.vk is None.

Is there a reason why mykey.vk does not contain the keycode? This would be useful additional information.

**Comment by moses-palmer** [comment]
There is, as far as I can see, no reason.

I'll add it to the road map. Once testing, bug reports and feature requests stabilise I'll get around to releasing the next version.

**Comment by moses-palmer** [comment]
I have pushed changes addressing this to *mater*.

Now all keyboard events, except for special keys which are sent as [Keys](https://github.com/moses-palmer/pynput/blob/31fef7f57e68ea16f58f9696a60dd4d8a45aabbe/lib/pynput/keyboard/_base.py#L146), include the platform representation of a virtual key code.
