### ISSUE TITLE
Handle shortcuts

### ISSUE THREAD

**Issue by LegnaRuoy** [moses-palmer/pynput#78]
@moses-palmer Hello, I want make program which exit when I touch shortcut: Control_R+Q

I have this code:
```
from time import sleep
from pynput import keyboard

QUIT_READY = False

def on_press(key):
    #if key == keyboard.Key.ctrl_r:
    #    QUIT_READY = True

    if str(type(key)) != "<enum 'Key'>":
        if key.char == 'q': 
            print QUIT_READY
            if QUIT_READY == True:
                return False
    #else:
    #    QUIT_READY = False

keyboard_thread = keyboard.Listener(on_press=on_press)
keyboard_thread.start()

while keyboard_thread.running:
    sleep(0.1)

```
but it is not working right when I uncomment the 4 lines because I cannot write into 
QUIT_READY variable probably..
Do you please know, how can I add any my variables into pynput.keyboard.Listener thread??
Or exists some better solution how handle shortcuts in the pynput??

**Comment by moses-palmer** [comment]
As `QUIT_READY` is a global variable, you cannot assign a value to it from inside of `on_press` unless you have declared it as [global](https://docs.python.org/3/reference/simple_stmts.html#the-global-statement): `global QUIT_READY` somewhere in `on_press`.
