### ISSUE TITLE
Passing floats as coordinate values for mouse movement causes crash on Windows, but not Mac

### ISSUE THREAD

**Issue by Jadiker** [moses-palmer/pynput#79]
On a Mac, if I do
```
mouse = Controller()
mouse.position = (20.5, 20.5)
```
it works just fine.

On Windows, if I do
```
mouse = Controller()
mouse.position = (20.5, 20.5)
```
it crashes with
> ctypes.ArgumentError: argument 1: <class 'TypeError'>: Don't know how to convert parameter 1

It would be great if a wrapper could be added around Windows so that it automatically called `int` on both of the parameters if the Windows platform was being used.

**Comment by moses-palmer** [comment]
Thank you for your report!

I have merged a fixup branch to master addressing this issue for both _Windows_ and _Xorg_. It will be included in the upcoming _1.4_ release once I have worked through the issue list a bit more.

I will close this issue; if it is not resolved, please reopen.
