### ISSUE TITLE
String representation includes quotes.

### ISSUE THREAD

**Issue by nelydajo** [moses-palmer/pynput#8]
I copied your example code on Monitoring the keyboard into a file called pynput_listener.py and ran it with Python 3.5 on Ubuntu Linux. I get the following output:

> $ python3 pynput_listener.py 
> 'a' pressed
> a'a' release
> 'b' pressed
> b'b' release
> 'c' pressed
> c'c' release
> Key.esc pressed
> ^[Key.esc release

The line of code `print('{0} pressed'.format(key))` is returning a string with two embedded quote characters. 

Similarly, if I change those lines to just `print(str(key))` I get:

> $ python3 pynput_listener.py 
> 'a'
> a'a'
> 'b'
> b'b'
> 'c'
> c'c'
> Key.esc
> ^[Key.esc 

Shouldn't `str(key)` return a single character string, and not a 3-character string, that includes quotes?

**Comment by moses-palmer** [comment]
I guess this is a matter of taste; the string representation should only be used for display purposes. 

If you want to get the actual string programmatically, use the `char` attribute; if you change `key` in the examples to `key.char`, it will print as you expect.

**Comment by nelydajo** [comment]
I will use `key.char`. Thank you.
