### ISSUE TITLE
Getting Layout from active thread cause a problem

### ISSUE THREAD

**Issue by Schmettaling** [moses-palmer/pynput#80]
Hello,
I try to record the keyboard events a different program gets. When I record, the program stops to react to them. It will start reacting wenn I stop the record.

I solved my problem by changing line 643-645 in  \pynput\_util\win32.py  , thats:
```
643 remote_thread = self._GetWindowThreadProcessId(
644            self._GetForegroundWindow(),
645            None) 
```
to
`643 remote_thread = GetCurrentThreadId()`

So if  I dont touch the thread (I do not know why) and there is a better way to do it, the Program reacts to them while recording and my problem is solved.

I would appreciate to know why this happens.

**Comment by moses-palmer** [comment]
Thank you!

I have updated the code in question to ignore the thread input of the active window altogether. Doing so seems to have fixed #71 as well.

I have pushed the fix to master, but I have another feature branch that I would like to merge before making a new release.
