### ISSUE TITLE
Is it possible to click on x,y coordinates on the screen while windows is locked?

### ISSUE THREAD

**Issue by karamjaber** [moses-palmer/pynput#81]
I'm working on a software which has to click on some fixed coordinates on the screen(When he gets a trigger).
When in Windows, it works perfectly.
But if I lock the screen it doesn't work(I guess that it clicks on the lock screen of windows), Is it possible to click on coordinates while it's locked?

**Comment by moses-palmer** [comment]
I very much doubt that.

I general, *pynput* can only be used within a user session; it cannot even be used from a service because of restrictions inherent in the operating system.
