### ISSUE TITLE
How do you simulate mouse drag

### ISSUE THREAD

**Issue by abhigenie92** [moses-palmer/pynput#82]
```
mouse = Controller()
x,y = 1450.1640625, 600.0234375
mouse.press(Button.left)
while x<1919:
    x += 1
    mouse.position =(x,y)
mouse.release(Button.left)
```
Above code doesn't work

**Comment by moses-palmer** [comment]
On what platform have you tested this?

Commit [0b69c82](https://github.com/moses-palmer/pynput/commit/0b69c825fd919a261c84ec7d16f0c8ec7551f612) corrected issues with non-integer coordinates. Could you try again with the *master* version to see whether this issue has been resolved?

**Comment by moses-palmer** [comment]
I assume that testing with *master* resolved the issue, and will close this issue.

If it persists, please reopen.
