### ISSUE TITLE
On macos, keyboard.type('abcdefg !@#$%^&*()') generates 'abcdefg aaaa6a78aa^Z'

### ISSUE THREAD

**Issue by naftalibeder** [moses-palmer/pynput#83]
In addition, trying to create shifted special characters by using

    with keyboard.pressed(Key.shift):
        keyboard.press('-')

fails to shift the character. Is there any way to simulate key pressed for characters like '_' (underscore)?

**Comment by soggychips** [comment]
I'm having the same issue. Works fine on windows.

**Comment by zac-garby** [comment]
I'm having the same problem too. Does anybody know a workaround?

**Comment by naftalibeder** [comment]
I've had good luck in the meantime with https://github.com/asweigart/pyautogui - it's more heavyweight but works well.
