### ISSUE TITLE
Blocking or non-blocking?

### ISSUE THREAD

**Issue by karth2512** [moses-palmer/pynput#85]
The listener.join() seems to be blocking. So it severely restricts the applications of this package. 
The thread should remotely monitor the keystrokes while simultaneously running the rest of the program.
That is how an "event-trigger" would be best put to use, i guess.
P.S : Sorry if i am wrong , Anyway to run it in a "non-blocking" manner?

**Comment by moses-palmer** [comment]
The way to run it in non-blocking mode is to not call join(). The context
manager-join pattern is used in examples to make them simpler, but have a
look at the documentation of the constructors of the listener classes for
non-blocking patterns.

**Comment by Wtcheesecakes** [comment]
how would i do it without using join cant see anything in docs
