### ISSUE TITLE
Keyboard.listener lags

### ISSUE THREAD

**Issue by WonderMr** [moses-palmer/pynput#88]
I use keyboard.listner in separate thread. Something like this

```
def on_press(key):
    global globs
    globs._key_presses                                      +=  1
    globs._last_act_time                                    =   datetime.datetime.today()
    if globs._sleeping:
        globs._sleeping                                     =   False
        globs._got_waked                                    =   True

listener                                                =   pynput_keyboard.Listener(on_press=on_press)
listener.start()

```
Sometimes i got terrible lags while switching keyboard input language(with alt+shift, i'm on Windows)
Sometimes it work fine. I can't detect any reasonable cause.

By the way, switching input languagewith win+space(Windows too))) work perfecly all the time
Is there anything i do incorrectly?

**Comment by moses-palmer** [comment]
Thank you for your report; I'll look into this.

**Comment by WonderMr** [comment]
> Thank you for your report; I'll look into this.
Is there anything i can help with?

**Comment by moses-palmer** [comment]
You could add some logging [here] (https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/win32.py#L374). That line is among the first inside the library to be invoked by the operating system.

**Comment by moses-palmer** [comment]
Did your investigation reveal anything? Would you mind posting a minimal code sample so that I can test?

**Comment by WonderMr** [comment]
Hello, unfortunately i did stop my investigation satisfied by workaround
Here is o code sample that reproduce the problem
```
import threading, pynput, time
presses                                     =   0
class thread_keyboard(threading.Thread):
    listener                                =   None
    def __init__(self, name):
        threading.Thread.__init__(self)
        self.name                           =   name
        self.listener                       =   pynput.keyboard.Listener(on_press = thread_keyboard.on_press)
    def on_press(key):
        global presses
        presses                             +=  1

keyboard                                    =   thread_keyboard("thread.listener.keyboard")
keyboard.listener.start()
while(True):
    time.sleep(0.01)

```

**Comment by moses-palmer** [comment]
I tested your code sample after correcting it to work on _Python 3_---then you need a `@staticmethod` decorator for `thread_keyboard.on_press`.

I do not experience any lag. However, is the code above at all representative of your actual application? I would strongly advice against using a busy loop---this will attempt to acquire the GIL every 100 ms, something which may cause the lag that you experience. And is there a reason that you wrap the listener in a `Thread`? In the example above, it does not serve any purpose, as you do not actually start it. The *pynput* listeners are threads themselves, so you generally do not have to worry about threading.

**Comment by WonderMr** [comment]
Thank you. I aprreciate your advices, but this is just a sample. 
If you wish i can record a video thet reproduce problem. Perhaps i miss some details that will be present on screen record.
