### ISSUE TITLE
Is there a way to run mouse listener with focus on some window?

### ISSUE THREAD

**Issue by karamjaber** [moses-palmer/pynput#89]
I need to run the mouse listener only when some window is in the foreground .
Does your library support this ?

**Comment by WonderMr** [comment]
This library capture whole mouse input. You can track active window and process mouse activity while active window you need

**Comment by moses-palmer** [comment]
As @WonderMr says, you'll have to track active widows yourself and fillet out events. This is our of scope for _pynput_.
