### ISSUE TITLE
Keyboard and mouse listeners on WinXP 

### ISSUE THREAD

**Issue by s00ler** [moses-palmer/pynput#93]
Hello! I use pynput in my masters research, but unfortunately many PCs in my university are running WinXP. So controlling mouse/keyboard works well, but when i try to run any monitoring example from docs it just does not receive any presses or other actions, so my program stuck on waiting for event.
I would be grateful if anyone can suggest solution for me.

**Comment by moses-palmer** [comment]
Since this issue relates to a legacy operating system, I will close it.
