### ISSUE TITLE
how do i run pynput listener and tkinter object at the same time

### ISSUE THREAD

**Issue by slamjeron** [moses-palmer/pynput#97]
so fare i have tried this and it ends up runing my listeners then when my listeners are done my tkinter main loop will run. parent is my tkinter.Tk object and mouse and key are both pynput objects

     with key.Listener(on_press=self.OnKeyPress) as lis:
                with mouse.Listener(on_click=self.on_click) as self.listener:
                    with parent.mainloop() as self.p:
                        self.p.join()

**Comment by moses-palmer** [comment]
I would think that the mainloops compete for attention from the system. Have you tried running the _pynput_ mainloop in a separate thread?

**Comment by moses-palmer** [comment]
I will close this issue since I suspect that my suggestion worked.

Please reopen if the problem persists.

**Comment by ReuMOO** [comment]
I tried that and it didn't work my program that I am trying to create, even if i make a very simple example such as:
![image](https://user-images.githubusercontent.com/49539778/60005372-b3b6f300-96b1-11e9-9755-575a8d059ab3.png)
the code about will not run the pynput listener code and will only run the mainloop code.

If I were to put it inside of the mainloop it would freeze as soon as the first listener is made, even if I stop the listener instantly after. Putting the pynput before making the tkinter mainloop will result in only the pynput working. Please help! I have tested my code for flaws and I know it works fine, if you have a resolution to this problem it would really help, or perhaps an alternative listening module I can use in the same way (to detect any keyboard events and run a function as soon as it detects anything) thanks.

**Comment by ReuMOO** [comment]
Actually I found the answer, It was to use threading for the tk mainloop. I created a class with multiple functions one with the listener in it and one with the tk code. Through threading I ran the tk code with the mainloop and then created a thread the would continuously run the  listener. Here is an example:
`
import threading
from tkinter import *
import time
stop=False
from pynput.keyboard import Key, Listener
root=Tk()
class TestClass():
    def test_f(*self):
       ##prints consecutive numbers over and over just to show the power of the threading module to handle multiple infinite loops at once
        ctr = 0
        while True:
            print(ctr)
            ctr += 1
            time.sleep(1.0)
            if stop == True:
                break
    def print_key(*key):
        print(key)
        if stop==True:
            return False
    def key(self):
        with Listener(on_press=CT.print_key) as listener:
            listener.join()
    def tk_code(self):
        button1= Button(root,height=10,text="stop program", command=quit,
                  width=10).grid()
        root.mainloop()
__name__= '__main__'
print(__name__)
if __name__ == '__main__':
     print("worked")
     ## run function in the background
     CT=TestClass()

     ## start as many processes as you want
     p1 = threading.Thread(target=CT.test_f)
     p1.start()
     p2 = threading.Thread(target=CT.key)
     p2.start()

     CT.tk_code()
     print("terminate process")
     for p in [p1, p2]:
         if stop== False:
             stop=True
         p.join()
`

**Comment by moses-palmer** [comment]
I strongly suspect that this will not work in a platform-independent manner---On at least *macOS*, the Tkinter mainloop must be started from the main thread.

A `Listener` is also a thread, so a simpler solution would be to not join the thread as you do in your posted samples would be to use the non-blocking sample [here](https://pynput.readthedocs.io/en/latest/keyboard.html#monitoring-the-keyboard). You would then invoke it thus:
```python
listener = keyboard.Listener(on_press=other_function)
listener.start()
root.mainloop()
```

**Comment by calebgood** [comment]
I wanted to do a similar thing...like I have a mouse listener which prints the coordinates of the mouse on_click....and an empty tkinter window with a label to update the coordinates....but the listener and the main loop of tkinter are contradicting....is there a way to solve this ?

**Comment by Golder06** [comment]
I just tried what moses said, but it says that the "name 'keyboard' is not defined"
