### ISSUE TITLE
How to make the mouse/keyboard wait before a program open

### ISSUE THREAD

**Issue by wayoalamos** [moses-palmer/pynput#98]
I want to open a program and wait until it is open before start typing in. I tried with time.sleep but it didnt work.

from pynput.mouse import Controller, Button

mouse = Controller()
mouse.position = (320,800)
mouse.click(Button.left, 1)
mouse.position = (600,600)
mouse.click(Button.left, 1) #i want to click inside the opened program

But because the code runs faster than opening the program, obviously is not doing click in it.
how to wait until the program is opened?

**Comment by moses-palmer** [comment]
This is unfortunately out of scope for _pystray_; this library is aimed at simulating input devices, not automating GUIs. Have you tried [LDTP](https://ldtp.freedesktop.org/wiki/)?
